-- Execute uma vez no SQL Editor do Supabase para compartilhar avaliações.
create table if not exists public.game_feedback (
  id bigint generated by default as identity primary key,
  player_name text not null check (char_length(player_name) between 1 and 20),
  rating smallint not null check (rating between 1 and 5),
  comment text not null check (char_length(comment) between 1 and 500),
  created_at timestamptz not null default now()
);
alter table public.game_feedback enable row level security;
do $$ begin
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='game_feedback' and policyname='avaliações visíveis') then create policy "avaliações visíveis" on public.game_feedback for select using (true); end if;
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='game_feedback' and policyname='avaliações publicáveis') then create policy "avaliações publicáveis" on public.game_feedback for insert with check (true); end if;
end $$;
