(() => {
  const canvas=document.querySelector('#arena'),ctx=canvas.getContext('2d');
  const ui={shell:document.querySelector('.game-shell'),arenaWrap:document.querySelector('.arena-wrap'),score:document.querySelector('#score'),accuracy:document.querySelector('#accuracy'),combo:document.querySelector('#combo'),stage:document.querySelector('#stage'),stageTime:document.querySelector('#stageTime'),stageProgress:document.querySelector('#stageProgress'),sectorName:document.querySelector('#sectorName'),sceneName:document.querySelector('#sceneName'),bossHud:document.querySelector('#bossHud'),bossName:document.querySelector('#bossName'),bossFill:document.querySelector('#bossFill'),bossHealth:document.querySelector('#bossHealth'),powerStatus:document.querySelector('#powerStatus'),health:document.querySelector('#health'),announcement:document.querySelector('#announcement'),phase:document.querySelector('#phase'),threat:document.querySelector('#threatFill'),start:document.querySelector('#start'),gameMode:document.querySelector('#gameMode'),difficulty:document.querySelector('#difficulty'),arcadeSceneLabel:document.querySelector('#arcadeSceneLabel'),arcadeScene:document.querySelector('#arcadeScene'),survivalActions:document.querySelector('#survivalActions'),pauseSurvival:document.querySelector('#pauseSurvival'),stopSurvival:document.querySelector('#stopSurvival'),fire:document.querySelector('#fire'),sound:document.querySelector('#sound'),rankingName:document.querySelector('#rankingName'),saveRanking:document.querySelector('#saveRanking'),restartCampaign:document.querySelector('#restartCampaign'),rankingMode:document.querySelector('#rankingMode'),rankingBody:document.querySelector('#rankingBody'),rankingMessage:document.querySelector('#rankingMessage'),careerSummary:document.querySelector('#careerSummary'),awards:document.querySelector('#awards')};
  const profiles={easy:{hp:[1,2],spawn:1900,speed:72,cannons:3},medium:{hp:[3,5],spawn:1450,speed:90,cannons:4},hard:{hp:[6,9],spawn:1100,speed:108,cannons:5}};
  const result={panel:document.querySelector('#stageResult'),sector:document.querySelector('#resultSector'),title:document.querySelector('#resultTitle'),medal:document.querySelector('#resultMedal'),points:document.querySelector('#resultPoints'),accuracy:document.querySelector('#resultAccuracy'),destroyed:document.querySelector('#resultDestroyed'),combo:document.querySelector('#resultCombo'),health:document.querySelector('#resultHealth'),bonus:document.querySelector('#resultBonus'),message:document.querySelector('#resultMessage'),next:document.querySelector('#nextStage'),newCampaign:document.querySelector('#newCampaign'),retry:document.querySelector('#retryStage'),pause:document.querySelector('#pauseCampaign')};
  const tutorial={open:document.querySelector('#openTutorial'),overlay:document.querySelector('#tutorialOverlay'),progress:document.querySelector('#tutorialProgress'),icon:document.querySelector('#tutorialIcon'),step:document.querySelector('#tutorialStep'),title:document.querySelector('#tutorialTitle'),text:document.querySelector('#tutorialText'),back:document.querySelector('#tutorialBack'),skip:document.querySelector('#tutorialSkip'),next:document.querySelector('#tutorialNext')};
  const tutorialSteps=[
    ['🔥','Bem-vindo ao Fogo Cruzado','Defenda o minicanhão até o tempo terminar. Nas fases de mestre, a vitória só acontece depois de eliminar o chefe.'],
    ['↕️','Movimente o canhão','No computador, use ↑ e ↓, clique na altura desejada ou arraste o mouse. No celular, deslize o dedo verticalmente sobre a pista.'],
    ['💥','Dispare','Toque ou segure o botão FIRE na coluna direita. No computador, a barra de espaço também dispara.'],
    ['①','Respeite a prioridade','Destrua primeiro a pedra marcada com 1. Quando ela cair, a próxima assume a prioridade. Tiros atravessam ameaças fora da ordem.'],
    ['🎯','Precisão fortalece','Quanto maior sua precisão, maiores ficam os tiros. Acima de 82%, o canhão causa dano adicional.'],
    ['♥','Proteja sua energia','Impactos retiram energia. No Treino livre eles são registrados, mas não encerram a partida.'],
    ['⚡','Colete power-ups','Atire nas cápsulas brilhantes para ativar tiro duplo, turbo, perfuração, escudo, cura ou pulso destruidor.'],
    ['🌊','Observe o ritmo','As ondas aceleram, atingem o perigo máximo e desaceleram. Escolha entre Campanha, Sobrevivência, Tempo e Treino livre.']
  ];
  let tutorialIndex=0,tutorialWasRunning=false;
  const sectors=[
    {family:'OFICINAS',colors:['#ead28e','#c99c56','#172b38','#805336','#ffb43d'],effect:'equilíbrio',names:['Bancada do Inventor','Oficina Abandonada','Depósito de Ferramentas','Carpintaria Solar','Sala das Engrenagens','Esteira de Montagem','Caldeira Antiga','Oficina Elétrica','Galpão Industrial','Oficina do Mestre']},
    {family:'FORTALEZAS',colors:['#b9b3a1','#777467','#222a31','#51483d','#e0a84d'],effect:'pedras reforçadas',names:['Portão de Pedra','Muralha do Norte','Pátio dos Escudos','Torre do Vigia','Corredor das Armaduras','Ponte Fortificada','Salão dos Estandartes','Masmorra Profunda','Bastião Real','Cidadela do Colosso']},
    {family:'INDÚSTRIAS',colors:['#b7a278','#75684d','#182b32','#4f4435','#ff8b32'],effect:'produção acelerada',names:['Linha de Produção','Prensa Hidráulica','Armazém de Aço','Tubulação Central','Usina de Vapor','Turbinas Gêmeas','Fundição Laranja','Forja Automatizada','Núcleo da Fundição','Máquina Suprema']},
    {family:'GELEIRAS',colors:['#d8f5f4','#7fbac7','#173344','#376878','#8ff5ff'],effect:'rastros congelados',names:['Lago Congelado','Gruta de Cristal','Passagem Boreal','Vale da Nevasca','Ponte de Gelo','Caverna Azul','Muralha Glacial','Aurora Silenciosa','Coração do Inverno','Trono de Gelo']},
    {family:'VULCÕES',colors:['#6f3a2d','#321d21','#20151a','#68261e','#ff612f'],effect:'pedras velozes',names:['Fenda Ardente','Galeria de Cinzas','Rio de Lava','Cratera Rubra','Câmara de Magma','Forja Vulcânica','Chuva de Brasas','Abismo Incandescente','Coração da Montanha','Titã do Vulcão']},
    {family:'FLORESTAS',colors:['#b9ce83','#62804e','#162d28','#3c5d3b','#e6d95c'],effect:'trajetórias sinuosas',names:['Clareira Antiga','Bosque dos Ecos','Trilha de Musgo','Jardim Selvagem','Árvores Gigantes','Ruínas Verdes','Pântano Luminoso','Templo das Raízes','Copa Encantada','Guardião da Floresta']},
    {family:'DESERTOS',colors:['#e9c477','#bd7541','#33241f','#77452c','#ffe16b'],effect:'tempestade de areia',names:['Dunas Douradas','Cânion Seco','Oásis Perdido','Templo de Areia','Mar de Dunas','Ruínas do Sol','Tempestade Âmbar','Pirâmide Interior','Olho do Deserto','Faraó de Pedra']},
    {family:'MEGACIDADES',colors:['#7586a8','#333c5c','#12182c','#293259','#ff4fd8'],effect:'canhão adicional',names:['Distrito Neon','Avenida Magnética','Metrô Suspenso','Fábrica de Androides','Torre Holográfica','Rede Central','Laboratório Quântico','Núcleo Cibernético','Cidade Vertical','Inteligência Suprema']},
    {family:'ESPAÇO',colors:['#20264d','#080d24','#070b18','#242c59','#68dfff'],effect:'gravidade instável',names:['Órbita Terrestre','Campo de Asteroides','Lua Sombria','Nebulosa Azul','Estação Perdida','Anéis de Saturno','Cometa Errante','Portal Estelar','Horizonte Cósmico','Nave-Mãe']},
    {family:'DIMENSÃO FINAL',colors:['#573068','#1b102d','#0c0916','#3a1d4d','#ffcf4b'],effect:'ameaças combinadas',names:['Portal do Caos','Espelho Partido','Corredor Impossível','Vazio Pulsante','Cidade Invertida','Relógio Cósmico','Labirinto Final','Olho da Tempestade','Última Muralha','Coração do Fogo Cruzado']}
  ];
  const sceneFor=stage=>{const sector=Math.min(9,Math.floor((stage-1)/10)),index=(stage-1)%10,base=sectors[sector];return{...base,sector,index,name:base.names[index]}};
  function populateArcadeScenes(){ui.arcadeScene.innerHTML=sectors.map((scene,index)=>`<option value="${index*10+1}">Tela ${index+1} · ${scene.family}</option>`).join('')}
  function refreshModeControls(){const mode=ui.gameMode.value,arcade=mode!=='campaign',hasModeActions=mode==='survival'||mode==='training';ui.arcadeSceneLabel.hidden=!arcade;ui.survivalActions.hidden=!hasModeActions;ui.pauseSurvival.hidden=mode!=='survival';ui.stopSurvival.textContent=mode==='training'?'Encerrar treino livre':'Encerrar sobrevivência';if(!arcade&&!state.running){state.stage=loadCampaign().currentStage;updateHud();draw()}if(mode==='survival'&&!state.running){const saved=localStorage.getItem(SURVIVAL_KEY);ui.start.textContent=saved?'Continuar sobrevivência':'Iniciar defesa';ui.pauseSurvival.textContent=saved?'Continuar sobrevivência':'Pausar e continuar depois'}else if(!state.running&&!state.transitioning)ui.start.textContent='Iniciar defesa'}
  const bossNames=['Mestre das Engrenagens','Colosso da Cidadela','Máquina Suprema','Soberano Glacial','Titã do Vulcão','Guardião das Raízes','Faraó de Pedra','Inteligência Suprema','Nave-Mãe','Coração do Fogo Cruzado'];
  const powerInfo={double:{name:'Tiro duplo',icon:'⑵',color:'#54d8ff',duration:9},rapid:{name:'Cadência turbo',icon:'»',color:'#ffca45',duration:8},pierce:{name:'Disparo perfurante',icon:'➤',color:'#c987ff',duration:9},shield:{name:'Escudo',icon:'◆',color:'#67e79a'},heal:{name:'Energia',icon:'♥',color:'#ff667b'},bomb:{name:'Pulso destruidor',icon:'✹',color:'#ff8a42'}};
  const isBossStage=stage=>stage%10===0;
  let state,raf,last=0,audio,soundOn=true,fireHeld=false,fireClock=0,moveDirection=0;
  const clamp=(n,min,max)=>Math.max(min,Math.min(max,n)),random=(min,max)=>min+Math.random()*(max-min);
  const SAVE_KEY='qqfCampaignV1';
  const SURVIVAL_KEY='qqfSurvivalV1';
  const HALL_KEY='qqfHallV1';
  const LEGACY_KEY='qqfLegacyV1';
  const savedStage=()=>clamp(Number(localStorage.getItem('qqfUnlockedStage'))||1,1,100);
  function loadCampaign(){try{const saved=JSON.parse(localStorage.getItem(SAVE_KEY)||'null');if(saved?.version===1)return{...saved,currentStage:clamp(Number(saved.currentStage)||savedStage(),1,100),unlockedStage:clamp(Number(saved.unlockedStage)||savedStage(),1,100)}}catch{}return{version:1,currentStage:savedStage(),unlockedStage:savedStage(),score:0,difficulty:'easy',totalTime:0,totalDestroyed:0,destroyedByType:{},bossesDefeated:0,perfectDefenses:0,bestAccuracy:0,bestCombo:1,medals:{}}}
  function saveCampaign(overrides={}){const old=loadCampaign(),data={...old,version:1,currentStage:state.stage,unlockedStage:Math.max(old.unlockedStage,state.stage),score:state.score,difficulty:ui.difficulty.value,totalTime:state.totalTime||0,totalDestroyed:state.totalDestroyed,destroyedByType:{...state.destroyedByType},bossesDefeated:state.bossesDefeated,perfectDefenses:state.perfectDefenses,bestAccuracy:Math.max(old.bestAccuracy||0,state.bestAccuracy||0),bestCombo:Math.max(old.bestCombo||1,state.maxCombo||1),medals:{...(old.medals||{})},...overrides};localStorage.setItem(SAVE_KEY,JSON.stringify(data));localStorage.setItem('qqfUnlockedStage',String(data.unlockedStage));return data}
  const makeRunId=()=>`run-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,9)}`;
  function hallPerformanceKey(entry){return`${entry.score}|${entry.difficulty}|${entry.accuracy}|${entry.bosses}|${entry.perfect}`}
  function loadHall(){try{const value=JSON.parse(localStorage.getItem(HALL_KEY)||'[]');if(!Array.isArray(value))return[];const unique=new Map();value.forEach(entry=>{const legacyKey=hallPerformanceKey(entry),runId=entry.runId||`legacy-${legacyKey}`,mode=entry.mode||'campaign';unique.set(runId,{wave:mode==='campaign'?100:1,destroyed:entry.destroyed||0,combo:entry.combo||1,time:entry.time||0,screen:entry.screen||(mode==='campaign'?'Fase 100':'Tela 1'),date:entry.date||new Date(0).toISOString(),...entry,mode,runId})});const normalized=[...unique.values()];if(JSON.stringify(normalized)!==JSON.stringify(value))localStorage.setItem(HALL_KEY,JSON.stringify(normalized));return normalized}catch{return[]}}
  function loadLegacy(){try{return{finished:false,bosses:0,perfect:0,bestAccuracy:0,gold:0,campaigns:0,...JSON.parse(localStorage.getItem(LEGACY_KEY)||'{}')}}catch{return{finished:false,bosses:0,perfect:0,bestAccuracy:0,gold:0,campaigns:0}}}
  function archiveCampaign(){const campaign=loadCampaign(),legacy=loadLegacy(),gold=Object.values(campaign.medals||{}).filter(value=>value==='gold').length;localStorage.setItem(LEGACY_KEY,JSON.stringify({finished:legacy.finished||campaign.currentStage>=100,bosses:legacy.bosses+(campaign.bossesDefeated||0),perfect:legacy.perfect+(campaign.perfectDefenses||0),bestAccuracy:Math.max(legacy.bestAccuracy||0,campaign.bestAccuracy||0),gold:legacy.gold+gold,campaigns:legacy.campaigns+1}))}
  function renderHall(){const campaign=loadCampaign(),legacy=loadLegacy(),allEntries=loadHall(),filter=ui.rankingMode?.value||'all',entries=allEntries.filter(entry=>filter==='all'||entry.mode===filter).sort((a,b)=>b.score-a.score||b.accuracy-a.accuracy).slice(0,15),difficulty={easy:'Fácil',medium:'Médio',hard:'Difícil'},modeNames={campaign:'Campanha',survival:'Sobrevivência',timed:'Tempo'},currentGold=Object.values(campaign.medals||{}).filter(value=>value==='gold').length,gold=legacy.gold+currentGold,finished=legacy.finished||(campaign.currentStage>=100&&campaign.score>0),bosses=legacy.bosses+(campaign.bossesDefeated||0),perfect=legacy.perfect+(campaign.perfectDefenses||0),bestAccuracy=Math.max(legacy.bestAccuracy||0,campaign.bestAccuracy||0,...allEntries.map(entry=>entry.accuracy||0)),competitive=allEntries.filter(entry=>entry.mode!=='training'),totalDestroyed=competitive.reduce((sum,entry)=>sum+(Number(entry.destroyed)||0),0),totalSeconds=competitive.reduce((sum,entry)=>sum+(Number(entry.time)||0),0),bestSurvival=Math.max(0,...allEntries.filter(entry=>entry.mode==='survival').map(entry=>entry.wave||0));ui.restartCampaign.hidden=!finished;ui.careerSummary.textContent=`${competitive.length} resultados · ${totalDestroyed.toLocaleString('pt-BR')} pedras destruídas · ${Math.floor(totalSeconds/60)} min registrados · melhor Sobrevivência: onda ${bestSurvival}.`;const awards=[['🌌','Conquistador','Chegou à fase 100',finished],['👑','Caçador de chefes','Venceu 5 chefes',bosses>=5],['🎯','Olho de águia','Precisão de 85%',bestAccuracy>=85],['🛡️','Defesa lendária','10 fases perfeitas',perfect>=10],['🥇','Colecionador','10 medalhas de ouro',gold>=10]];ui.awards.innerHTML=awards.map(([icon,title,description,unlocked])=>`<article class="award${unlocked?'':' locked'}"><i>${icon}</i><b>${title}</b><small>${unlocked?description:'Bloqueado · '+description}</small></article>`).join('');ui.rankingBody.innerHTML=entries.length?entries.map((entry,index)=>`<tr><td>${index+1}</td><td>${escapeText(entry.name)}</td><td>${modeNames[entry.mode]||entry.mode}</td><td>${Number(entry.score).toLocaleString('pt-BR')}</td><td>${escapeText(entry.screen)}</td><td>${entry.mode==='timed'?'—':entry.wave}</td><td>${entry.accuracy}%</td><td>${entry.destroyed}</td><td>x${entry.combo}</td><td>${difficulty[entry.difficulty]||entry.difficulty}</td><td>${String(entry.date).startsWith('1970-')?'Legado':new Date(entry.date).toLocaleDateString('pt-BR')}</td></tr>`).join(''):'<tr><td colspan="11">Nenhum resultado neste modo.</td></tr>'}
  function escapeText(value){const span=document.createElement('span');span.textContent=String(value);return span.innerHTML}
  function registerRanking(automatic=false){const name=(ui.rankingName.value||'Defensor').trim().slice(0,20)||'Defensor',campaign=loadCampaign();localStorage.setItem('qqfPlayerName',name);if(campaign.currentStage<100||!campaign.score){ui.rankingMessage.textContent='Chegue à fase 100 para registrar uma campanha completa.';return}const hall=loadHall(),performance={mode:'campaign',score:Number(campaign.score)||0,difficulty:campaign.difficulty||'easy',accuracy:Math.round(campaign.bestAccuracy||0),bosses:campaign.bossesDefeated||0,perfect:campaign.perfectDefenses||0,destroyed:campaign.totalDestroyed||0,combo:campaign.bestCombo||1,wave:100,time:campaign.totalTime||0,screen:'100 fases'};if(!campaign.runId){const migrated=hall.find(item=>item.runId?.startsWith('legacy-')&&hallPerformanceKey(item)===hallPerformanceKey(performance));campaign.runId=migrated?.runId||makeRunId();localStorage.setItem(SAVE_KEY,JSON.stringify(campaign))}const entry={runId:campaign.runId,name,...performance,date:new Date().toISOString()},existing=hall.findIndex(item=>item.runId===entry.runId);if(existing<0){hall.push(entry);ui.rankingMessage.textContent=automatic?'Campanha registrada automaticamente no Hall!':'Conquista registrada no Hall dos Defensores!'}else{const previousName=hall[existing].name;hall[existing]={...hall[existing],...entry};ui.rankingMessage.textContent=previousName===name?'Resultado atualizado sem criar duplicata.':'Nome atualizado no resultado existente.'}hall.sort((a,b)=>b.score-a.score||b.accuracy-a.accuracy);localStorage.setItem(HALL_KEY,JSON.stringify(hall.slice(0,100)));renderHall()}
  function registerArcadeResult(automatic=true){if(!['survival','timed'].includes(state.playMode))return;const name=(ui.rankingName.value||'Defensor').trim().slice(0,20)||'Defensor',hall=loadHall(),accuracy=Math.round((state.stageShots?state.stageHits/state.stageShots:0)*100),scene=sceneFor(state.stage);state.resultRunId??=makeRunId();const entry={runId:state.resultRunId,name,mode:state.playMode,score:Math.round(state.score),difficulty:ui.difficulty.value,accuracy,bosses:0,perfect:0,destroyed:state.totalDestroyed||state.stageDestroyed||0,combo:state.maxCombo||1,wave:state.playMode==='survival'?state.wave:0,time:Math.round(state.totalTime),screen:scene.family,date:new Date().toISOString()},existing=hall.findIndex(item=>item.runId===entry.runId);if(existing<0)hall.push(entry);else hall[existing]={...hall[existing],...entry};hall.sort((a,b)=>b.score-a.score||b.accuracy-a.accuracy);localStorage.setItem(HALL_KEY,JSON.stringify(hall.slice(0,100)));localStorage.setItem('qqfPlayerName',name);ui.rankingMessage.textContent=automatic?`${state.playMode==='survival'?'Sobrevivência':'Partida por tempo'} registrada automaticamente.`:'Resultado atualizado no Hall.';renderHall()}
  function startNewCampaign(){const campaign=loadCampaign();if(campaign.currentStage<100||!campaign.score){ui.rankingMessage.textContent='Conclua a campanha atual antes de iniciar outra.';return}if(!confirm('Iniciar uma nova campanha na fase 1? O resultado atual ficará preservado no Hall.'))return;registerRanking(true);archiveCampaign();const difficulty=ui.difficulty.value,reset={version:1,runId:makeRunId(),currentStage:1,unlockedStage:100,score:0,difficulty,totalDestroyed:0,destroyedByType:{},bossesDefeated:0,perfectDefenses:0,bestAccuracy:0,bestCombo:1,medals:{}};localStorage.setItem(SAVE_KEY,JSON.stringify(reset));localStorage.setItem('qqfUnlockedStage','100');state=fresh(1);ui.difficulty.value=difficulty;beginStage(1,0);renderHall();ui.restartCampaign.hidden=true;scrollTo({top:0,behavior:'smooth'});ui.announcement.textContent='NOVA CAMPANHA · fase 1 iniciada. Suas conquistas continuam no Hall.'}
  const stageDuration=stage=>Math.min(60,25+Math.floor((stage-1)/10)*4);
  function fresh(stage=savedStage()){return{running:false,over:false,transitioning:false,overtime:false,playMode:'campaign',wave:1,bossDefeated:false,bossesDefeated:0,stageStartBosses:0,score:0,stageStartScore:0,hits:0,shots:0,stageHits:0,stageShots:0,stageDestroyed:0,totalDestroyed:0,destroyedByType:{},stageStartDestroyedByType:{},stageStartDestroyed:0,perfectDefenses:0,stageStartPerfect:0,bestAccuracy:0,combo:1,maxCombo:1,stageMaxCombo:1,health:3,stage,stageTime:0,totalTime:0,damageTaken:0,spawnClock:0,lastPowerDrop:-20,activeTargetOrder:null,effects:{doubleUntil:0,rapidUntil:0,pierceUntil:0,shield:0},cannon:{x:68,y:250,r:23},bullets:[],rocks:[],powerups:[],sparks:[],sequence:0,shake:0,transitionToken:0}}
  const initialCampaign=loadCampaign();state=fresh(initialCampaign.currentStage);state.score=initialCampaign.score||0;state.stageStartScore=state.score;state.totalTime=initialCampaign.totalTime||0;state.totalDestroyed=initialCampaign.totalDestroyed||0;state.destroyedByType={...(initialCampaign.destroyedByType||{})};state.stageStartDestroyedByType={...state.destroyedByType};state.stageStartDestroyed=state.totalDestroyed;state.bossesDefeated=initialCampaign.bossesDefeated||0;state.stageStartBosses=state.bossesDefeated;state.perfectDefenses=initialCampaign.perfectDefenses||0;state.stageStartPerfect=state.perfectDefenses;state.bestAccuracy=initialCampaign.bestAccuracy||0;state.maxCombo=initialCampaign.bestCombo||1;ui.difficulty.value=initialCampaign.difficulty||'easy';
  function tone(freq=.1,duration=.05,type='square',volume=.025){if(!soundOn)return;audio??=new AudioContext();const osc=audio.createOscillator(),gain=audio.createGain();osc.type=type;osc.frequency.value=freq;gain.gain.setValueAtTime(volume,audio.currentTime);gain.gain.exponentialRampToValueAtTime(.001,audio.currentTime+duration);osc.connect(gain).connect(audio.destination);osc.start();osc.stop(audio.currentTime+duration)}
  function phaseData(){const progress=state.stageTime/stageDuration(state.stage);if(progress<.36)return{name:'Acelerando',factor:.68+progress/.36*.62,meter:progress/.36*.78};if(progress<.62)return{name:'PERIGO MÁXIMO',factor:1.3,meter:1};if(progress<.86){const part=(progress-.62)/.24;return{name:'Desacelerando',factor:1.3-part*.68,meter:1-part*.55}}return{name:'Respiro',factor:.62,meter:.25}}
  function stageRules(){const sector=sceneFor(state.stage).sector;return{hp:sector===1||sector===9?1:0,spawn:sector===2||sector===9?.86:1,speed:sector===4||sector===9?1.12:1,cannons:sector===7?1:0,curve:sector===5,space:sector===8,haze:sector===6}}
  function cannonCount(){const p=profiles[ui.difficulty.value],rules=stageRules();return Math.min(6,p.cannons+rules.cannons)}
  function bossBalance(){const tier=state.stage/10,base={easy:18+tier*4,medium:30+tier*6,hard:44+tier*8}[ui.difficulty.value],reinforcement={easy:1.55,medium:1.45,hard:1.35}[ui.difficulty.value],raw=Math.ceil(base*reinforcement),conservativeCapacity=Math.floor(stageDuration(state.stage)*6.25*.5);return{hp:Math.min(raw,Math.floor(conservativeCapacity*.86)),capacity:conservativeCapacity}}
  function spawnBoss(){const tier=state.stage/10,balance=bossBalance(),radius=44+tier*1.5,openingFire={easy:2.15,medium:1.55,hard:.95}[ui.difficulty.value];state.rocks.push({x:canvas.width-95,y:canvas.height/2,baseY:canvas.height/2,r:radius,hp:balance.hp,maxHp:balance.hp,order:++state.sequence,speed:7+tier*1.1,drift:random(0,Math.PI*2),type:'boss',bossTier:tier,lastHit:state.totalTime,regenClock:0,overtimeClock:0,fireClock:openingFire});state.bossDefeated=false;ui.announcement.textContent=`CHEFE: ${bossNames[tier-1]} · destrua-o e intercepte seus disparos!`;tone(72,.45,'sawtooth',.08)}
  function spawnBossAttack(boss){const difficulty=ui.difficulty.value,speed={easy:125,medium:150,hard:175}[difficulty],hp={easy:1,medium:1,hard:2}[difficulty],travel=Math.max(1.5,(boss.x-100)/speed),r=13+boss.bossTier*.25;state.rocks.push({x:boss.x-boss.r*.7,y:boss.y,baseY:boss.y,r,hp,maxHp:hp,order:10000+state.totalTime,speed,vy:(state.cannon.y-boss.y)/travel+random(-28,28),type:'bossShot',lastHit:state.totalTime});burst(boss.x-boss.r,boss.y,'#ff9b42',7);tone(145,.1,'sawtooth',.035)}
  const rockInfo={common:{name:'Pedra comum',color:'#6f6a5c',symbol:'●'},fast:{name:'Pedra veloz',color:'#d89b2b',symbol:'»'},armored:{name:'Pedra blindada',color:'#536d7d',symbol:'◆'},fragmenter:{name:'Pedra fragmentadora',color:'#94516b',symbol:'✕'},regenerator:{name:'Pedra regeneradora',color:'#4f8b5e',symbol:'+'},fragment:{name:'Fragmento',color:'#b86988',symbol:'·'},boss:{name:'Chefe',color:'#b5342c',symbol:'♛'},bossShot:{name:'Disparo do chefe',color:'#e86f32',symbol:'!'}};
  function chooseRockType(){const pool=['common','common','common'];if(state.stage>=11)pool.push('fast');if(state.stage>=21)pool.push('armored');if(state.stage>=31)pool.push('fragmenter');if(state.stage>=41)pool.push('regenerator');return pool[Math.floor(Math.random()*pool.length)]}
  function introduceRock(type){if(type==='common'||localStorage.getItem(`qqfSeenRock:${type}`))return;localStorage.setItem(`qqfSeenRock:${type}`,'1');ui.announcement.textContent=`NOVA AMEAÇA: ${rockInfo[type].name}! Observe sua forma e comportamento.`}
  function spawnRock(){const p=profiles[ui.difficulty.value],rules=stageRules(),count=cannonCount(),lane=Math.floor(Math.random()*count),spacing=canvas.height/count,y=spacing*(lane+.5),type=chooseRockType();let hp=Math.floor(random(p.hp[0],p.hp[1]+1))+Math.floor((state.stage-1)/12)+rules.hp,speed=p.speed*random(.9,1.1),radius=18+Math.min(8,hp);if(type==='fast'){hp=Math.max(1,Math.ceil(hp*.62));speed*=1.48;radius*=.72}if(type==='armored'){hp=Math.ceil(hp*1.65);speed*=.7;radius*=1.22}if(type==='fragmenter')radius*=1.08;if(type==='regenerator'){hp=Math.ceil(hp*1.15);speed*=.9}const rock={x:canvas.width-57,y,baseY:y,r:radius,hp,maxHp:hp,order:++state.sequence,speed,drift:random(0,Math.PI*2),type,lastHit:state.totalTime,regenClock:0};state.rocks.push(rock);(state.enemyFlashes??=[])[lane]=.22;burst(canvas.width-72,y,'#ffc24d',5);introduceRock(type);tone(95,.08,'sawtooth',.018)}
  function fire(){if(!state.running)return;const accuracy=clamp(state.stageShots?state.stageHits/state.stageShots:1,0,1),r=5+accuracy*6,damage=accuracy>.82?2:1,pierce=state.totalTime<state.effects.pierceUntil?3:1,offsets=state.totalTime<state.effects.doubleUntil?[-9,9]:[0];offsets.forEach(offset=>state.bullets.push({x:state.cannon.x+25,y:state.cannon.y+offset,r,damage,pierce,ignoredOrders:[]}));state.shots+=offsets.length;state.stageShots+=offsets.length;fireClock=0;tone(260,.035,'square',.02);updateHud()}
  function burst(x,y,color,count=8){for(let i=0;i<count;i++)state.sparks.push({x,y,vx:random(-100,100),vy:random(-100,100),life:random(.25,.65),color})}
  function dropPower(rock){if(rock.type==='bossShot'||rock.type==='fragment'||state.totalTime-state.lastPowerDrop<6||state.powerups.length)return;const chance=rock.type==='common'?0.09:0.18;if(Math.random()>chance)return;let pool=['double','rapid','pierce','shield','bomb'];if(state.health<3)pool.push('heal','heal');if(state.rocks.filter(item=>item.type!=='boss').length<3)pool=pool.filter(type=>type!=='bomb');const type=pool[Math.floor(Math.random()*pool.length)];state.powerups.push({x:rock.x,y:rock.y,r:15,type,life:9,phase:random(0,Math.PI*2)});state.lastPowerDrop=state.totalTime;ui.announcement.textContent=`CÁPSULA ${powerInfo[type].name.toUpperCase()} · acerte-a para ativar!`}
  function activatePower(power){const info=powerInfo[power.type];if(info.duration)state.effects[`${power.type}Until`]=Math.max(state.effects[`${power.type}Until`]||0,state.totalTime)+info.duration;if(power.type==='shield')state.effects.shield=Math.min(2,state.effects.shield+1);if(power.type==='heal')state.health=Math.min(3,state.health+1);if(power.type==='bomb'){const victims=state.rocks.filter(rock=>rock.type!=='boss');victims.forEach(rock=>{state.score+=60;state.stageDestroyed++;state.totalDestroyed++;state.destroyedByType[rock.type]=(state.destroyedByType[rock.type]||0)+1;burst(rock.x,rock.y,'#ffb34f',12)});state.rocks=state.rocks.filter(rock=>rock.type==='boss');state.activeTargetOrder=null}burst(power.x,power.y,info.color,24);tone(920,.18,'triangle',.06);ui.announcement.textContent=`POWER-UP ATIVADO: ${info.name}!`;updatePowerHud()}
  function updatePowerHud(){const active=[];for(const type of ['double','rapid','pierce']){const remaining=Math.ceil((state.effects[`${type}Until`]||0)-state.totalTime);if(remaining>0)active.push(`${powerInfo[type].icon} ${powerInfo[type].name} ${remaining}s`)}if(state.effects.shield)active.push(`◆ Escudo x${state.effects.shield}`);ui.powerStatus.textContent=active.length?active.join(' · '):'Nenhum bônus ativo'}
  function destroyRock(index,rock){const multiplier=rock.type==='boss'?3:rock.type==='bossShot'?0.35:rock.type==='fast'?1.35:rock.type==='armored'?1.2:1;state.score+=Math.round(35*rock.maxHp*state.combo*multiplier);if(rock.type!=='bossShot'){state.combo=Math.min(9,state.combo+1);state.stageMaxCombo=Math.max(state.stageMaxCombo,state.combo);state.maxCombo=Math.max(state.maxCombo,state.combo)}state.stageDestroyed++;state.totalDestroyed++;state.destroyedByType[rock.type]=(state.destroyedByType[rock.type]||0)+1;burst(rock.x,rock.y,rockInfo[rock.type].color,rock.type==='boss'?45:rock.type==='armored'?25:18);state.rocks.splice(index,1);if(rock.type==='boss'){state.bossDefeated=true;state.bossesDefeated++;tone(110,.2,'sawtooth',.07);tone(780,.3,'square',.05);ui.announcement.textContent=`CHEFE DERROTADO! ${bossNames[rock.bossTier-1]}`;return}if(rock.type==='fragmenter'){const fragmentHp=Math.max(1,Math.ceil(rock.maxHp*.32));[-1,1].forEach((side,part)=>state.rocks.push({...rock,type:'fragment',isFragment:true,x:rock.x+part*7,y:clamp(rock.y+side*14,18,canvas.height-18),baseY:clamp(rock.baseY+side*14,18,canvas.height-18),r:Math.max(9,rock.r*.52),hp:fragmentHp,maxHp:fragmentHp,speed:rock.speed*1.2,order:rock.order+(part+1)*.1,lastHit:state.totalTime}));tone(310,.1,'sawtooth',.035)}tone(680,.11,'square',.04)}
  const destroyRockWithoutDrop=destroyRock;destroyRock=(index,rock)=>{dropPower(rock);return destroyRockWithoutDrop(index,rock)};
  function preserveRockOrder(){const ordered=state.rocks.filter(rock=>rock.type!=='bossShot').sort((a,b)=>a.order-b.order);if(!ordered.length){state.activeTargetOrder=null;return ordered}const target=ordered[0];if(state.activeTargetOrder!==target.order){state.activeTargetOrder=target.order;target.graceUntil=state.totalTime+.8;target.activatedAt=state.totalTime}for(let i=1;i<ordered.length;i++){const ahead=ordered[i-1],rock=ordered[i],minimumX=ahead.x+ahead.r+rock.r+10;if(rock.x<minimumX)rock.x=minimumX}return ordered}
  function finishArcade(message){state.running=false;state.over=true;fireHeld=false;registerArcadeResult(true);state.bullets=[];state.rocks=[];state.powerups=[];if(state.playMode==='survival')localStorage.removeItem(SURVIVAL_KEY);ui.gameMode.disabled=false;ui.difficulty.disabled=false;ui.arcadeScene.disabled=false;ui.start.disabled=false;ui.start.textContent='Jogar novamente';ui.pauseSurvival.textContent='Pausar e continuar depois';ui.announcement.textContent=`${message} · ${state.score.toLocaleString('pt-BR')} pontos!`;updatePowerHud()}
  function update(dt){if(!state.running)return;state.stageTime+=dt;state.totalTime+=dt;const phase=phaseData(),p=profiles[ui.difficulty.value],rules=stageRules(),bossStage=state.playMode==='campaign'&&isBossStage(state.stage);if(state.playMode==='timed'&&state.stageTime>=60){finishArcade('TEMPO ENCERRADO');return}if((state.playMode==='survival'||state.playMode==='training')&&state.stageTime>=25){state.stageTime=0;state.wave++;state.score+=250*state.wave;ui.announcement.textContent=`ONDA ${state.wave} · velocidade e resistência aumentaram!`}if(state.playMode==='campaign'&&state.stageTime>=stageDuration(state.stage)){if(bossStage&&!state.bossDefeated){if(!state.overtime){state.overtime=true;state.rocks=state.rocks.filter(rock=>rock.type==='boss');ui.announcement.textContent='TEMPO EXTRA · somente o chefe permanece. A armadura começará a enfraquecer.'}}else{completeStage();return}}state.cannon.y=clamp(state.cannon.y+moveDirection*250*dt,38,canvas.height-38);state.spawnClock+=dt*1000;const fieldCount=state.rocks.filter(rock=>rock.type!=='bossShot').length,fieldLimit={easy:5,medium:6,hard:7}[ui.difficulty.value],directorDelay=1+Math.max(0,fieldCount-(fieldLimit-2))*.38;if(!bossStage&&fieldCount<fieldLimit&&state.spawnClock>p.spawn*rules.spawn/phase.factor*directorDelay){state.spawnClock=0;spawnRock()}if(fireHeld){fireClock+=dt;const fireInterval=state.totalTime<state.effects.rapidUntil?0.075:0.13;if(fireClock>fireInterval)fire()}
    const marching=preserveRockOrder(),pace=new Map();marching.forEach((rock,index)=>{if(!index){const ramp=clamp((state.totalTime-(rock.graceUntil||0))/1.05,0,1);pace.set(rock,ramp);return}const ahead=marching[index-1],gap=rock.x-rock.r-(ahead.x+ahead.r);pace.set(rock,clamp((gap-10)/115,.08,1))});state.bullets.forEach(b=>b.x+=640*(rules.space?.9:1)*dt);state.rocks.forEach(r=>{if(r.type==='boss'){r.x-=r.speed*dt;r.y=clamp(r.baseY+Math.sin(state.totalTime*(.7+r.bossTier*.04)+r.drift)*(48+r.bossTier*4),r.r+8,canvas.height-r.r-8);r.fireClock+=dt;const interval={easy:3.4,medium:2.7,hard:2.2}[ui.difficulty.value];if(!state.overtime&&r.fireClock>=interval){r.fireClock=0;spawnBossAttack(r)}if(state.overtime){r.overtimeClock+=dt;if(r.overtimeClock>15){r.erosionClock=(r.erosionClock||0)+dt;if(r.erosionClock>=1){r.hp=Math.max(1,r.hp-1);r.erosionClock=0;burst(r.x,r.y,'#ffc65a',3)}}}return}if(r.type==='bossShot'){r.x-=r.speed*dt;r.y=clamp(r.y+r.vy*dt,r.r,canvas.height-r.r);return}r.x-=r.speed*rules.speed*phase.factor*(1+(state.stage-1)*.012)*(pace.get(r)??1)*dt;if(rules.curve)r.y=clamp(r.baseY+Math.sin(state.totalTime*2+r.drift)*32,25,canvas.height-25);if(rules.space)r.y=clamp(r.baseY+Math.sin(state.totalTime*.9+r.drift)*18,25,canvas.height-25);if(r.type==='regenerator'&&r.hp<r.maxHp&&state.totalTime-r.lastHit>2.4){r.regenClock+=dt;if(r.regenClock>=1.15){r.hp++;r.regenClock=0;burst(r.x,r.y,'#76dd8d',4)}}});state.powerups.forEach(power=>{power.x-=42*dt;power.life-=dt;power.phase+=dt*4});state.powerups=state.powerups.filter(power=>power.life>0&&power.x>-30);preserveRockOrder();
    for(let bi=state.bullets.length-1;bi>=0;bi--){const bullet=state.bullets[bi];for(let pi=state.powerups.length-1;pi>=0;pi--){const power=state.powerups[pi];if(Math.hypot(bullet.x-power.x,bullet.y-power.y)<bullet.r+power.r){state.bullets.splice(bi,1);state.powerups.splice(pi,1);activatePower(power);break}}}
    for(let bi=state.bullets.length-1;bi>=0;bi--){const b=state.bullets[bi];if(b.x>canvas.width){state.bullets.splice(bi,1);state.combo=1;continue}for(let ri=0;ri<state.rocks.length;ri++){const r=state.rocks[ri];if(b.ignoredOrders.includes(r.order))continue;if(Math.hypot(b.x-r.x,b.y-r.y)<b.r+r.r){const targets=state.rocks.filter(rock=>rock.type!=='bossShot'),target=targets.reduce((a,v)=>v.order<a.order?v:a,targets[0]);if(r!==target&&r.type!=='bossShot'){b.ignoredOrders.push(r.order);burst(b.x,b.y,'#d8f0ff',3);continue}b.ignoredOrders.push(r.order);b.pierce--;if(b.pierce<=0)state.bullets.splice(bi,1);state.hits++;state.stageHits++;r.hp-=b.damage;r.lastHit=state.totalTime;r.regenClock=0;burst(b.x,b.y,'#ffd067',6);tone(430,.04,'triangle',.025);if(r.hp<=0)destroyRock(ri,r);if(b.pierce<=0)break}}
    }if(bossStage&&state.bossDefeated){completeStage();return}
    for(let i=state.rocks.length-1;i>=0;i--){const r=state.rocks[i];if(r.x-r.r<95){state.rocks.splice(i,1);if(state.playMode==='training'){burst(80,r.y,'#67c8e7',10);ui.announcement.textContent='TREINO · impacto registrado sem perda de energia.';continue}if(r.type!=='boss'&&state.effects.shield>0){state.effects.shield--;burst(80,r.y,'#67e79a',24);tone(560,.16,'triangle',.05);ui.announcement.textContent='ESCUDO ATIVADO · impacto bloqueado!';continue}state.health=r.type==='boss'?0:state.health-1;state.damageTaken++;state.combo=1;state.shake=.35;burst(80,r.y,'#ff4438',r.type==='boss'?45:20);tone(80,.25,'sawtooth',.07);ui.announcement.textContent=r.type==='boss'?'O CHEFE ROMPEU A DEFESA!':'IMPACTO! O minicanhão perdeu energia.';if(state.health<=0)gameOver()}}
    state.sparks.forEach(s=>{s.x+=s.vx*dt;s.y+=s.vy*dt;s.life-=dt});state.sparks=state.sparks.filter(s=>s.life>0);if(state.enemyFlashes)state.enemyFlashes=state.enemyFlashes.map(value=>Math.max(0,(value||0)-dt));updatePowerHud();state.shake=Math.max(0,state.shake-dt);updateHud(phase)}
  function updateHud(phase=phaseData()){const accuracy=state.stageShots?state.stageHits/state.stageShots:1,duration=stageDuration(state.stage),remaining=Math.max(0,Math.ceil(duration-state.stageTime)),scene=sceneFor(state.stage),boss=state.rocks.find(rock=>rock.type==='boss'),bossStage=isBossStage(state.stage);ui.score.textContent=state.score;ui.accuracy.textContent=Math.round(accuracy*100)+'%';ui.combo.textContent='x'+state.combo;ui.stage.textContent=`${state.stage}/100`;ui.stageTime.textContent=state.overtime?`EXTRA ${Math.floor(state.stageTime-duration)}s`:remaining+'s';ui.stageProgress.style.width=clamp(state.stageTime/duration*100,0,100)+'%';ui.stageProgress.style.background=scene.colors[4];ui.sectorName.textContent=`SETOR ${scene.sector+1} · ${scene.family} · ${scene.effect}`;ui.sceneName.textContent=scene.name;ui.arenaWrap.style.borderColor=scene.colors[3];ui.arenaWrap.style.outline=`2px solid ${scene.colors[4]}55`;ui.health.textContent='♥ '.repeat(state.health)+'♡ '.repeat(3-state.health);ui.phase.textContent=state.overtime?'TEMPO EXTRA':phase.name;ui.threat.style.width=(state.overtime?100:phase.meter*100)+'%';ui.bossHud.hidden=!bossStage;ui.bossName.textContent=bossNames[Math.max(0,state.stage/10-1)];ui.bossHealth.textContent=boss?`${Math.ceil(boss.hp)}/${boss.maxHp}`:state.bossDefeated?'DERROTADO':'AGUARDANDO';ui.bossFill.style.width=boss?clamp(boss.hp/boss.maxHp*100,0,100)+'%':'0%'}
  const updateCampaignHud=updateHud;updateHud=phase=>{updateCampaignHud(phase);if(state.playMode==='campaign')return;ui.bossHud.hidden=true;if(state.playMode==='timed'){ui.stage.textContent='60 SEG';ui.stageTime.textContent=Math.max(0,Math.ceil(60-state.stageTime))+'s';ui.stageProgress.style.width=clamp(state.stageTime/60*100,0,100)+'%'}else{ui.stage.textContent=`ONDA ${state.wave}`;ui.stageTime.textContent=Math.max(0,Math.ceil(25-state.stageTime))+'s';ui.stageProgress.style.width=clamp(state.stageTime/25*100,0,100)+'%'}if(state.playMode==='training')ui.health.textContent='∞'};
  function sceneNoise(seed){const value=Math.sin(seed*91.733+state.stage*17.17)*43758.5453;return value-Math.floor(value)}
  function drawSceneDecor(scene){const accent=scene.colors[4],dark=scene.colors[2],variant=scene.index;ctx.save();ctx.strokeStyle=accent;ctx.fillStyle=accent;ctx.lineWidth=2;ctx.globalAlpha=.13;
    if(variant===0){for(let x=150;x<900;x+=120){ctx.beginPath();ctx.arc(x,90+(x%240),22,0,Math.PI*2);ctx.stroke()}}
    if(variant===1){for(let x=-300;x<1100;x+=75){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x+260,canvas.height);ctx.stroke()}}
    if(variant===2){for(let x=150;x<900;x+=145){ctx.fillRect(x,28,24,canvas.height-56);ctx.clearRect(x+7,40,10,canvas.height-80)}}
    if(variant===3){for(let y=65;y<canvas.height;y+=120){ctx.beginPath();ctx.arc(canvas.width*.52,y,65,0,Math.PI*2);ctx.stroke();ctx.beginPath();ctx.arc(canvas.width*.52,y,35,0,Math.PI*2);ctx.stroke()}}
    if(variant===4){ctx.translate(canvas.width*.52,canvas.height*.5);ctx.rotate(Math.PI/4);ctx.fillRect(-105,-105,210,210);ctx.globalAlpha=.2;ctx.strokeStyle=dark;ctx.strokeRect(-75,-75,150,150)}
    if(variant===5){for(let x=120;x<900;x+=64)for(let y=35;y<490;y+=64)if((x+y)%128)ctx.strokeRect(x,y,38,38)}
    if(variant===6){for(let i=0;i<42;i++){const x=80+sceneNoise(i)*840,y=(sceneNoise(i+80)*canvas.height+state.totalTime*(12+scene.sector*2))%canvas.height,r=2+sceneNoise(i+160)*6;ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.fill()}}
    if(variant===7){const beam=ctx.createLinearGradient(100,0,850,canvas.height);beam.addColorStop(0,'transparent');beam.addColorStop(.45,accent);beam.addColorStop(.55,accent);beam.addColorStop(1,'transparent');ctx.globalAlpha=.2+.06*Math.sin(state.totalTime);ctx.fillStyle=beam;ctx.fillRect(80,0,850,canvas.height)}
    if(variant===8){const pulse=62+Math.sin(state.totalTime*2)*8;ctx.globalAlpha=.18;ctx.beginPath();ctx.arc(canvas.width*.55,canvas.height*.5,pulse,0,Math.PI*2);ctx.fill();ctx.globalAlpha=.25;ctx.beginPath();ctx.arc(canvas.width*.55,canvas.height*.5,pulse+35,0,Math.PI*2);ctx.stroke()}
    if(variant===9){ctx.globalAlpha=.2;ctx.lineWidth=10;ctx.strokeRect(80,22,canvas.width-160,canvas.height-44);ctx.lineWidth=2;for(let x=145;x<900;x+=105){ctx.beginPath();ctx.moveTo(x,22);ctx.lineTo(x+35,52);ctx.lineTo(x+70,22);ctx.stroke();ctx.beginPath();ctx.moveTo(x,canvas.height-22);ctx.lineTo(x+35,canvas.height-52);ctx.lineTo(x+70,canvas.height-22);ctx.stroke()}}
    ctx.restore();
  }
  function drawEnemyCannon(x,y,scene){const accent=scene.colors[4],metal=scene.colors[3],core=scene.colors[2],kind=scene.sector%5;ctx.save();ctx.translate(x,y);ctx.fillStyle=metal;ctx.strokeStyle=accent;ctx.lineWidth=2;if(kind===0){ctx.fillRect(-2,-16,30,32);ctx.beginPath();ctx.arc(0,0,22,0,Math.PI*2);ctx.fill()}if(kind===1){ctx.beginPath();ctx.moveTo(-22,-20);ctx.lineTo(24,-13);ctx.lineTo(24,13);ctx.lineTo(-22,20);ctx.closePath();ctx.fill();ctx.stroke()}if(kind===2){ctx.fillRect(-20,-19,44,38);ctx.strokeRect(-14,-13,27,26)}if(kind===3){ctx.beginPath();for(let i=0;i<8;i++){const a=i*Math.PI/4,r=i%2?17:25;ctx.lineTo(Math.cos(a)*r,Math.sin(a)*r)}ctx.closePath();ctx.fill();ctx.stroke()}if(kind===4){ctx.beginPath();ctx.arc(0,0,23,0,Math.PI*2);ctx.fill();ctx.beginPath();ctx.arc(0,0,12,0,Math.PI*2);ctx.fillStyle=core;ctx.fill();ctx.stroke()}ctx.fillStyle=accent;ctx.fillRect(12,-4,20,8);ctx.restore()}
  function drawRock(rock,isTarget,label){const info=rockInfo[rock.type]||rockInfo.common;ctx.save();ctx.translate(rock.x,rock.y);ctx.fillStyle=rock.type==='boss'?'#8f2924':isTarget?'#773f30':info.color;ctx.strokeStyle=isTarget?'#ffcc4d':'#303435';ctx.lineWidth=isTarget?4:2;ctx.beginPath();if(rock.type==='boss'){for(let i=0;i<24;i++){const a=i*Math.PI/12,r=i%2?rock.r*.82:rock.r;ctx.lineTo(Math.cos(a)*r,Math.sin(a)*r)}ctx.closePath()}else if(rock.type==='fast'){ctx.moveTo(rock.r,0);ctx.lineTo(0,rock.r*.72);ctx.lineTo(-rock.r,0);ctx.lineTo(0,-rock.r*.72);ctx.closePath()}else if(rock.type==='armored'){for(let i=0;i<6;i++){const a=i*Math.PI/3;ctx.lineTo(Math.cos(a)*rock.r,Math.sin(a)*rock.r)}ctx.closePath()}else if(rock.type==='fragmenter'){for(let i=0;i<10;i++){const a=i*Math.PI/5,r=i%2?rock.r*.78:rock.r;ctx.lineTo(Math.cos(a)*r,Math.sin(a)*r)}ctx.closePath()}else{ctx.arc(0,0,rock.r,0,Math.PI*2)}ctx.fill();ctx.stroke();if(rock.type==='boss'){ctx.beginPath();ctx.arc(0,0,rock.r*.6,0,Math.PI*2);ctx.strokeStyle='#ffb23e';ctx.lineWidth=5;ctx.stroke();ctx.fillStyle='#ffd269';ctx.font=`bold ${Math.max(20,rock.r*.48)}px Arial`;ctx.textAlign='center';ctx.fillText('♛',0,8)}else if(rock.type==='regenerator'){ctx.strokeStyle='#8df0a1';ctx.lineWidth=3;ctx.beginPath();ctx.arc(0,0,rock.r*.68,0,Math.PI*2);ctx.stroke()}if(rock.type!=='boss'){ctx.fillStyle='#fff';ctx.font=`bold ${Math.max(9,Math.min(13,rock.r*.55))}px Arial`;ctx.textAlign='center';ctx.fillText(String(label),0,4);ctx.fillStyle='#fff9';ctx.font='bold 8px Arial';ctx.fillText(info.symbol,0,rock.r*.62)}ctx.fillStyle='#311';ctx.fillRect(-rock.r,-rock.r-9,rock.r*2,4);ctx.fillStyle=rock.type==='boss'?'#ffb23e':rock.type==='regenerator'?'#7eed91':'#6ed18e';ctx.fillRect(-rock.r,-rock.r-9,rock.r*2*(rock.hp/rock.maxHp),4);ctx.restore()}
  function draw(){ctx.save();if(state.shake)ctx.translate(random(-6,6),random(-4,4));const scene=sceneFor(state.stage),colors=scene.colors,gradient=ctx.createLinearGradient(0,0,0,canvas.height);gradient.addColorStop(0,colors[0]);gradient.addColorStop(1,colors[1]);ctx.fillStyle=gradient;ctx.fillRect(0,0,canvas.width,canvas.height);ctx.strokeStyle=colors[4]+'44';ctx.lineWidth=1;for(let y=50;y<canvas.height;y+=50){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(canvas.width,y);ctx.stroke()}
    drawSceneDecor(scene);
    if(stageRules().haze){ctx.save();ctx.globalAlpha=.08+.07*(.5+.5*Math.sin(state.totalTime*.7));ctx.fillStyle='#f8d78c';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.restore()}
    ctx.fillStyle=colors[2];ctx.fillRect(0,0,36,canvas.height);ctx.fillStyle=colors[3];ctx.fillRect(36,0,13,canvas.height);ctx.fillStyle=colors[2];ctx.fillRect(canvas.width-42,0,42,canvas.height);
    const count=cannonCount(),spacing=canvas.height/count;for(let i=0;i<count;i++){const y=spacing*(i+.5);drawEnemyCannon(canvas.width-65,y,scene);if(state.enemyFlashes?.[i]){ctx.save();ctx.globalAlpha=state.enemyFlashes[i]*4;ctx.fillStyle='#fff3a0';ctx.shadowBlur=28;ctx.shadowColor='#ff8a35';ctx.beginPath();ctx.arc(canvas.width-92,y,10+state.enemyFlashes[i]*35,0,Math.PI*2);ctx.fill();ctx.restore()}}
    ctx.fillStyle='#263d4b';ctx.fillRect(38,state.cannon.y-8,35,16);ctx.beginPath();ctx.arc(state.cannon.x,state.cannon.y,state.cannon.r,0,Math.PI*2);ctx.fillStyle='#df522f';ctx.fill();ctx.lineWidth=5;ctx.strokeStyle='#72271f';ctx.stroke();ctx.fillStyle='#ffe4a0';ctx.font='bold 11px Arial';ctx.textAlign='center';ctx.fillText('QQ',state.cannon.x,state.cannon.y+4);
    const ordered=state.rocks.filter(rock=>rock.type!=='bossShot').sort((a,b)=>a.order-b.order),ranks=new Map(ordered.map((rock,index)=>[rock,index+1])),target=ordered[0];state.rocks.forEach(rock=>{ctx.save();ctx.globalAlpha=.18;ctx.strokeStyle=(rockInfo[rock.type]||rockInfo.common).color;ctx.lineWidth=Math.max(3,rock.r*.35);ctx.beginPath();ctx.moveTo(rock.x+rock.r,rock.y);ctx.lineTo(rock.x+rock.r+Math.min(70,rock.speed*.35),rock.y);ctx.stroke();ctx.restore();drawRock(rock,rock===target,rock.type==='bossShot'?'!':ranks.get(rock))});if(target&&target.x-target.r<230){ctx.save();ctx.globalAlpha=.38+.25*Math.sin(state.totalTime*10);ctx.strokeStyle='#ff392f';ctx.lineWidth=6;ctx.strokeRect(49,4,175,canvas.height-8);ctx.fillStyle='#ff392f';ctx.font='bold 15px Arial';ctx.textAlign='left';ctx.fillText('⚠ PERIGO',62,24);ctx.restore()}
    state.powerups.forEach(power=>{const info=powerInfo[power.type],pulse=1+Math.sin(power.phase)*.12;ctx.save();ctx.translate(power.x,power.y);ctx.scale(pulse,pulse);ctx.shadowBlur=18;ctx.shadowColor=info.color;ctx.fillStyle='#102b38';ctx.strokeStyle=info.color;ctx.lineWidth=4;ctx.beginPath();ctx.arc(0,0,power.r,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.shadowBlur=0;ctx.fillStyle=info.color;ctx.font='bold 17px Arial';ctx.textAlign='center';ctx.fillText(info.icon,0,6);ctx.restore()});state.bullets.forEach(b=>{ctx.beginPath();ctx.arc(b.x,b.y,b.r,0,Math.PI*2);ctx.fillStyle=state.totalTime<state.effects.pierceUntil?'#d9a3ff':'#fff7cf';ctx.shadowBlur=10;ctx.shadowColor=state.totalTime<state.effects.pierceUntil?'#a94dff':'#ff7b3e';ctx.fill();ctx.shadowBlur=0});state.sparks.forEach(s=>{ctx.globalAlpha=clamp(s.life*2,0,1);ctx.fillStyle=s.color;ctx.fillRect(s.x,s.y,4,4)});ctx.globalAlpha=1;ctx.restore()}
  function loop(now){const dt=Math.min(.035,(now-last)/1000||0);last=now;update(dt);draw();raf=requestAnimationFrame(loop)}
  function medalRank(value){return{bronze:1,silver:2,gold:3}[value]||0}
  function beginStage(stage,checkpoint=state.score){state.running=true;state.over=false;state.transitioning=false;state.overtime=false;state.bossDefeated=false;state.stage=clamp(stage,1,100);state.score=checkpoint;state.stageStartScore=checkpoint;state.stageTime=0;state.stageHits=0;state.stageShots=0;state.stageDestroyed=0;state.damageTaken=0;state.health=3;state.combo=1;state.stageMaxCombo=1;state.maxCombo=Math.max(1,state.maxCombo);state.spawnClock=0;state.sequence=0;state.activeTargetOrder=null;state.effects={doubleUntil:0,rapidUntil:0,pierceUntil:0,shield:0};state.bullets=[];state.rocks=[];state.powerups=[];state.sparks=[];state.stageStartDestroyed=state.totalDestroyed;state.stageStartDestroyedByType={...state.destroyedByType};state.stageStartBosses=state.bossesDefeated;state.stageStartPerfect=state.perfectDefenses;fireHeld=false;result.panel.hidden=true;ui.shell.classList.remove('stage-clear','game-over');ui.difficulty.disabled=true;ui.arcadeScene.disabled=true;ui.start.disabled=false;ui.start.textContent=state.playMode==='campaign'?'Reiniciar fase':'Reiniciar modo';updatePowerHud();if(state.playMode==='campaign'&&isBossStage(state.stage))spawnBoss();else ui.announcement.textContent=`FASE ${state.stage} · destrua primeiro a pedra marcada com 1!`;updateHud()}
  function showStageResult(data){const scene=sceneFor(state.stage),finalStage=state.stage===100;result.sector.textContent=`FASE ${state.stage} · ${scene.name}`;result.title.textContent=finalStage?'Campanha concluída!':'Defesa concluída!';result.medal.textContent=data.medal==='gold'?'🥇':data.medal==='silver'?'🥈':'🥉';result.points.textContent='+'+data.stagePoints;result.accuracy.textContent=data.accuracy+'%';result.destroyed.textContent=state.stageDestroyed;result.combo.textContent='x'+state.stageMaxCombo;result.health.textContent=state.health;result.bonus.textContent='+'+data.bonus;result.message.textContent=data.perfect?'Defesa perfeita: nenhuma energia perdida!':`Você sobreviveu com ${state.health} de 3 energias.`;result.next.textContent=finalStage?'Ver Hall dos Defensores':'Próxima fase';result.newCampaign.hidden=!finalStage;result.pause.hidden=finalStage;result.retry.textContent=finalStage?'Repetir fase 100':'Repetir fase';result.panel.hidden=false}
  function completeStage(){if(state.transitioning)return;if(isBossStage(state.stage)&&!state.bossDefeated){state.overtime=true;state.stageTime=Math.max(state.stageTime,stageDuration(state.stage));state.rocks=state.rocks.filter(rock=>rock.type==='boss');state.powerups=[];fireHeld=false;ui.announcement.textContent='TEMPO EXTRA · o chefe ainda está vivo e precisa ser eliminado!';updatePowerHud();updateHud();return}state.running=false;state.transitioning=true;fireHeld=false;state.bullets=[];state.rocks=[];state.powerups=[];const perfect=state.damageTaken===0,accuracy=Math.min(100,Math.round((state.stageShots?state.stageHits/state.stageShots:1)*100)),bonus=perfect?500*state.stage:0,stagePoints=state.score-state.stageStartScore+bonus,medal=perfect&&accuracy>=85?'gold':accuracy>=60?'silver':'bronze';state.score+=bonus;if(perfect)state.perfectDefenses++;state.bestAccuracy=Math.max(state.bestAccuracy,accuracy);const old=loadCampaign(),oldMedal=old.medals?.[state.stage],medals={...(old.medals||{})};if(medalRank(medal)>medalRank(oldMedal))medals[state.stage]=medal;const next=Math.min(100,state.stage+1);saveCampaign({currentStage:next,unlockedStage:Math.max(old.unlockedStage,next),medals});if(state.stage===100)registerRanking(true);else renderHall();ui.shell.classList.add('stage-clear');ui.announcement.textContent=`FASE ${state.stage} CONCLUÍDA · desempenho registrado.`;ui.start.disabled=true;tone(740,.12,'square',.05);tone(980,.2,'triangle',.04);updateHud();showStageResult({perfect,accuracy,bonus,stagePoints,medal})}
  function restoreSurvival(){try{const saved=JSON.parse(localStorage.getItem(SURVIVAL_KEY)||'null');if(!saved?.state)return false;state={...fresh(saved.state.stage),...saved.state,running:true,over:false,playMode:'survival'};ui.difficulty.value=saved.difficulty||'easy';ui.arcadeScene.value=String(state.stage);ui.gameMode.value='survival';ui.gameMode.disabled=true;ui.difficulty.disabled=true;ui.arcadeScene.disabled=true;ui.start.textContent='Reiniciar sobrevivência';ui.pauseSurvival.textContent='Pausar e continuar depois';ui.announcement.textContent=`SOBREVIVÊNCIA RETOMADA · onda ${state.wave}.`;last=performance.now();updatePowerHud();updateHud();return true}catch{localStorage.removeItem(SURVIVAL_KEY);return false}}
  function start(){const mode=ui.gameMode.value;if(mode!=='campaign'){if(mode==='survival'&&restoreSurvival()){ui.start.blur();return}const chosenStage=clamp(Number(ui.arcadeScene.value)||1,1,100);state=fresh(chosenStage);state.playMode=mode;beginStage(chosenStage,0);ui.gameMode.disabled=true;ui.start.blur();ui.announcement.textContent=mode==='survival'?'SOBREVIVÊNCIA · resista ao maior número de ondas!':mode==='timed'?'PARTIDA POR TEMPO · faça o máximo de pontos em 60 segundos!':'TREINO LIVRE · pratique sem perder energia.';return}const campaign=loadCampaign(),stage=state.over?state.stage:campaign.currentStage,checkpoint=state.over?state.stageStartScore:campaign.score||0;if(state.over){state.totalDestroyed=state.stageStartDestroyed;state.destroyedByType={...state.stageStartDestroyedByType};state.bossesDefeated=state.stageStartBosses;state.perfectDefenses=state.stageStartPerfect}state.playMode='campaign';beginStage(stage,checkpoint);ui.gameMode.disabled=true;ui.start.blur()}
  function gameOver(){state.running=false;state.over=true;fireHeld=false;if(state.playMode==='campaign'){state.totalDestroyed=state.stageStartDestroyed;state.destroyedByType={...state.stageStartDestroyedByType};state.bossesDefeated=state.stageStartBosses;state.perfectDefenses=state.stageStartPerfect}if(state.playMode==='survival'){registerArcadeResult(true);localStorage.removeItem(SURVIVAL_KEY)}ui.shell.classList.add('game-over');ui.gameMode.disabled=false;ui.difficulty.disabled=false;ui.arcadeScene.disabled=false;ui.pauseSurvival.textContent='Pausar e continuar depois';ui.announcement.textContent=state.playMode==='survival'?`SOBREVIVÊNCIA ENCERRADA NA ONDA ${state.wave} · ${state.score.toLocaleString('pt-BR')} pontos.`:`DEFESA ROMPIDA NA FASE ${state.stage} · tente novamente a partir desta fase.`;ui.start.textContent=state.playMode==='campaign'?'Repetir fase':'Jogar novamente'}
  function pauseSurvival(){if(state.playMode!=='survival')return;if(!state.running){restoreSurvival();return}fireHeld=false;moveDirection=0;state.running=false;localStorage.setItem(SURVIVAL_KEY,JSON.stringify({version:1,difficulty:ui.difficulty.value,state}));ui.gameMode.disabled=false;ui.difficulty.disabled=false;ui.arcadeScene.disabled=false;ui.start.textContent='Continuar sobrevivência';ui.pauseSurvival.textContent='Continuar sobrevivência';ui.announcement.textContent=`SOBREVIVÊNCIA PAUSADA · onda ${state.wave} salva neste dispositivo.`;updateHud()}
  function stopSurvival(){const selectedMode=ui.gameMode.value;if(selectedMode==='training'){if(state.playMode!=='training'||!state.running)return;finishArcade('TREINO LIVRE ENCERRADO PELO JOGADOR');refreshModeControls();return}if(state.playMode!=='survival'&&!localStorage.getItem(SURVIVAL_KEY))return;localStorage.removeItem(SURVIVAL_KEY);finishArcade('SOBREVIVÊNCIA ENCERRADA PELO JOGADOR');refreshModeControls()}
  function renderTutorial(){const [icon,title,text]=tutorialSteps[tutorialIndex];tutorial.icon.textContent=icon;tutorial.title.textContent=title;tutorial.text.textContent=text;tutorial.step.textContent=`PASSO ${tutorialIndex+1} DE ${tutorialSteps.length}`;tutorial.progress.style.width=`${(tutorialIndex+1)/tutorialSteps.length*100}%`;tutorial.back.disabled=tutorialIndex===0;tutorial.next.textContent=tutorialIndex===tutorialSteps.length-1?'Concluir':'Próximo'}
  function openTutorial(){if(!tutorial.overlay.hidden)return;tutorialIndex=0;tutorialWasRunning=state.running;state.running=false;fireHeld=false;moveDirection=0;tutorial.overlay.hidden=false;renderTutorial();requestAnimationFrame(()=>tutorial.next.focus())}
  function closeTutorial(){tutorial.overlay.hidden=true;localStorage.setItem('qqfTutorialV1','1');if(tutorialWasRunning&&!state.over&&!state.transitioning)state.running=true;tutorialWasRunning=false;last=performance.now();tutorial.open.focus()}
  tutorial.open.onclick=openTutorial;
  tutorial.back.onclick=()=>{if(tutorialIndex>0){tutorialIndex--;renderTutorial()}};
  tutorial.next.onclick=()=>{if(tutorialIndex<tutorialSteps.length-1){tutorialIndex++;renderTutorial()}else closeTutorial()};
  tutorial.skip.onclick=closeTutorial;
  tutorial.overlay.addEventListener('click',e=>{if(e.target===tutorial.overlay)closeTutorial()});
  ui.gameMode.addEventListener('change',refreshModeControls);
  ui.arcadeScene.addEventListener('change',()=>{localStorage.setItem('qqfArcadeScene',ui.arcadeScene.value);if(!state.running){state.stage=clamp(Number(ui.arcadeScene.value)||1,1,100);updateHud();draw()}});
  ui.pauseSurvival.onclick=pauseSurvival;
  ui.stopSurvival.onclick=stopSurvival;
  ui.fire.addEventListener('pointerdown',e=>{e.preventDefault();fireHeld=true;fire()});ui.fire.addEventListener('pointerup',()=>fireHeld=false);ui.fire.addEventListener('pointercancel',()=>fireHeld=false);ui.start.onclick=e=>{e.currentTarget.blur();start()};ui.sound.onclick=e=>{e.currentTarget.blur();soundOn=!soundOn;ui.sound.setAttribute('aria-pressed',soundOn);ui.sound.textContent=soundOn?'🔊 Som':'🔇 Som'};ui.saveRanking.onclick=()=>state.over&&['survival','timed'].includes(state.playMode)?registerArcadeResult(false):registerRanking(false);ui.restartCampaign.onclick=startNewCampaign;ui.rankingMode.addEventListener('change',renderHall);ui.rankingName.addEventListener('change',()=>localStorage.setItem('qqfPlayerName',ui.rankingName.value.trim().slice(0,20)));
  addEventListener('keydown',e=>{if(!tutorial.overlay.hidden){if(e.code==='Escape')closeTutorial();if(e.code==='ArrowLeft')tutorial.back.click();if(e.code==='ArrowRight'||e.code==='Enter')tutorial.next.click();return}if(['ArrowUp','ArrowDown','Space'].includes(e.code))e.preventDefault();if(e.code==='ArrowUp')moveDirection=-1;if(e.code==='ArrowDown')moveDirection=1;if(e.code==='Space'&&!e.repeat){fireHeld=true;fire()}});addEventListener('keyup',e=>{if(!tutorial.overlay.hidden)return;if(['ArrowUp','ArrowDown','Space'].includes(e.code))e.preventDefault();if(['ArrowUp','ArrowDown'].includes(e.code))moveDirection=0;if(e.code==='Space')fireHeld=false});canvas.addEventListener('pointerdown',e=>{const rect=canvas.getBoundingClientRect();state.cannon.y=clamp((e.clientY-rect.top)*canvas.height/rect.height,38,canvas.height-38)});canvas.addEventListener('pointermove',e=>{if(e.buttons){const rect=canvas.getBoundingClientRect();state.cannon.y=clamp((e.clientY-rect.top)*canvas.height/rect.height,38,canvas.height-38)}});
  result.next.onclick=()=>{if(state.stage>=100){result.panel.hidden=true;state.transitioning=false;ui.shell.classList.remove('stage-clear');ui.difficulty.disabled=false;ui.start.disabled=false;ui.start.textContent='Jogar fase 100 novamente';ui.announcement.textContent='Campanha concluída! Seu desempenho foi salvo.';renderHall();document.querySelector('.hall').scrollIntoView({behavior:'smooth',block:'start'});return}beginStage(state.stage+1,state.score);saveCampaign({currentStage:state.stage,score:state.score})};
  result.newCampaign.onclick=startNewCampaign;
  result.retry.onclick=()=>{state.totalDestroyed=state.stageStartDestroyed;state.destroyedByType={...state.stageStartDestroyedByType};state.bossesDefeated=state.stageStartBosses;state.perfectDefenses=state.stageStartPerfect;beginStage(state.stage,state.stageStartScore)};
  result.pause.onclick=()=>{const next=Math.min(100,state.stage+1);state.stage=next;state.stageTime=0;state.stageStartScore=state.score;state.running=false;state.transitioning=false;result.panel.hidden=true;ui.shell.classList.remove('stage-clear');ui.difficulty.disabled=false;ui.start.disabled=false;ui.start.textContent='Continuar campanha';ui.announcement.textContent=`Campanha pausada · fase ${next} pronta para continuar.`;saveCampaign({currentStage:next,score:state.score});updateHud()};
  populateArcadeScenes();const storedArcadeStage=clamp(Number(localStorage.getItem('qqfArcadeScene'))||1,1,100),storedArcadeScreen=Math.floor((storedArcadeStage-1)/10)*10+1;ui.arcadeScene.value=String(storedArcadeScreen);localStorage.setItem('qqfArcadeScene',String(storedArcadeScreen));ui.rankingName.value=localStorage.getItem('qqfPlayerName')||'Defensor';renderHall();ui.restartCampaign.hidden=!(loadCampaign().currentStage>=100&&loadCampaign().score>0);refreshModeControls();updateHud();draw();raf=requestAnimationFrame(loop);if(!localStorage.getItem('qqfTutorialV1'))setTimeout(openTutorial,500);
})();
