(() => {
  const canvas=document.querySelector('#arena'),ctx=canvas.getContext('2d');
  const ui={shell:document.querySelector('.game-shell'),arenaWrap:document.querySelector('.arena-wrap'),score:document.querySelector('#score'),accuracy:document.querySelector('#accuracy'),combo:document.querySelector('#combo'),stage:document.querySelector('#stage'),stageTime:document.querySelector('#stageTime'),stageProgress:document.querySelector('#stageProgress'),sectorName:document.querySelector('#sectorName'),sceneName:document.querySelector('#sceneName'),health:document.querySelector('#health'),announcement:document.querySelector('#announcement'),phase:document.querySelector('#phase'),threat:document.querySelector('#threatFill'),start:document.querySelector('#start'),difficulty:document.querySelector('#difficulty'),fire:document.querySelector('#fire'),up:document.querySelector('#up'),down:document.querySelector('#down'),sound:document.querySelector('#sound')};
  const profiles={easy:{hp:[1,2],spawn:1900,speed:72,cannons:3},medium:{hp:[3,5],spawn:1450,speed:90,cannons:4},hard:{hp:[6,9],spawn:1100,speed:108,cannons:5}};
  const result={panel:document.querySelector('#stageResult'),sector:document.querySelector('#resultSector'),title:document.querySelector('#resultTitle'),medal:document.querySelector('#resultMedal'),points:document.querySelector('#resultPoints'),accuracy:document.querySelector('#resultAccuracy'),destroyed:document.querySelector('#resultDestroyed'),combo:document.querySelector('#resultCombo'),health:document.querySelector('#resultHealth'),bonus:document.querySelector('#resultBonus'),message:document.querySelector('#resultMessage'),next:document.querySelector('#nextStage'),retry:document.querySelector('#retryStage'),pause:document.querySelector('#pauseCampaign')};
  const sectors=[
    {family:'OFICINAS',colors:['#ead28e','#c99c56','#172b38','#805336','#ffb43d'],effect:'equilíbrio',names:['Bancada do Inventor','Oficina Abandonada','Depósito de Ferramentas','Carpintaria Solar','Sala das Engrenagens','Esteira de Montagem','Caldeira Antiga','Oficina Elétrica','Galpão Industrial','Oficina do Mestre']},
    {family:'FORTALEZAS',colors:['#b9b3a1','#777467','#222a31','#51483d','#e0a84d'],effect:'pedras reforçadas',names:['Portão de Pedra','Muralha do Norte','Pátio dos Escudos','Torre do Vigia','Corredor das Armaduras','Ponte Fortificada','Salão dos Estandartes','Masmorra Profunda','Bastião Real','Cidadela do Colosso']},
    {family:'INDÚSTRIAS',colors:['#b7a278','#75684d','#182b32','#4f4435','#ff8b32'],effect:'produção acelerada',names:['Linha de Produção','Prensa Hidráulica','Armazém de Aço','Tubulação Central','Usina de Vapor','Turbinas Gêmeas','Fundição Laranja','Forja Automatizada','Núcleo da Fundição','Máquina Suprema']},
    {family:'GELEIRAS',colors:['#d8f5f4','#7fbac7','#173344','#376878','#8ff5ff'],effect:'rastros congelados',names:['Lago Congelado','Gruta de Cristal','Passagem Boreal','Vale da Nevasca','Ponte de Gelo','Caverna Azul','Muralha Glacial','Aurora Silenciosa','Coração do Inverno','Trono de Gelo']},
    {family:'VULCÕES',colors:['#6f3a2d','#321d21','#20151a','#68261e','#ff612f'],effect:'pedras velozes',names:['Fenda Ardente','Galeria de Cinzas','Rio de Lava','Cratera Rubra','Câmara de Magma','Forja Vulcânica','Chuva de Brasas','Abismo Incandescente','Coração da Montanha','Titã do Vulcão']},
    {family:'FLORESTAS',colors:['#b9ce83','#62804e','#162d28','#3c5d3b','#e6d95c'],effect:'trajetórias sinuosas',names:['Clareira Antiga','Bosque dos Ecos','Trilha de Musgo','Jardim Selvagem','Árvores Gigantes','Ruínas Verdes','Pântano Luminoso','Templo das Raízes','Copa Encantada','Guardião da Floresta']},
    {family:'DESERTOS',colors:['#e9c477','#bd7541','#33241f','#77452c','#ffe16b'],effect:'tempestade de areia',names:['Dunas Douradas','Cânion Seco','Oásis Perdido','Templo de Areia','Mar de Dunas','Ruínas do Sol','Tempestade Âmbar','Pirâmide Interior','Olho do Deserto','Faraó de Pedra']},
    {family:'MEGACIDADES',colors:['#7586a8','#333c5c','#12182c','#293259','#ff4fd8'],effect:'canhão adicional',names:['Distrito Neon','Avenida Magnética','Metrô Suspenso','Fábrica de Androides','Torre Holográfica','Rede Central','Laboratório Quântico','Núcleo Cibernético','Cidade Vertical','Inteligência Suprema']},
    {family:'ESPAÇO',colors:['#20264d','#080d24','#070b18','#242c59','#68dfff'],effect:'gravidade instável',names:['Órbita Terrestre','Campo de Asteroides','Lua Sombria','Nebulosa Azul','Estação Perdida','Anéis de Saturno','Cometa Errante','Portal Estelar','Horizonte Cósmico','Nave-Mãe']},
    {family:'DIMENSÃO FINAL',colors:['#573068','#1b102d','#0c0916','#3a1d4d','#ffcf4b'],effect:'ameaças combinadas',names:['Portal do Caos','Espelho Partido','Corredor Impossível','Vazio Pulsante','Cidade Invertida','Relógio Cósmico','Labirinto Final','Olho da Tempestade','Última Muralha','Coração do Fogo Cruzado']}
  ];
  const sceneFor=stage=>{const sector=Math.min(9,Math.floor((stage-1)/10)),index=(stage-1)%10,base=sectors[sector];return{...base,sector,index,name:base.names[index]}};
  let state,raf,last=0,audio,soundOn=true,fireHeld=false,fireClock=0,moveDirection=0;
  const clamp=(n,min,max)=>Math.max(min,Math.min(max,n)),random=(min,max)=>min+Math.random()*(max-min);
  const SAVE_KEY='qqfCampaignV1';
  const savedStage=()=>clamp(Number(localStorage.getItem('qqfUnlockedStage'))||1,1,100);
  function loadCampaign(){try{const saved=JSON.parse(localStorage.getItem(SAVE_KEY)||'null');if(saved?.version===1)return{...saved,currentStage:clamp(Number(saved.currentStage)||savedStage(),1,100),unlockedStage:clamp(Number(saved.unlockedStage)||savedStage(),1,100)}}catch{}return{version:1,currentStage:savedStage(),unlockedStage:savedStage(),score:0,difficulty:'easy',totalDestroyed:0,perfectDefenses:0,bestAccuracy:0,bestCombo:1,medals:{}}}
  function saveCampaign(overrides={}){const old=loadCampaign(),data={...old,version:1,currentStage:state.stage,unlockedStage:Math.max(old.unlockedStage,state.stage),score:state.score,difficulty:ui.difficulty.value,totalDestroyed:state.totalDestroyed,perfectDefenses:state.perfectDefenses,bestAccuracy:Math.max(old.bestAccuracy||0,state.bestAccuracy||0),bestCombo:Math.max(old.bestCombo||1,state.maxCombo||1),medals:{...(old.medals||{})},...overrides};localStorage.setItem(SAVE_KEY,JSON.stringify(data));localStorage.setItem('qqfUnlockedStage',String(data.unlockedStage));return data}
  const stageDuration=stage=>Math.min(60,25+Math.floor((stage-1)/10)*4);
  function fresh(stage=savedStage()){return{running:false,over:false,transitioning:false,score:0,stageStartScore:0,hits:0,shots:0,stageHits:0,stageShots:0,stageDestroyed:0,totalDestroyed:0,stageStartDestroyed:0,perfectDefenses:0,stageStartPerfect:0,bestAccuracy:0,combo:1,maxCombo:1,stageMaxCombo:1,health:3,stage,stageTime:0,totalTime:0,damageTaken:0,spawnClock:0,cannon:{x:68,y:250,r:23},bullets:[],rocks:[],sparks:[],sequence:0,shake:0,transitionToken:0}}
  const initialCampaign=loadCampaign();state=fresh(initialCampaign.currentStage);state.score=initialCampaign.score||0;state.stageStartScore=state.score;state.totalDestroyed=initialCampaign.totalDestroyed||0;state.stageStartDestroyed=state.totalDestroyed;state.perfectDefenses=initialCampaign.perfectDefenses||0;state.stageStartPerfect=state.perfectDefenses;state.bestAccuracy=initialCampaign.bestAccuracy||0;state.maxCombo=initialCampaign.bestCombo||1;ui.difficulty.value=initialCampaign.difficulty||'easy';
  function tone(freq=.1,duration=.05,type='square',volume=.025){if(!soundOn)return;audio??=new AudioContext();const osc=audio.createOscillator(),gain=audio.createGain();osc.type=type;osc.frequency.value=freq;gain.gain.setValueAtTime(volume,audio.currentTime);gain.gain.exponentialRampToValueAtTime(.001,audio.currentTime+duration);osc.connect(gain).connect(audio.destination);osc.start();osc.stop(audio.currentTime+duration)}
  function phaseData(){const progress=state.stageTime/stageDuration(state.stage);if(progress<.36)return{name:'Acelerando',factor:.68+progress/.36*.62,meter:progress/.36*.78};if(progress<.62)return{name:'PERIGO MÁXIMO',factor:1.3,meter:1};if(progress<.86){const part=(progress-.62)/.24;return{name:'Desacelerando',factor:1.3-part*.68,meter:1-part*.55}}return{name:'Respiro',factor:.62,meter:.25}}
  function stageRules(){const sector=sceneFor(state.stage).sector;return{hp:sector===1||sector===9?1:0,spawn:sector===2||sector===9?.86:1,speed:sector===4||sector===9?1.12:1,cannons:sector===7?1:0,curve:sector===5,space:sector===8,haze:sector===6}}
  function cannonCount(){const p=profiles[ui.difficulty.value],rules=stageRules();return Math.min(6,p.cannons+rules.cannons)}
  function spawnRock(){const p=profiles[ui.difficulty.value],rules=stageRules(),count=cannonCount(),lane=Math.floor(Math.random()*count),spacing=canvas.height/count,y=spacing*(lane+.5),hp=Math.floor(random(p.hp[0],p.hp[1]+1))+Math.floor((state.stage-1)/12)+rules.hp;state.rocks.push({x:canvas.width-57,y,baseY:y,r:18+Math.min(8,hp),hp,maxHp:hp,order:++state.sequence,speed:p.speed*random(.9,1.1),drift:random(0,Math.PI*2)});tone(95,.08,'sawtooth',.018)}
  function fire(){if(!state.running)return;const accuracy=state.stageShots?state.stageHits/state.stageShots:1,r=5+accuracy*6,damage=accuracy>.88?2:1;state.bullets.push({x:state.cannon.x+25,y:state.cannon.y,r,damage});state.shots++;state.stageShots++;fireClock=0;tone(260,.035,'square',.02);updateHud()}
  function burst(x,y,color,count=8){for(let i=0;i<count;i++)state.sparks.push({x,y,vx:random(-100,100),vy:random(-100,100),life:random(.25,.65),color})}
  function update(dt){if(!state.running)return;state.stageTime+=dt;state.totalTime+=dt;const phase=phaseData(),p=profiles[ui.difficulty.value],rules=stageRules();if(state.stageTime>=stageDuration(state.stage)){completeStage();return}state.cannon.y=clamp(state.cannon.y+moveDirection*250*dt,38,canvas.height-38);state.spawnClock+=dt*1000;if(state.spawnClock>p.spawn*rules.spawn/phase.factor){state.spawnClock=0;spawnRock()}if(fireHeld){fireClock+=dt;if(fireClock>.16)fire()}
    state.bullets.forEach(b=>b.x+=520*(rules.space?.88:1)*dt);state.rocks.forEach(r=>{r.x-=r.speed*rules.speed*phase.factor*(1+(state.stage-1)*.012)*dt;if(rules.curve)r.y=clamp(r.baseY+Math.sin(state.totalTime*2+r.drift)*32,25,canvas.height-25);if(rules.space)r.y=clamp(r.baseY+Math.sin(state.totalTime*.9+r.drift)*18,25,canvas.height-25)});
    for(let bi=state.bullets.length-1;bi>=0;bi--){const b=state.bullets[bi];if(b.x>canvas.width){state.bullets.splice(bi,1);state.combo=1;continue}for(let ri=0;ri<state.rocks.length;ri++){const r=state.rocks[ri];if(Math.hypot(b.x-r.x,b.y-r.y)<b.r+r.r){state.bullets.splice(bi,1);const target=state.rocks.reduce((a,v)=>v.order<a.order?v:a,state.rocks[0]);if(r!==target){burst(b.x,b.y,'#9aa7aa',4);state.combo=1;break}state.hits++;state.stageHits++;r.hp-=b.damage;burst(b.x,b.y,'#ffd067',6);tone(430,.04,'triangle',.025);if(r.hp<=0){state.score+=Math.round(35*r.maxHp*state.combo);state.combo=Math.min(9,state.combo+1);state.stageMaxCombo=Math.max(state.stageMaxCombo,state.combo);state.maxCombo=Math.max(state.maxCombo,state.combo);state.stageDestroyed++;state.totalDestroyed++;burst(r.x,r.y,'#ff693b',18);state.rocks.splice(ri,1);tone(680,.11,'square',.04)}break}}
    }
    for(let i=state.rocks.length-1;i>=0;i--){const r=state.rocks[i];if(r.x-r.r<95){state.rocks.splice(i,1);state.health--;state.damageTaken++;state.combo=1;state.shake=.35;burst(80,r.y,'#ff4438',20);tone(80,.25,'sawtooth',.07);ui.announcement.textContent='IMPACTO! O minicanhão perdeu energia.';if(state.health<=0)gameOver()}}
    state.sparks.forEach(s=>{s.x+=s.vx*dt;s.y+=s.vy*dt;s.life-=dt});state.sparks=state.sparks.filter(s=>s.life>0);state.shake=Math.max(0,state.shake-dt);updateHud(phase)}
  function updateHud(phase=phaseData()){const accuracy=state.stageShots?state.stageHits/state.stageShots:1,duration=stageDuration(state.stage),remaining=Math.max(0,Math.ceil(duration-state.stageTime)),scene=sceneFor(state.stage);ui.score.textContent=state.score;ui.accuracy.textContent=Math.round(accuracy*100)+'%';ui.combo.textContent='x'+state.combo;ui.stage.textContent=`${state.stage}/100`;ui.stageTime.textContent=remaining+'s';ui.stageProgress.style.width=clamp(state.stageTime/duration*100,0,100)+'%';ui.stageProgress.style.background=scene.colors[4];ui.sectorName.textContent=`SETOR ${scene.sector+1} · ${scene.family} · ${scene.effect}`;ui.sceneName.textContent=scene.name;ui.arenaWrap.style.borderColor=scene.colors[3];ui.arenaWrap.style.outline=`2px solid ${scene.colors[4]}55`;ui.health.textContent='♥ '.repeat(state.health)+'♡ '.repeat(3-state.health);ui.phase.textContent=phase.name;ui.threat.style.width=phase.meter*100+'%'}
  function sceneNoise(seed){const value=Math.sin(seed*91.733+state.stage*17.17)*43758.5453;return value-Math.floor(value)}
  function drawSceneDecor(scene){const accent=scene.colors[4],dark=scene.colors[2],variant=scene.index;ctx.save();ctx.strokeStyle=accent;ctx.fillStyle=accent;ctx.lineWidth=2;ctx.globalAlpha=.13;
    if(variant===0){for(let x=150;x<900;x+=120){ctx.beginPath();ctx.arc(x,90+(x%240),22,0,Math.PI*2);ctx.stroke()}}
    if(variant===1){for(let x=-300;x<1100;x+=75){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x+260,canvas.height);ctx.stroke()}}
    if(variant===2){for(let x=150;x<900;x+=145){ctx.fillRect(x,28,24,canvas.height-56);ctx.clearRect(x+7,40,10,canvas.height-80)}}
    if(variant===3){for(let y=65;y<canvas.height;y+=120){ctx.beginPath();ctx.arc(canvas.width*.52,y,65,0,Math.PI*2);ctx.stroke();ctx.beginPath();ctx.arc(canvas.width*.52,y,35,0,Math.PI*2);ctx.stroke()}}
    if(variant===4){ctx.translate(canvas.width*.52,canvas.height*.5);ctx.rotate(Math.PI/4);ctx.fillRect(-105,-105,210,210);ctx.globalAlpha=.2;ctx.strokeStyle=dark;ctx.strokeRect(-75,-75,150,150)}
    if(variant===5){for(let x=120;x<900;x+=64)for(let y=35;y<490;y+=64)if((x+y)%128)ctx.strokeRect(x,y,38,38)}
    if(variant===6){for(let i=0;i<42;i++){const x=80+sceneNoise(i)*840,y=(sceneNoise(i+80)*canvas.height+state.totalTime*(12+scene.sector*2))%canvas.height,r=2+sceneNoise(i+160)*6;ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.fill()}}
    if(variant===7){const beam=ctx.createLinearGradient(100,0,850,canvas.height);beam.addColorStop(0,'transparent');beam.addColorStop(.45,accent);beam.addColorStop(.55,accent);beam.addColorStop(1,'transparent');ctx.globalAlpha=.2+.06*Math.sin(state.totalTime);ctx.fillStyle=beam;ctx.fillRect(80,0,850,canvas.height)}
    if(variant===8){const pulse=62+Math.sin(state.totalTime*2)*8;ctx.globalAlpha=.18;ctx.beginPath();ctx.arc(canvas.width*.55,canvas.height*.5,pulse,0,Math.PI*2);ctx.fill();ctx.globalAlpha=.25;ctx.beginPath();ctx.arc(canvas.width*.55,canvas.height*.5,pulse+35,0,Math.PI*2);ctx.stroke()}
    if(variant===9){ctx.globalAlpha=.2;ctx.lineWidth=10;ctx.strokeRect(80,22,canvas.width-160,canvas.height-44);ctx.lineWidth=2;for(let x=145;x<900;x+=105){ctx.beginPath();ctx.moveTo(x,22);ctx.lineTo(x+35,52);ctx.lineTo(x+70,22);ctx.stroke();ctx.beginPath();ctx.moveTo(x,canvas.height-22);ctx.lineTo(x+35,canvas.height-52);ctx.lineTo(x+70,canvas.height-22);ctx.stroke()}}
    ctx.restore();
  }
  function drawEnemyCannon(x,y,scene){const accent=scene.colors[4],metal=scene.colors[3],core=scene.colors[2],kind=scene.sector%5;ctx.save();ctx.translate(x,y);ctx.fillStyle=metal;ctx.strokeStyle=accent;ctx.lineWidth=2;if(kind===0){ctx.fillRect(-2,-16,30,32);ctx.beginPath();ctx.arc(0,0,22,0,Math.PI*2);ctx.fill()}if(kind===1){ctx.beginPath();ctx.moveTo(-22,-20);ctx.lineTo(24,-13);ctx.lineTo(24,13);ctx.lineTo(-22,20);ctx.closePath();ctx.fill();ctx.stroke()}if(kind===2){ctx.fillRect(-20,-19,44,38);ctx.strokeRect(-14,-13,27,26)}if(kind===3){ctx.beginPath();for(let i=0;i<8;i++){const a=i*Math.PI/4,r=i%2?17:25;ctx.lineTo(Math.cos(a)*r,Math.sin(a)*r)}ctx.closePath();ctx.fill();ctx.stroke()}if(kind===4){ctx.beginPath();ctx.arc(0,0,23,0,Math.PI*2);ctx.fill();ctx.beginPath();ctx.arc(0,0,12,0,Math.PI*2);ctx.fillStyle=core;ctx.fill();ctx.stroke()}ctx.fillStyle=accent;ctx.fillRect(12,-4,20,8);ctx.restore()}
  function draw(){ctx.save();if(state.shake)ctx.translate(random(-6,6),random(-4,4));const scene=sceneFor(state.stage),colors=scene.colors,gradient=ctx.createLinearGradient(0,0,0,canvas.height);gradient.addColorStop(0,colors[0]);gradient.addColorStop(1,colors[1]);ctx.fillStyle=gradient;ctx.fillRect(0,0,canvas.width,canvas.height);ctx.strokeStyle=colors[4]+'44';ctx.lineWidth=1;for(let y=50;y<canvas.height;y+=50){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(canvas.width,y);ctx.stroke()}
    drawSceneDecor(scene);
    if(stageRules().haze){ctx.save();ctx.globalAlpha=.08+.07*(.5+.5*Math.sin(state.totalTime*.7));ctx.fillStyle='#f8d78c';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.restore()}
    ctx.fillStyle=colors[2];ctx.fillRect(0,0,36,canvas.height);ctx.fillStyle=colors[3];ctx.fillRect(36,0,13,canvas.height);ctx.fillStyle=colors[2];ctx.fillRect(canvas.width-42,0,42,canvas.height);
    const count=cannonCount(),spacing=canvas.height/count;for(let i=0;i<count;i++)drawEnemyCannon(canvas.width-65,spacing*(i+.5),scene);
    ctx.fillStyle='#263d4b';ctx.fillRect(38,state.cannon.y-8,35,16);ctx.beginPath();ctx.arc(state.cannon.x,state.cannon.y,state.cannon.r,0,Math.PI*2);ctx.fillStyle='#df522f';ctx.fill();ctx.lineWidth=5;ctx.strokeStyle='#72271f';ctx.stroke();ctx.fillStyle='#ffe4a0';ctx.font='bold 11px Arial';ctx.textAlign='center';ctx.fillText('QQ',state.cannon.x,state.cannon.y+4);
    const target=state.rocks.length&&state.rocks.reduce((a,v)=>v.order<a.order?v:a,state.rocks[0]);state.rocks.forEach(r=>{ctx.beginPath();ctx.arc(r.x,r.y,r.r,0,Math.PI*2);ctx.fillStyle=r===target?'#773f30':'#6f6a5c';ctx.fill();ctx.strokeStyle=r===target?'#ffcc4d':'#3b3b36';ctx.lineWidth=r===target?4:2;ctx.stroke();ctx.fillStyle='#fff';ctx.font='bold 12px Arial';ctx.fillText(r===target?'1':String(r.order-target.order+1),r.x,r.y+4);ctx.fillStyle='#311';ctx.fillRect(r.x-r.r,r.y-r.r-9,r.r*2,4);ctx.fillStyle='#6ed18e';ctx.fillRect(r.x-r.r,r.y-r.r-9,r.r*2*(r.hp/r.maxHp),4)});
    state.bullets.forEach(b=>{ctx.beginPath();ctx.arc(b.x,b.y,b.r,0,Math.PI*2);ctx.fillStyle='#fff7cf';ctx.shadowBlur=10;ctx.shadowColor='#ff7b3e';ctx.fill();ctx.shadowBlur=0});state.sparks.forEach(s=>{ctx.globalAlpha=clamp(s.life*2,0,1);ctx.fillStyle=s.color;ctx.fillRect(s.x,s.y,4,4)});ctx.globalAlpha=1;ctx.restore()}
  function loop(now){const dt=Math.min(.035,(now-last)/1000||0);last=now;update(dt);draw();raf=requestAnimationFrame(loop)}
  function medalRank(value){return{bronze:1,silver:2,gold:3}[value]||0}
  function beginStage(stage,checkpoint=state.score){state.running=true;state.over=false;state.transitioning=false;state.stage=clamp(stage,1,100);state.score=checkpoint;state.stageStartScore=checkpoint;state.stageTime=0;state.stageHits=0;state.stageShots=0;state.stageDestroyed=0;state.damageTaken=0;state.health=3;state.combo=1;state.stageMaxCombo=1;state.maxCombo=Math.max(1,state.maxCombo);state.spawnClock=0;state.sequence=0;state.bullets=[];state.rocks=[];state.sparks=[];state.stageStartDestroyed=state.totalDestroyed;state.stageStartPerfect=state.perfectDefenses;fireHeld=false;result.panel.hidden=true;ui.shell.classList.remove('stage-clear','game-over');ui.difficulty.disabled=true;ui.start.disabled=false;ui.start.textContent='Reiniciar fase';ui.announcement.textContent=`FASE ${state.stage} · destrua primeiro a pedra marcada com 1!`;updateHud()}
  function showStageResult(data){const scene=sceneFor(state.stage);result.sector.textContent=`FASE ${state.stage} · ${scene.name}`;result.title.textContent=state.stage===100?'Campanha concluída!':'Defesa concluída!';result.medal.textContent=data.medal==='gold'?'🥇':data.medal==='silver'?'🥈':'🥉';result.points.textContent='+'+data.stagePoints;result.accuracy.textContent=data.accuracy+'%';result.destroyed.textContent=state.stageDestroyed;result.combo.textContent='x'+state.stageMaxCombo;result.health.textContent=state.health;result.bonus.textContent='+'+data.bonus;result.message.textContent=data.perfect?'Defesa perfeita: nenhuma energia perdida!':`Você sobreviveu com ${state.health} de 3 energias.`;result.next.textContent=state.stage===100?'Encerrar campanha':'Próxima fase';result.panel.hidden=false}
  function completeStage(){if(state.transitioning)return;state.running=false;state.transitioning=true;fireHeld=false;state.bullets=[];state.rocks=[];const perfect=state.damageTaken===0,accuracy=Math.round((state.stageShots?state.stageHits/state.stageShots:1)*100),bonus=perfect?500*state.stage:0,stagePoints=state.score-state.stageStartScore+bonus,medal=perfect&&accuracy>=85?'gold':accuracy>=60?'silver':'bronze';state.score+=bonus;if(perfect)state.perfectDefenses++;state.bestAccuracy=Math.max(state.bestAccuracy,accuracy);const old=loadCampaign(),oldMedal=old.medals?.[state.stage],medals={...(old.medals||{})};if(medalRank(medal)>medalRank(oldMedal))medals[state.stage]=medal;const next=Math.min(100,state.stage+1);saveCampaign({currentStage:next,unlockedStage:Math.max(old.unlockedStage,next),medals});ui.shell.classList.add('stage-clear');ui.announcement.textContent=`FASE ${state.stage} CONCLUÍDA · desempenho registrado.`;ui.start.disabled=true;tone(740,.12,'square',.05);tone(980,.2,'triangle',.04);updateHud();showStageResult({perfect,accuracy,bonus,stagePoints,medal})}
  function start(){const campaign=loadCampaign(),stage=state.over?state.stage:campaign.currentStage,checkpoint=state.over?state.stageStartScore:campaign.score||0;if(state.over){state.totalDestroyed=state.stageStartDestroyed;state.perfectDefenses=state.stageStartPerfect}beginStage(stage,checkpoint);ui.start.blur()}
  function gameOver(){state.running=false;state.over=true;fireHeld=false;state.totalDestroyed=state.stageStartDestroyed;state.perfectDefenses=state.stageStartPerfect;ui.shell.classList.add('game-over');ui.difficulty.disabled=false;ui.announcement.textContent=`DEFESA ROMPIDA NA FASE ${state.stage} · tente novamente a partir desta fase.`;ui.start.textContent='Repetir fase'}
  const hold=(element,direction)=>{element.addEventListener('pointerdown',e=>{e.preventDefault();moveDirection=direction;element.setPointerCapture?.(e.pointerId)});element.addEventListener('pointerup',()=>moveDirection=0);element.addEventListener('pointercancel',()=>moveDirection=0)};hold(ui.up,-1);hold(ui.down,1);
  ui.fire.addEventListener('pointerdown',e=>{e.preventDefault();fireHeld=true;fire()});ui.fire.addEventListener('pointerup',()=>fireHeld=false);ui.fire.addEventListener('pointercancel',()=>fireHeld=false);ui.start.onclick=e=>{e.currentTarget.blur();start()};ui.sound.onclick=e=>{e.currentTarget.blur();soundOn=!soundOn;ui.sound.setAttribute('aria-pressed',soundOn);ui.sound.textContent=soundOn?'🔊 Som':'🔇 Som'};
  addEventListener('keydown',e=>{if(e.code==='ArrowUp')moveDirection=-1;if(e.code==='ArrowDown')moveDirection=1;if(e.code==='Space'){e.preventDefault();if(!e.repeat){fireHeld=true;fire()}}});addEventListener('keyup',e=>{if(['ArrowUp','ArrowDown'].includes(e.code))moveDirection=0;if(e.code==='Space'){e.preventDefault();fireHeld=false}});canvas.addEventListener('pointerdown',e=>{const rect=canvas.getBoundingClientRect();state.cannon.y=clamp((e.clientY-rect.top)*canvas.height/rect.height,38,canvas.height-38)});canvas.addEventListener('pointermove',e=>{if(e.buttons){const rect=canvas.getBoundingClientRect();state.cannon.y=clamp((e.clientY-rect.top)*canvas.height/rect.height,38,canvas.height-38)}});
  result.next.onclick=()=>{if(state.stage>=100){result.panel.hidden=true;state.transitioning=false;ui.shell.classList.remove('stage-clear');ui.difficulty.disabled=false;ui.start.disabled=false;ui.start.textContent='Jogar fase 100 novamente';ui.announcement.textContent='Campanha concluída! Seu desempenho foi salvo.';return}beginStage(state.stage+1,state.score);saveCampaign({currentStage:state.stage,score:state.score})};
  result.retry.onclick=()=>{state.totalDestroyed=state.stageStartDestroyed;state.perfectDefenses=state.stageStartPerfect;beginStage(state.stage,state.stageStartScore)};
  result.pause.onclick=()=>{const next=Math.min(100,state.stage+1);state.stage=next;state.stageTime=0;state.stageStartScore=state.score;state.running=false;state.transitioning=false;result.panel.hidden=true;ui.shell.classList.remove('stage-clear');ui.difficulty.disabled=false;ui.start.disabled=false;ui.start.textContent='Continuar campanha';ui.announcement.textContent=`Campanha pausada · fase ${next} pronta para continuar.`;saveCampaign({currentStage:next,score:state.score});updateHud()};
  updateHud();draw();raf=requestAnimationFrame(loop);
})();
