(() => {
  const mode=document.querySelector('#mode'),game=document.querySelector('.game'),precision=document.querySelector('#precision'),flick=document.querySelector('#flick');
  if(!mode||!game||!precision||!flick)return;
  const option=document.createElement('option');option.value='circuit';option.textContent='Circuito Queima-Queima';mode.insertBefore(option,mode.firstElementChild);
  const panel=document.createElement('section');panel.id='circuitPanel';panel.hidden=true;
  panel.innerHTML=`<style>
    #circuitPanel{margin:10px 0 14px;padding:12px;border:2px solid #d37b2f;border-radius:13px;background:linear-gradient(135deg,#fff0b8,#ffd989);color:#50321f;text-align:left}#circuitPanel[hidden]{display:none}#circuitPanel header{display:flex;align-items:center;justify-content:space-between;gap:10px}#circuitPanel small{font-weight:900;letter-spacing:.1em;color:#a74628}#circuitPanel h2{margin:3px 0 0;font:700 1.15rem Georgia}#circuitProgress{height:8px;margin:9px 0;overflow:hidden;border-radius:20px;background:#b98a55}#circuitProgress i{display:block;height:100%;background:linear-gradient(90deg,#e44e2d,#ffbd35);transition:width .25s}#circuitObjective{margin:5px 0;font-weight:800}#circuitStatus{margin:4px 0 0;font-size:.82rem}#circuitAction{padding:8px 11px;border:0;border-radius:8px;background:#273d4b;color:#fff;font-weight:800}#circuitAction[hidden]{display:none}#circuitPanel.success{border-color:#4d9c62;background:linear-gradient(135deg,#e8f5c9,#bce29c)}#circuitPanel.failure{border-color:#b34836;background:linear-gradient(135deg,#ffe1c3,#f4b095)}
  </style><header><div><small id="circuitStep">ETAPA 1 DE 10</small><h2>🔥 Circuito Queima-Queima</h2></div><button id="circuitAction" hidden></button></header><div id="circuitProgress"><i></i></div><p id="circuitObjective"></p><p id="circuitDeck"></p><p id="circuitStatus"></p>`;
  document.querySelector('.hud').before(panel);

  const shuffle=values=>{const copy=[...values];for(let i=copy.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[copy[i],copy[j]]=[copy[j],copy[i]]}return copy};
  const floorName=floor=>({wood:'madeira',glass:'vidro',rubber:'borracha'}[floor]);
  const freshMission=()=>({shots:0,score:0,zones:new Set(),valid:0,invalid:0,startBurns:0,hits100:0,targets:0,increasing:0,bestIncreasing:0,lastPoints:-1});

  // Banco registrado: 10 famílias × 30 variações = 300 desafios individuais.
  const bank=[],add=(family,index,data)=>bank.push({id:`${family}-${String(index+1).padStart(2,'0')}`,family,...data});
  const scoreTargets=[100,120,140,150,160,180,190,200,210,220,230,240,250,260,270,280,290,300,310,320,330,340,350,360,370,380,390,400,420,450];
  scoreTargets.forEach((points,index)=>add('score',index,{title:['Aquecimento','Ritmo de brasa','Trilha quente','Pulso firme','Fôlego de aço'][index%5],objective:`Faça pelo menos ${points} pontos em até 5 lançamentos.`,test:s=>s.score>=points,progress:s=>`${s.score}/${points} pontos`}));
  Array.from({length:30},(_,index)=>({count:2+index%3,points:40+index*12})).forEach((rule,index)=>add('zones',index,{title:['Explorador de faixas','Mapa do retorno','Pista completa'][index%3],objective:`Some ${rule.points} pontos e acerte ${rule.count} faixas diferentes.`,test:s=>s.score>=rule.points&&s.zones.size>=rule.count,progress:s=>`${s.score}/${rule.points} pontos · ${s.zones.size}/${rule.count} faixas`}));
  Array.from({length:30},(_,index)=>({count:index%5===4?2:1,points:100+index*10})).forEach((rule,index)=>add('hundred',index,{title:['Primeira grande queima','Olho na centelha','Chama certeira'][index%3],objective:`Faça ${rule.count===1?'um acerto':'dois acertos'} em 100 e some ${rule.points} pontos.`,test:s=>s.hits100>=rule.count&&s.score>=rule.points,progress:s=>`${s.hits100}/${rule.count} em 100 · ${s.score}/${rule.points} pontos`}));
  Array.from({length:30},(_,index)=>({count:2+index%4,points:60+index*12})).forEach((rule,index)=>add('valid',index,{title:['Regularidade','Mão constante','Linha segura'][index%3],objective:`Faça ${rule.count} retornos válidos e alcance ${rule.points} pontos.`,test:s=>s.valid>=rule.count&&s.score>=rule.points,progress:s=>`${s.valid}/${rule.count} retornos · ${s.score}/${rule.points} pontos`}));
  Array.from({length:30},(_,index)=>({count:index%4===3?2:1,points:80+index*12})).forEach((rule,index)=>add('target',index,{title:['Na mosca','Leitura do tabuleiro','Bônus ardente'][index%3],objective:`Cumpra ${rule.count} desafio${rule.count===1?'':'s'} e some ${rule.points} pontos.`,test:s=>s.targets>=rule.count&&s.score>=rule.points,progress:s=>`${s.targets}/${rule.count} desafio${rule.count===1?'':'s'} · ${s.score}/${rule.points} pontos`}));
  Array.from({length:30},(_,index)=>({count:2+index%3,points:80+index*11})).forEach((rule,index)=>add('increase',index,{title:['Escalada','Subida controlada','Pressão crescente'][index%3],objective:`Obtenha uma sequência crescente de ${rule.count} retornos e alcance ${rule.points} pontos.`,test:s=>s.bestIncreasing>=rule.count&&s.score>=rule.points,progress:s=>`${s.bestIncreasing}/${rule.count} melhor sequência · ${s.score}/${rule.points} pontos`}));
  ['wood','glass','rubber'].flatMap(floor=>Array.from({length:10},(_,index)=>({floor,index}))).forEach(({floor,index},order)=>{const points=110+index*15+(floor==='rubber'?20:0);add('surface',order,{title:`Domínio da ${floorName(floor)}`,objective:`No piso de ${floorName(floor)}, alcance ${points} pontos.`,floor,test:s=>s.score>=points,progress:s=>`${s.score}/${points} pontos no piso de ${floorName(floor)}`})});
  Array.from({length:30},(_,index)=>({points:150+index*10,zones:2+index%2})).forEach((rule,index)=>add('mixed',index,{title:['Rota estratégica','Circuito de faixas','Trajetória precisa'][index%3],objective:`Faça ${rule.points} pontos e acerte ${rule.zones} faixas diferentes.`,test:s=>s.score>=rule.points&&s.zones.size>=rule.zones,progress:s=>`${s.score}/${rule.points} pontos · ${s.zones.size}/${rule.zones} faixas`}));
  Array.from({length:30},(_,index)=>({count:2+index%3,points:70+index*10})).forEach((rule,index)=>add('clean',index,{title:['Retorno limpo','Sem excesso','Mão delicada'][index%3],objective:`Faça ${rule.count} retornos limpos e some ${rule.points} pontos.`,test:s=>s.valid>=rule.count&&!s.startBurns&&s.score>=rule.points,progress:s=>`${s.valid}/${rule.count} retornos · ${s.score}/${rule.points} pontos`}));
  Array.from({length:30},(_,index)=>{const points=50+index*10;add('endurance',index,{title:['Controle absoluto','Prova de resistência','Cinco na medida'][index%3],objective:`Complete 5 lançamentos válidos e some ${points} pontos.`,endOnly:true,test:s=>s.shots>=5&&!s.invalid&&s.score>=points,progress:s=>`${s.shots}/5 lançamentos · ${s.score}/${points} pontos`})});

  const familyTotals=bank.reduce((totals,mission)=>(totals[mission.family]=(totals[mission.family]||0)+1,totals),{});
  if(bank.length!==300||Object.values(familyTotals).some(total=>total!==30))throw new Error('Banco do Circuito inválido: são exigidos 300 desafios, 30 por família.');

  const KEY='qqeCircuitV2',LEGACY_KEY='qqeCircuitV1',read=key=>{try{return JSON.parse(localStorage.getItem(key)||'null')}catch{return null}};
  const loaded=read(KEY)||read(LEGACY_KEY)||{};
  let career={version:3,stage:Math.min(10,Math.max(1,Number(loaded.stage)||1)),total:Number(loaded.total)||0,completed:Number(loaded.completed)||0,sequence:Array.isArray(loaded.sequence)?loaded.sequence:[],usedIds:Array.isArray(loaded.usedIds)?loaded.usedIds:(Array.isArray(loaded.sequence)?loaded.sequence:[]),deckCycle:Math.max(1,Number(loaded.deckCycle)||1),readyForNew:Boolean(loaded.readyForNew)};
  const save=()=>localStorage.setItem(KEY,JSON.stringify(career)),byId=new Map(bank.map(mission=>[mission.id,mission]));
  // Baralho determinístico: uma vez usado, o desafio só volta após os 300 serem usados.
  const drawCircuit=()=>{let used=new Set((career.usedIds||[]).filter(id=>byId.has(id))),cycle=career.deckCycle;if(bank.length-used.size<10){used=new Set();cycle++;}const sequence=shuffle([...new Set(bank.map(mission=>mission.family))]).map(family=>shuffle(bank.filter(mission=>mission.family===family&&!used.has(mission.id)))[0].id);return{sequence,usedIds:[...used,...sequence],deckCycle:cycle}};
  const ensureSequence=()=>{const valid=career.sequence.length===10&&career.sequence.every(id=>byId.has(id));if(!valid||career.readyForNew){const draw=drawCircuit();career={...career,stage:1,total:0,...draw,readyForNew:false};save()}};
  ensureSequence();
  let missionState,lastEvent='',resolved=false;
  const step=panel.querySelector('#circuitStep'),objective=panel.querySelector('#circuitObjective'),deck=panel.querySelector('#circuitDeck'),message=panel.querySelector('#circuitStatus'),bar=panel.querySelector('#circuitProgress i'),action=panel.querySelector('#circuitAction');
  const currentMission=()=>byId.get(career.sequence[Math.min(9,career.stage-1)]);
  function configureFloor(mission){if(!mission.floor)return;document.querySelector('#difficulty').value='custom';document.querySelector('#floor').value=mission.floor;document.querySelector('#floor').dispatchEvent(new Event('change'))}
  function beginMission(){ensureSequence();resolved=false;lastEvent='';missionState=freshMission();panel.className='';const mission=currentMission();step.textContent=`ETAPA ${career.stage} DE 10 · ${mission.title}`;objective.textContent=mission.objective;deck.textContent=`Baralho ${career.deckCycle}: ${career.usedIds.length}/300 desafios sinalizados · ${300-career.usedIds.length} disponíveis.`;message.textContent=mission.progress(missionState);bar.style.width=`${(career.stage-1)/10*100}%`;action.hidden=true;configureFloor(mission)}
  function resolve(success){if(resolved)return;resolved=true;flick.disabled=true;panel.className=success?'success':'failure';if(success){career.total+=missionState.score;if(career.stage>=10){career.stage=1;career.completed++;career.readyForNew=true;message.textContent=`Circuito concluído! ${career.total.toLocaleString('pt-BR')} pontos acumulados. O próximo retirará outras 10 cartas do baralho.`;action.textContent='Novo circuito aleatório'}else{career.stage++;message.textContent=`Etapa concluída! Total do circuito: ${career.total.toLocaleString('pt-BR')} pontos.`;action.textContent='Próxima etapa'}bar.style.width='100%'}else{message.textContent='Objetivo não alcançado em 5 lançamentos. Clique em “Repetir etapa” para reiniciar este desafio.';action.textContent='↻ Repetir etapa'}save();action.hidden=false}
  function record(){if(mode.value!=='circuit'||resolved)return;const text=precision.textContent.trim(),turn=document.querySelector('#turn').textContent,score=Number(document.querySelector('#score').textContent)||0;if(!/^RETORNO/i.test(text))return;const key=`${text}|${turn}|${score}`;if(key===lastEvent)return;lastEvent=key;const shot=window.qqeLastShot||{},mission=currentMission(),valid=/^RETORNO:/i.test(text),startBurn=/QUEIMADO/i.test(text),points=Number(shot.rawPoints)||Number(text.match(/—\s*(\d+)\s+pontos/i)?.[1])||0,zone=Number(shot.zone)||Number(text.match(/faixa\s+(\d+)/i)?.[1])||0;missionState.shots++;missionState.score=score;missionState.invalid+=valid?0:1;missionState.startBurns+=startBurn?1:0;if(valid){missionState.valid++;if(zone)missionState.zones.add(zone);missionState.increasing=points>missionState.lastPoints?missionState.increasing+1:1;missionState.bestIncreasing=Math.max(missionState.bestIncreasing,missionState.increasing);missionState.lastPoints=points}if(valid&&points===100)missionState.hits100++;if(valid&&(shot.hitChallenge||/DESAFIO CUMPRIDO/i.test(text)))missionState.targets++;message.textContent=mission.progress(missionState);const finished=/FINALIZADA|FINALIZADO/.test(flick.textContent)||missionState.shots>=5;if(mission.test(missionState)&&!mission.endOnly)resolve(true);else if(finished)resolve(mission.test(missionState))}
  action.onclick=()=>{if(career.readyForNew)ensureSequence();reset();beginMission();flick.disabled=false};
  mode.addEventListener('change',()=>{panel.hidden=mode.value!=='circuit';if(mode.value==='circuit')beginMission()});
  addEventListener('qqe-special-result',()=>{if(mode.value!=='circuit'||resolved)return;const mission=currentMission();missionState.score=Number(document.querySelector('#score').textContent)||missionState.score;message.textContent=mission.progress(missionState);if(mission.test(missionState)&&!mission.endOnly)resolve(true)});
  new MutationObserver(()=>setTimeout(record,0)).observe(precision,{subtree:true,childList:true,characterData:true});
  // Proteção para cinco retornos inválidos: o núcleo encerra a partida, mas o Circuito
  // ainda precisa oferecer a repetição da etapa, mesmo que não haja resultado pontuado.
  new MutationObserver(()=>setTimeout(()=>{if(mode.value==='circuit'&&!resolved&&/FINALIZADA|FINALIZADO/.test(flick.textContent))resolve(false)},0)).observe(flick,{subtree:true,childList:true,characterData:true});
  if(mode.value==='match'&&!window.qqeRoom){mode.value='circuit';mode.dispatchEvent(new Event('change'))}
})();
