(() => {
  const mode=document.querySelector('#mode'),game=document.querySelector('.game'),precision=document.querySelector('#precision'),flick=document.querySelector('#flick');
  if(!mode||!game||!precision||!flick)return;
  const option=document.createElement('option');option.value='circuit';option.textContent='Circuito Queima-Queima';mode.insertBefore(option,mode.firstElementChild);
  const panel=document.createElement('section');panel.id='circuitPanel';panel.hidden=true;
  panel.innerHTML=`<style>
    #circuitPanel{margin:10px 0 14px;padding:12px;border:2px solid #d37b2f;border-radius:13px;background:linear-gradient(135deg,#fff0b8,#ffd989);color:#50321f;text-align:left}#circuitPanel[hidden]{display:none}#circuitPanel header{display:flex;align-items:center;justify-content:space-between;gap:10px}#circuitPanel small{font-weight:900;letter-spacing:.1em;color:#a74628}#circuitPanel h2{margin:3px 0 0;font:700 1.15rem Georgia}#circuitProgress{height:8px;margin:9px 0;overflow:hidden;border-radius:20px;background:#b98a55}#circuitProgress i{display:block;height:100%;background:linear-gradient(90deg,#e44e2d,#ffbd35);transition:width .25s}#circuitObjective{margin:5px 0;font-weight:800}#circuitStatus{margin:4px 0 0;font-size:.82rem}#circuitAction{padding:8px 11px;border:0;border-radius:8px;background:#273d4b;color:#fff;font-weight:800}#circuitAction[hidden]{display:none}#circuitPanel.success{border-color:#4d9c62;background:linear-gradient(135deg,#e8f5c9,#bce29c)}#circuitPanel.failure{border-color:#b34836;background:linear-gradient(135deg,#ffe1c3,#f4b095)}
  </style><header><div><small id="circuitStep">ETAPA 1 DE 10</small><h2>🔥 Circuito Queima-Queima</h2></div><button id="circuitAction" hidden></button></header><div id="circuitProgress"><i></i></div><p id="circuitObjective"></p><p id="circuitStatus"></p>`;
  document.querySelector('.hud').before(panel);

  const shuffle=values=>{const copy=[...values];for(let i=copy.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[copy[i],copy[j]]=[copy[j],copy[i]]}return copy};
  const floorName=floor=>({wood:'madeira',glass:'vidro',rubber:'borracha'}[floor]);
  const freshMission=()=>({shots:0,score:0,zones:new Set(),valid:0,invalid:0,startBurns:0,hits100:0,targets:0,increasing:0,lastPoints:-1});

  // Banco registrado: 10 famílias × 30 variações = 300 desafios individuais.
  const bank=[],add=(family,index,data)=>bank.push({id:`${family}-${String(index+1).padStart(2,'0')}`,family,...data});
  const scoreTargets=[100,120,140,150,160,180,190,200,210,220,230,240,250,260,270,280,290,300,310,320,330,340,350,360,370,380,390,400,420,450];
  scoreTargets.forEach((points,index)=>add('score',index,{title:['Aquecimento','Ritmo de brasa','Trilha quente','Pulso firme','Fôlego de aço'][index%5],objective:`Faça pelo menos ${points} pontos em até 5 lançamentos.`,test:s=>s.score>=points,progress:s=>`${s.score}/${points} pontos`}));
  Array.from({length:30},(_,index)=>2+index%3).forEach((count,index)=>add('zones',index,{title:['Explorador de faixas','Mapa do retorno','Pista completa'][index%3],objective:`Acerte ${count} faixas diferentes em retornos válidos.`,test:s=>s.zones.size>=count,progress:s=>`${s.zones.size}/${count} faixas diferentes`}));
  Array.from({length:30},(_,index)=>index%5===4?2:1).forEach((count,index)=>add('hundred',index,{title:['Primeira grande queima','Olho na centelha','Chama certeira'][index%3],objective:`Pare ${count===1?'uma vez':'duas vezes'} na faixa de 100 pontos.`,test:s=>s.hits100>=count,progress:s=>`${s.hits100}/${count} acerto${count===1?'':'s'} em 100`}));
  Array.from({length:30},(_,index)=>2+index%4).forEach((count,index)=>add('valid',index,{title:['Regularidade','Mão constante','Linha segura'][index%3],objective:`Faça ${count} retornos válidos nesta etapa.`,test:s=>s.valid>=count,progress:s=>`${s.valid}/${count} retornos válidos`}));
  Array.from({length:30},(_,index)=>index%4===3?2:1).forEach((count,index)=>add('target',index,{title:['Na mosca','Leitura do tabuleiro','Bônus ardente'][index%3],objective:`Cumpra ${count===1?'o desafio indicado':'dois desafios indicados'} pelo tabuleiro.`,test:s=>s.targets>=count,progress:s=>`${s.targets}/${count} desafio${count===1?'':'s'} cumprido${count===1?'':'s'}`}));
  Array.from({length:30},(_,index)=>2+index%3).forEach((count,index)=>add('increase',index,{title:['Escalada','Subida controlada','Pressão crescente'][index%3],objective:`Faça ${count} retornos válidos com pontuações crescentes.`,test:s=>s.increasing>=count,progress:s=>`${s.increasing}/${count} resultados crescentes`}));
  ['wood','glass','rubber'].flatMap(floor=>Array.from({length:10},(_,index)=>({floor,index}))).forEach(({floor,index},order)=>{const points=110+index*15+(floor==='rubber'?20:0);add('surface',order,{title:`Domínio da ${floorName(floor)}`,objective:`No piso de ${floorName(floor)}, alcance ${points} pontos.`,floor,test:s=>s.score>=points,progress:s=>`${s.score}/${points} pontos no piso de ${floorName(floor)}`})});
  Array.from({length:30},(_,index)=>({points:150+index%10*20,zones:2+index%2})).forEach((rule,index)=>add('mixed',index,{title:['Rota estratégica','Circuito de faixas','Trajetória precisa'][index%3],objective:`Faça ${rule.points} pontos e acerte ${rule.zones} faixas diferentes.`,test:s=>s.score>=rule.points&&s.zones.size>=rule.zones,progress:s=>`${s.score}/${rule.points} pontos · ${s.zones.size}/${rule.zones} faixas`}));
  Array.from({length:30},(_,index)=>2+index%3).forEach((count,index)=>add('clean',index,{title:['Retorno limpo','Sem excesso','Mão delicada'][index%3],objective:`Faça ${count} retornos válidos sem tocar a parede inicial.`,test:s=>s.valid>=count&&!s.startBurns,progress:s=>`${s.valid}/${count} retornos · ${s.startBurns} queimadas`}));
  Array.from({length:30},(_,index)=>add('endurance',index,{title:['Controle absoluto','Prova de resistência','Cinco na medida'][index%3],objective:'Complete os 5 lançamentos sem nenhuma tentativa inválida.',endOnly:true,test:s=>s.shots>=5&&!s.invalid,progress:s=>`${s.shots}/5 lançamentos · ${s.invalid} inválidos`}));

  const KEY='qqeCircuitV2',LEGACY_KEY='qqeCircuitV1',read=key=>{try{return JSON.parse(localStorage.getItem(key)||'null')}catch{return null}};
  const loaded=read(KEY)||read(LEGACY_KEY)||{};
  let career={version:2,stage:Math.min(10,Math.max(1,Number(loaded.stage)||1)),total:Number(loaded.total)||0,completed:Number(loaded.completed)||0,sequence:Array.isArray(loaded.sequence)?loaded.sequence:[],recentIds:Array.isArray(loaded.recentIds)?loaded.recentIds:(Array.isArray(loaded.sequence)?loaded.sequence:[]),readyForNew:Boolean(loaded.readyForNew)};
  const save=()=>localStorage.setItem(KEY,JSON.stringify(career)),byId=new Map(bank.map(mission=>[mission.id,mission]));
  // Cada novo circuito ignora os 50 desafios mais recentes (cinco circuitos inteiros).
  const buildSequence=()=>{const recent=new Set(career.recentIds||[]);return shuffle([...new Set(bank.map(mission=>mission.family))]).map(family=>{const candidates=bank.filter(mission=>mission.family===family&&!recent.has(mission.id));return shuffle(candidates.length?candidates:bank.filter(mission=>mission.family===family))[0].id})};
  const ensureSequence=()=>{const valid=career.sequence.length===10&&career.sequence.every(id=>byId.has(id));if(!valid||career.readyForNew){const sequence=buildSequence();career={...career,stage:1,total:0,sequence,recentIds:[...(career.recentIds||[]),...sequence].slice(-50),readyForNew:false};save()}};
  ensureSequence();
  let missionState,lastEvent='',resolved=false;
  const step=panel.querySelector('#circuitStep'),objective=panel.querySelector('#circuitObjective'),message=panel.querySelector('#circuitStatus'),bar=panel.querySelector('#circuitProgress i'),action=panel.querySelector('#circuitAction');
  const currentMission=()=>byId.get(career.sequence[Math.min(9,career.stage-1)]);
  function configureFloor(mission){if(!mission.floor)return;document.querySelector('#difficulty').value='custom';document.querySelector('#floor').value=mission.floor;document.querySelector('#floor').dispatchEvent(new Event('change'))}
  function beginMission(){ensureSequence();resolved=false;lastEvent='';missionState=freshMission();panel.className='';const mission=currentMission();step.textContent=`ETAPA ${career.stage} DE 10 · ${mission.title}`;objective.textContent=mission.objective;message.textContent=mission.progress(missionState);bar.style.width=`${(career.stage-1)/10*100}%`;action.hidden=true;configureFloor(mission)}
  function resolve(success){if(resolved)return;resolved=true;flick.disabled=true;panel.className=success?'success':'failure';if(success){career.total+=missionState.score;if(career.stage>=10){career.stage=1;career.completed++;career.readyForNew=true;message.textContent=`Circuito concluído! ${career.total.toLocaleString('pt-BR')} pontos acumulados. O próximo terá 10 desafios inéditos.`;action.textContent='Novo circuito aleatório'}else{career.stage++;message.textContent=`Etapa concluída! Total do circuito: ${career.total.toLocaleString('pt-BR')} pontos.`;action.textContent='Próxima etapa'}bar.style.width='100%'}else{message.textContent='Objetivo não alcançado em 5 lançamentos. Tente novamente nesta mesma etapa.';action.textContent='Repetir etapa'}save();action.hidden=false}
  function record(){if(mode.value!=='circuit'||resolved)return;const text=precision.textContent.trim(),turn=document.querySelector('#turn').textContent,score=Number(document.querySelector('#score').textContent)||0;if(!/^RETORNO/i.test(text))return;const key=`${text}|${turn}|${score}`;if(key===lastEvent)return;lastEvent=key;const shot=window.qqeLastShot||{},mission=currentMission(),valid=/^RETORNO:/i.test(text),startBurn=/QUEIMADO/i.test(text),points=Number(shot.rawPoints)||Number(text.match(/—\s*(\d+)\s+pontos/i)?.[1])||0,zone=Number(shot.zone)||Number(text.match(/faixa\s+(\d+)/i)?.[1])||0;missionState.shots++;missionState.score=score;missionState.invalid+=valid?0:1;missionState.startBurns+=startBurn?1:0;if(valid){missionState.valid++;if(zone)missionState.zones.add(zone);missionState.increasing=points>missionState.lastPoints?missionState.increasing+1:1;missionState.lastPoints=points}if(valid&&points===100)missionState.hits100++;if(valid&&(shot.hitChallenge||/DESAFIO CUMPRIDO/i.test(text)))missionState.targets++;message.textContent=mission.progress(missionState);const finished=/FINALIZADA|FINALIZADO/.test(flick.textContent)||missionState.shots>=5;if(mission.test(missionState)&&!mission.endOnly)resolve(true);else if(finished)resolve(mission.test(missionState))}
  action.onclick=()=>{if(career.readyForNew)ensureSequence();reset();beginMission();flick.disabled=false};
  mode.addEventListener('change',()=>{panel.hidden=mode.value!=='circuit';if(mode.value==='circuit')beginMission()});
  addEventListener('qqe-special-result',()=>{if(mode.value!=='circuit'||resolved)return;const mission=currentMission();missionState.score=Number(document.querySelector('#score').textContent)||missionState.score;message.textContent=mission.progress(missionState);if(mission.test(missionState)&&!mission.endOnly)resolve(true)});
  new MutationObserver(()=>setTimeout(record,0)).observe(precision,{subtree:true,childList:true,characterData:true});
  if(mode.value==='match'&&!window.qqeRoom){mode.value='circuit';mode.dispatchEvent(new Event('change'))}
})();
