(() => {
  const game=document.querySelector('.game'),precision=document.querySelector('#precision'),flick=document.querySelector('#flick'),fill=document.querySelector('#fill'),floor=document.querySelector('#floor');if(!game||!precision||!flick)return;
  const panel=document.createElement('section');panel.id='coachPanel';panel.innerHTML=`
    <style>
      #coachPanel{margin:10px 0 14px;padding:10px 12px;border:2px solid #4d7d8e;border-radius:13px;background:linear-gradient(135deg,#eff9f5,#cee6df);color:#29434b;text-align:left}
      #coachPanel header{display:flex;align-items:center;justify-content:space-between;gap:8px}#coachPanel h2{margin:0;font:700 1.05rem Georgia}#coachMode{padding:5px;border:1px solid #6c929d;border-radius:7px;background:#fff}
      #coachBubble{position:relative;margin:9px 0 7px;padding:9px 11px;border-radius:5px 11px 11px;background:#fff;box-shadow:0 2px 7px #0002;font-size:.8rem;line-height:1.4}#coachBubble:before{content:"";position:absolute;left:-7px;top:9px;border-width:7px 7px 7px 0;border-style:solid;border-color:transparent #fff transparent transparent}
      #coachHelp{display:flex;gap:6px}#coachQuestion{min-width:0;flex:1;padding:7px 9px;border:1px solid #7b9ca4;border-radius:8px}#coachAsk{padding:7px 11px;border:0;border-radius:8px;background:#294b5a;color:#fff;font-weight:800}
      #coachShortcuts{display:flex;gap:5px;flex-wrap:wrap;margin-top:7px}#coachShortcuts button{padding:5px 8px;border:1px solid #8aa5aa;border-radius:99px;background:#f8fffc;color:#34515a;font-size:.68rem}
      @media(max-width:520px){#coachPanel header{align-items:flex-start;flex-direction:column}#coachMode{width:100%}}
    </style>
    <header><h2>🧢 Técnico QQ</h2><label>Acompanhamento <select id="coachMode"><option value="off">Desligado</option><option value="occasional" selected>Dicas ocasionais</option><option value="active">Técnico ativo</option></select></label></header>
    <p id="coachBubble">Estou de olho na pista. Faça um lançamento e eu analiso o resultado sem revelar uma força exata.</p>
    <form id="coachHelp"><input id="coachQuestion" maxlength="100" placeholder="Pergunte ao Técnico QQ…" aria-label="Pergunta ao Técnico QQ"><button id="coachAsk">Perguntar</button></form>
    <div id="coachShortcuts"><button data-question="força">Força</button><button data-question="pisos">Pisos</button><button data-question="100 pontos">100 pontos</button><button data-question="circuito">Circuito</button></div>`;
  const reference=document.querySelector('#challenge');reference.after(panel);
  const coachMode=panel.querySelector('#coachMode'),bubble=panel.querySelector('#coachBubble'),form=panel.querySelector('#coachHelp'),question=panel.querySelector('#coachQuestion');
  let lastCharge=0,lastResult='',launches=0,recentCharges=[];
  coachMode.value=localStorage.getItem('qqeCoachMode')||'occasional';
  coachMode.onchange=()=>{localStorage.setItem('qqeCoachMode',coachMode.value);bubble.textContent=coachMode.value==='off'?'Ficarei em silêncio. Você ainda pode fazer perguntas abaixo.':coachMode.value==='active'?'Acompanhamento ativo: comentarei cada lançamento.':'Darei uma dica quando ela puder fazer diferença.'};
  document.addEventListener('pointerup',()=>{if(charging)lastCharge=Math.max(0,Math.min(100,Number.parseFloat(fill.style.width)||charge||0))},true);
  function speak(text){bubble.textContent=text;panel.classList.remove('coach-speaking');void panel.offsetWidth;panel.classList.add('coach-speaking')}
  function advice(){const text=precision.textContent.trim();if(!/^RETORNO/i.test(text)||text===lastResult)return;lastResult=text;launches++;recentCharges.push(lastCharge);if(recentCharges.length>4)recentCharges.shift();if(coachMode.value==='off'||(coachMode.value==='occasional'&&launches%2!==0))return;const shot=window.qqeLastShot||{},surface=floor.value;
    if(shot.touchedStartWall||/QUEIMADO/i.test(text)){speak(`Força excessiva. Você carregou cerca de ${Math.round(lastCharge)}%. Reduza um pouco, principalmente quando o 100 estiver perto do início.`);return}
    if(!shot.reachedEnd||/INVÁLIDO/i.test(text)){const extra=surface==='rubber'?' Combine a carga com mais impulso extra.':surface==='glass'?' Aumente em passos pequenos: o vidro responde rapidamente.':' Aumente a carga gradualmente.';speak('O botão não alcançou o fim iluminado.'+extra);return}
    if(Number(shot.rawPoints)===100){speak(shot.hitChallenge?'Jogada de mestre: faixa 100 e desafio cumprido na mesma tentativa!':'Excelente leitura do retorno: você encontrou a faixa de 100. Tente repetir com uma pressão semelhante.');return}
    if(shot.hitChallenge){speak('Na mosca! Você leu corretamente a posição da faixa pedida e conquistou o bônus.');return}
    const variation=recentCharges.length>2?Math.max(...recentCharges)-Math.min(...recentCharges):0;if(variation>25){speak('Sua carga está variando bastante entre as jogadas. Tente fazer ajustes menores para entender melhor o piso.');return}
    const surfaceTip={wood:'A madeira responde de forma equilibrada: use esta jogada como referência.',glass:'No vidro, poucos pontos percentuais já alteram bastante o retorno.',rubber:'Na borracha, observe a combinação entre carga principal e impulso extra.'}[surface];speak(surfaceTip)}
  function answer(value){const q=value.trim().toLocaleLowerCase();if(!q)return;if(/circuit|etapa|missão/.test(q))speak('No Circuito, cada etapa tem um objetivo próprio e cinco tentativas. O progresso fica salvo neste dispositivo.');else if(/vidro|madeira|borracha|piso/.test(q))speak('Madeira é equilibrada, vidro é mais sensível e borracha exige força e impulso extra. Evite usar a mesma pressão nos três.');else if(/100|queima/.test(q))speak('Para marcar 100, primeiro alcance o fim iluminado e depois pare dentro da faixa 100. Se ela estiver no início, não toque a parede de retorno.');else if(/força|carga|pressão/.test(q))speak('Use a última parada como referência: se não alcançou o fim, aumente; se tocou a parede inicial, reduza. Faça mudanças pequenas.');else if(/desafio|bônus/.test(q))speak('A faixa do desafio é anunciada antes da jogada. Acertá-la concede +25, ou +50 durante o evento Desafio Turbinado.');else if(/evento|surpresa/.test(q))speak('Rodadas Surpresa aparecem ocasionalmente. Leia o cartão antes de carregar, pois bônus, limites e riscos mudam naquela jogada.');else speak('Posso ajudar com força, pisos, faixa 100, Circuito, desafios e Rodadas Surpresa. O segredo é ajustar pouco a pouco.')}
  form.onsubmit=e=>{e.preventDefault();answer(question.value);question.value=''};panel.querySelector('#coachShortcuts').onclick=e=>{const value=e.target.dataset.question;if(value)answer(value)};
  new MutationObserver(()=>setTimeout(advice,0)).observe(precision,{subtree:true,childList:true,characterData:true});
})();
