(() => {
  const game=document.querySelector('.game');
  if(!game)return;
  const STORAGE_KEY='qqeFeedbackLocalV1';
  const section=document.createElement('section');
  section.id='communityPanel';
  section.innerHTML=`<style>
    #communityPanel{margin-top:22px;padding:17px;border:2px solid #c89143;border-radius:14px;background:#fff0c8;text-align:left;color:#553a28}#communityPanel h2{margin:0 0 4px;font:700 1.35rem Georgia;color:#59351f}#communitySummary{margin:5px 0 12px;font-size:.9rem}
    #feedbackForm{display:grid;grid-template-columns:minmax(140px,.55fr) minmax(220px,1.45fr) auto;gap:8px;align-items:end}#feedbackForm label{display:grid;gap:4px;font-size:.8rem;font-weight:bold}#feedbackForm input,#feedbackForm textarea{width:100%;padding:8px;border:1px solid #b88649;border-radius:8px;background:#fffdf4;font:inherit;resize:vertical}#feedbackForm button{padding:10px 14px;border:0;border-radius:9px;background:#253a4b;color:#fff;font-weight:bold}
    #starPicker{display:flex;gap:2px;margin:5px 0 10px}#starPicker button{padding:0;border:0;background:none;color:#b4a589;font-size:1.85rem;line-height:1}#starPicker button.on{color:#e5a51e;text-shadow:0 1px #8d5b10}#feedbackStatus{min-height:1.2em;margin:8px 0;font-size:.78rem;color:#76573e}#feedbackList{display:grid;gap:7px;max-height:250px;overflow:auto}.feedbackItem{padding:9px;border:1px solid #dec28f;border-radius:9px;background:#fff9e8}.feedbackItem header{display:flex;justify-content:space-between;gap:8px;font-size:.83rem}.feedbackItem p{margin:5px 0 0;overflow-wrap:anywhere;font-size:.86rem}.feedbackStars{color:#dc9513;letter-spacing:1px}.feedbackDate{color:#8a7661;font-size:.72rem}@media(max-width:650px){#feedbackForm{grid-template-columns:1fr}#feedbackForm button{width:100%}}
  </style><h2>⭐ Avalie o Queima-queima</h2><p id="communitySummary">Seja o primeiro a avaliar.</p><div id="starPicker" role="radiogroup" aria-label="Avaliação de 1 a 5 estrelas"></div><form id="feedbackForm"><label>Seu nome<input id="feedbackName" maxlength="20" required placeholder="Jogador"></label><label>Comentário<textarea id="feedbackComment" maxlength="500" rows="2" required placeholder="Conte o que achou do jogo…"></textarea></label><button type="submit">Publicar avaliação</button></form><p id="feedbackStatus" aria-live="polite"></p><div id="feedbackList"></div>`;
  game.append(section);
  const $=selector=>section.querySelector(selector),stars=$('#starPicker'),list=$('#feedbackList'),status=$('#feedbackStatus'),summary=$('#communitySummary');
  let rating=0,records=[],shared=false;
  for(let value=1;value<=5;value++){const button=document.createElement('button');button.type='button';button.textContent='★';button.dataset.value=value;button.setAttribute('role','radio');button.setAttribute('aria-label',`${value} estrela${value>1?'s':''}`);button.setAttribute('aria-checked','false');button.onclick=()=>selectRating(value);stars.append(button)}
  function selectRating(value){rating=value;[...stars.children].forEach((button,index)=>{const active=index<value;button.classList.toggle('on',active);button.setAttribute('aria-checked',String(index===value-1))})}
  function localRecords(){try{return JSON.parse(localStorage.getItem(STORAGE_KEY)||'[]')}catch{return[]}}
  function saveLocal(item){const saved=[item,...localRecords()].slice(0,30);localStorage.setItem(STORAGE_KEY,JSON.stringify(saved));return saved}
  function render(){list.replaceChildren();const average=records.length?records.reduce((total,item)=>total+Number(item.rating||0),0)/records.length:0;summary.textContent=records.length?`${average.toFixed(1).replace('.',',')} de 5 · ${records.length} avaliação${records.length===1?'':'ões'}`:'Seja o primeiro a avaliar.';records.forEach(item=>{const article=document.createElement('article'),header=document.createElement('header'),name=document.createElement('b'),starsText=document.createElement('span'),date=document.createElement('time'),comment=document.createElement('p');article.className='feedbackItem';name.textContent=String(item.player_name||'Jogador').slice(0,20);starsText.className='feedbackStars';starsText.textContent='★'.repeat(Number(item.rating)||0)+'☆'.repeat(5-(Number(item.rating)||0));date.className='feedbackDate';date.textContent=new Date(item.created_at||Date.now()).toLocaleDateString('pt-BR');comment.textContent=String(item.comment||'').slice(0,500);header.append(name,starsText,date);article.append(header,comment);list.append(article)})}
  async function load(){const client=window.qqeSupabase;if(client){const {data,error}=await client.from('game_feedback').select('id,player_name,rating,comment,created_at').order('created_at',{ascending:false}).limit(30);if(!error){records=data||[];shared=true;status.textContent='Avaliações compartilhadas com toda a comunidade.';render();return}}records=localRecords();shared=false;status.textContent='Avaliações em modo local até ativar community.sql no Supabase.';render()}
  $('#feedbackForm').onsubmit=async event=>{event.preventDefault();const name=$('#feedbackName').value.trim(),comment=$('#feedbackComment').value.trim();if(!rating){status.textContent='Escolha de 1 a 5 estrelas.';return}if(!name||!comment)return;const item={player_name:name.slice(0,20),rating,comment:comment.slice(0,500),created_at:new Date().toISOString()};status.textContent='Publicando…';if(shared&&window.qqeSupabase){const {data,error}=await window.qqeSupabase.from('game_feedback').insert(item).select('id,player_name,rating,comment,created_at').single();if(!error){records=[data,...records].slice(0,30);status.textContent='Obrigado! Sua avaliação foi publicada.';finish();return}}item.id=globalThis.crypto?.randomUUID?.()||String(Date.now());records=saveLocal(item);status.textContent='Avaliação salva neste dispositivo.';finish()};
  function finish(){$('#feedbackComment').value='';selectRating(0);render()}
  const syncName=()=>{const roomName=document.querySelector('#roomName')?.value.trim();if(roomName&&!$('#feedbackName').value)$('#feedbackName').value=roomName};document.addEventListener('focusin',event=>{if(section.contains(event.target))syncName()});load();
})();
