(() => {
  const mode=document.querySelector('#mode'),game=document.querySelector('.game'),resetButton=document.querySelector('#reset'),flick=document.querySelector('#flick');
  if(!mode||!game||!resetButton||!flick)return;
  const option=document.createElement('option');option.value='nback';option.textContent='Mente em Chamas — N-Back';mode.append(option);
  const panel=document.createElement('section');panel.id='nbackPanel';panel.hidden=true;
  panel.innerHTML=`<style>
    #nbackPanel{margin:10px 0 14px;padding:12px;border:2px solid #7654a6;border-radius:13px;background:linear-gradient(135deg,#f3ebff,#ded0fa);color:#35204e;text-align:left}#nbackPanel[hidden]{display:none}#nbackPanel header{display:flex;justify-content:space-between;align-items:center;gap:8px}#nbackPanel h2{margin:0;font:700 1.08rem Georgia}#nbackLevel{padding:5px 8px;border:1px solid #8d70b6;border-radius:8px;background:#fff;color:#45286a;font-weight:bold}#nbackCue{display:grid;place-items:center;min-height:58px;margin:10px 0 7px;border:2px dashed #8b68b3;border-radius:11px;background:#fff9ff;font-size:2rem}#nbackInstruction,#nbackResult{margin:5px 0;font-size:.8rem;font-weight:bold}#nbackActions,#nbackSoundActions{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:9px}#nbackActions button,#nbackSoundActions button{padding:9px;border:0;border-radius:9px;font-weight:900}#nbackSame,#nbackSoundSame{background:#4e9a73;color:#fff}#nbackDifferent,#nbackSoundDifferent{background:#d26b47;color:#fff}#nbackActions button[disabled],#nbackSoundActions button[disabled]{opacity:.55;cursor:default}#nbackSoundActions[hidden],#nbackSoundLabel[hidden],#nbackFinal[hidden]{display:none}#nbackSoundLabel{margin:10px 0 -3px;color:#604282;font-size:.72rem;font-weight:900;letter-spacing:.06em}#nbackScore{color:#604282;font-size:.75rem}#nbackFinal{margin:9px 0 2px;padding:8px 10px;border-radius:9px;background:#fff8cf;color:#5c3c14;font-size:.8rem;font-weight:900}
  </style><header><h2>🧠 Mente em Chamas</h2><label>Nível <select id="nbackLevel"><option value="1">1-Back visual</option><option value="2">2-Back visual</option><option value="3">3-Back visual</option><option value="dual1">Dual-Back 1 · símbolo + som</option><option value="dual2">Dual-Back 2 · símbolo + som</option></select></label></header><div id="nbackCue" aria-live="polite">?</div><p id="nbackInstruction"></p><div id="nbackActions"><button id="nbackSame" type="button">SÍMBOLO IGUAL</button><button id="nbackDifferent" type="button">SÍMBOLO DIFERENTE</button></div><p id="nbackSoundLabel" hidden>🔊 Ouça o tom e responda abaixo</p><div id="nbackSoundActions" hidden><button id="nbackSoundSame" type="button">SOM IGUAL</button><button id="nbackSoundDifferent" type="button">SOM DIFERENTE</button></div><p id="nbackResult" aria-live="polite"></p><small id="nbackScore"></small><p id="nbackFinal" hidden></p>`;
  resetButton.after(panel);
  const cue=panel.querySelector('#nbackCue'),instruction=panel.querySelector('#nbackInstruction'),result=panel.querySelector('#nbackResult'),scoreText=panel.querySelector('#nbackScore'),final=panel.querySelector('#nbackFinal'),level=panel.querySelector('#nbackLevel'),same=panel.querySelector('#nbackSame'),different=panel.querySelector('#nbackDifferent'),soundLabel=panel.querySelector('#nbackSoundLabel'),soundActions=panel.querySelector('#nbackSoundActions'),soundSame=panel.querySelector('#nbackSoundSame'),soundDifferent=panel.querySelector('#nbackSoundDifferent');
  const symbols=['🔥','⚡','🎯','💎','🌙','⭐'],tones=[262,330,392,523];
  let sequence=[],lastRound=-1,answers={visual:null,tone:null},correct=0,attempts=0,audio;
  const isDual=()=>level.value.startsWith('dual'),backLevel=()=>Number(level.value.replace(/\D/g,''))||1,currentIndex=()=>Math.max(0,Math.min(4,Number(document.querySelector('#turn')?.textContent.match(/\d+/)?.[0]||1)-1));
  const differentValue=(values,current)=>{const choices=values.filter(value=>value!==current);return choices[Math.floor(Math.random()*choices.length)]};
  const choice=(values,previous,match)=>match?previous:differentValue(values,previous);
  function createSequence(){const n=backLevel(),next=[];for(let index=0;index<5;index++){const previous=index>=n?next[index-n]:null;next.push({visual:choice(symbols,previous?.visual,index>=n&&Math.random()<.4),tone:choice(tones,previous?.tone,index>=n&&Math.random()<.4)})}return next}
  function playTone(value){try{audio??=new AudioContext();const oscillator=audio.createOscillator(),gain=audio.createGain();oscillator.frequency.value=value;oscillator.type='sine';gain.gain.setValueAtTime(.0001,audio.currentTime);gain.gain.exponentialRampToValueAtTime(.09,audio.currentTime+.02);gain.gain.exponentialRampToValueAtTime(.0001,audio.currentTime+.3);oscillator.connect(gain).connect(audio.destination);oscillator.start();oscillator.stop(audio.currentTime+.32)}catch{}}
  function saveBest(){try{const key=`qqeNBackBest-${level.value}`,previous=Number(localStorage.getItem(key)||0);localStorage.setItem(key,String(Math.max(previous,correct)))}catch{}}
  function scoreLine(index){return `Rodada mental ${index+1}/5 · ${correct}/${attempts} respostas corretas`}
  function start(){sequence=createSequence();lastRound=-1;answers={visual:null,tone:null};correct=0;attempts=0;final.hidden=true;renderRound()}
  function renderRound(){if(mode.value!=='nback')return;panel.hidden=false;const index=currentIndex();if(index===lastRound-1)return;lastRound=index+1;answers={visual:null,tone:null};final.hidden=true;const n=backLevel(),item=sequence[index]||{},hasReference=index>=n;cue.textContent=item.visual||'?';instruction.textContent=hasReference?`Este símbolo é igual ao de ${n} lançamento${n>1?'s':''} atrás? Use sua memória; o símbolo anterior não será mostrado.`:`Memorize este símbolo. A comparação começa no lançamento ${n+1}.`;same.disabled=false;different.disabled=false;soundLabel.hidden=!isDual();soundActions.hidden=!isDual();soundSame.disabled=false;soundDifferent.disabled=false;result.textContent=isDual()?'Responda o símbolo e o som antes de lançar.':'Escolha a resposta antes de lançar.';scoreText.textContent=scoreLine(index);if(isDual())setTimeout(()=>playTone(item.tone),80)}
  function finishAnswer(index){const ready=answers.visual!==null&&(!isDual()||answers.tone!==null);if(!ready)return;same.disabled=true;different.disabled=true;soundSame.disabled=true;soundDifferent.disabled=true;result.textContent='Resposta registrada. Agora faça o lançamento.';scoreText.textContent=scoreLine(index);if(index===4){saveBest();final.hidden=false;const total=isDual()?10:5,percentage=Math.round(correct/total*100);final.textContent=`Fim da sessão: ${correct}/${total} respostas corretas (${percentage}%). Use Recomeçar para tentar novamente.`}}
  function answer(kind,value){if(mode.value!=='nback'||answers[kind]!==null)return;const index=currentIndex(),n=backLevel(),previous=index>=n?sequence[index-n]:null,expected=Boolean(previous&&sequence[index][kind]===previous[kind]);answers[kind]=value;attempts++;if(value===expected)correct++;(kind==='visual'?(value?same:different):(value?soundSame:soundDifferent)).disabled=true;result.textContent=isDual()&&answers.visual===null?'Agora responda o símbolo.':isDual()&&answers.tone===null?'Agora responda o som.':'Resposta registrada.';finishAnswer(index)}
  same.onclick=()=>answer('visual',true);different.onclick=()=>answer('visual',false);soundSame.onclick=()=>answer('tone',true);soundDifferent.onclick=()=>answer('tone',false);
  level.onchange=()=>{start();reset()};
  flick.addEventListener('pointerdown',event=>{const ready=answers.visual!==null&&(!isDual()||answers.tone!==null);if(mode.value==='nback'&&!ready){event.preventDefault();event.stopImmediatePropagation();result.textContent=isDual()?'Responda símbolo e som antes de lançar.':'Primeiro responda antes de lançar.'}},true);
  mode.addEventListener('change',()=>{panel.hidden=mode.value!=='nback';if(mode.value==='nback')start()});
  resetButton.addEventListener('click',()=>setTimeout(()=>{if(mode.value==='nback')start()},0));
  const originalSetup=globalThis.setup;if(typeof originalSetup==='function'){globalThis.setup=function(){originalSetup();renderRound()}}
})();
