(() => {
  const client = window.supabase.createClient(
    'https://cqipwdksohxcgrknjofm.supabase.co',
    'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNxaXB3ZGtzb2h4Y2dya25qb2ZtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODc4NjY5MzIsImV4cCI6MjEwMzQ0MjkzMn0.I3JKEFj3E0RkZ4mPiP98-A0iwx7emTUQqVURi1TKSF0'
  );
  window.qqeSupabase = client;
  let channel,gameChannel,heartbeat;const sessionId=sessionStorage.getItem('qqeClientId')||globalThis.crypto?.randomUUID?.()||`local-${Date.now()}-${Math.random().toString(36).slice(2)}`;sessionStorage.setItem('qqeClientId',sessionId);
  const game = document.querySelector('.game');
  const panel = document.createElement('section');
  panel.id = 'roomPanel';
  panel.innerHTML = `<style>#roomPanel{margin:0 0 18px;padding:14px;border:2px solid #c89143;border-radius:12px;background:#fff0c8}#roomPanel input,#roomPanel select,#roomPanel button{padding:7px;border:1px solid #9d6c36;border-radius:7px}#roomPanel button{background:#253a4b;color:#fff;border:0;font-weight:bold}#roomPeople{margin:9px 0;color:#553a28;font-size:.88rem}#roomGrid{display:grid;grid-template-columns:repeat(auto-fit,minmax(180px,1fr));gap:8px;margin-top:12px}.roomCard{padding:8px;background:#fff9e8;border:1px solid #c89143;border-radius:8px;font-size:.82rem}#roomChat{margin-top:12px;padding:10px;border:1px solid #c89143;border-radius:10px;background:#fff9e8;text-align:left}#roomChat[hidden]{display:none}#chatMessages{height:132px;overflow:auto;margin:7px 0;padding:7px;border-radius:7px;background:#fffdf4;box-shadow:inset 0 0 0 1px #dec28f;font-size:.82rem}#chatMessages:empty:before{content:'As mensagens desta sessão aparecerão aqui.';color:#806f60}#chatMessages p{margin:0 0 6px;overflow-wrap:anywhere}#chatMessages time{margin-left:5px;color:#887869;font-size:.7rem}#chatForm{display:flex;gap:6px}#chatInput{min-width:0;flex:1}@media(max-width:520px){#chatForm{flex-direction:column}#chatMessages{height:112px}}</style><b>🌐 Sala ao vivo</b><div><input id="roomName" maxlength="20" placeholder="Seu nome"><select id="roomRole"><option value="player">Jogador</option><option value="viewer">Espectador</option></select><button id="createRoom">Criar sala</button></div><div><input id="roomCode" maxlength="8" placeholder="Código da sala"><button id="joinRoom">Entrar</button><button id="leaveRoom" hidden>Sair da sala</button></div><div id="roomPeople">Crie uma sala ou entre com um código.</div><div id="challengeActions"></div><div id="roomGrid">Carregando salas abertas…</div><section id="roomChat" hidden><b>💬 Conversa da sala</b><div id="chatMessages" aria-live="polite"></div><form id="chatForm"><input id="chatInput" maxlength="200" autocomplete="off" placeholder="Escreva para quem está na sala…" aria-label="Mensagem"><button type="submit">Enviar</button></form></section>`;
  game.prepend(panel);
  const matchState=document.createElement('div');matchState.id='matchState';matchState.textContent='Modo local · partida neste dispositivo';panel.after(matchState);
  const rematchButton=document.createElement('button');rematchButton.id='rematchButton';rematchButton.hidden=true;rematchButton.textContent='Pedir revanche';matchState.after(rematchButton);
  const duelScoreboard=document.createElement('div');duelScoreboard.id='duelScoreboard';duelScoreboard.hidden=true;rematchButton.after(duelScoreboard);
  const matchStyle=document.createElement('style');matchStyle.textContent='#matchState{margin:0 auto 12px;padding:8px 12px;border:1px solid #c89143;border-radius:9px;background:#fff6d9;color:#553a28;font-weight:bold;font-size:.9rem;text-align:center}#matchState[data-state="ready"]{background:#e3f3dc;border-color:#729b61}#matchState[data-state="waiting"]{background:#fff0c8}#matchState[data-state="viewer"]{background:#e7edf3;border-color:#8999a8}#matchState[data-state="finished"]{background:#ffd9cf;border-color:#d83a2e;color:#9f261e}#rematchButton{display:block;margin:-4px auto 12px;padding:9px 15px;border:0;border-radius:9px;background:#253a4b;color:#fff;font-weight:bold;cursor:pointer}#rematchButton[hidden],#duelScoreboard[hidden]{display:none}#rematchButton:disabled{opacity:.65;cursor:default}#duelScoreboard{display:flex;justify-content:center;gap:10px;flex-wrap:wrap;margin:-3px auto 12px;padding:8px;border:1px solid #c89143;border-radius:10px;background:#fff9e8}#duelScoreboard span{padding:5px 10px;border-radius:7px;background:#eee0ba;font-weight:bold}#duelScoreboard span.current{outline:2px solid #6b9f59;background:#e3f3dc}#duelScoreboard span.winner{outline:2px solid #d89a25;background:#ffe3a1}#roomPanel[data-duel-active="true"] #roomGrid [data-challenge]{display:none}';document.head.append(matchStyle);
  window.qqeSetMatchState=(message,state='waiting')=>{if(matchState.textContent===message&&matchState.dataset.state===state)return;matchState.textContent=message;matchState.dataset.state=state};
  window.qqeUpdateDuelUI=detail=>{const players=detail?.players||[];if(players.length<2){duelScoreboard.hidden=true;panel.dataset.duelActive='false';return}panel.dataset.duelActive='true';duelScoreboard.hidden=false;const scores={...(detail.score||{})},current=players[detail.current_player||0];if(detail.phase!=='finished'&&detail.board?.score!=null)scores[current]=Number(detail.board.score)||0;const highest=Math.max(...players.map(name=>Number(scores[name])||0));duelScoreboard.replaceChildren(...players.map(name=>{const item=document.createElement('span'),value=scores[name];item.textContent=`${name}: ${value==null?'aguardando':value+' pts'}`;if(detail.phase!=='finished'&&name===current)item.classList.add('current');if(detail.phase==='finished'&&Number(value)===highest)item.classList.add('winner');return item}))};
  let rematchGame=null;window.qqeUpdateRematch=detail=>{rematchGame=detail;if(!window.qqeRoom||window.qqeRoom.role!=='player'||detail?.phase!=='finished'||(detail.players||[]).length<2){rematchButton.hidden=true;return}const me=window.qqeRoom.playerName,requests=detail.board?.rematchRequests||[],opponentAsked=requests.some(name=>name!==me);rematchButton.hidden=false;rematchButton.disabled=requests.includes(me)&&!opponentAsked;rematchButton.textContent=opponentAsked?'Aceitar revanche':requests.includes(me)?'Revanche solicitada':'Pedir revanche'};
  rematchButton.onclick=async()=>{if(!rematchGame||!window.qqeRoom)return;rematchButton.disabled=true;const {data}=await client.from('room_games').select('*').eq('room_code',window.qqeRoom.room).single();if(!data)return;const me=window.qqeRoom.playerName,players=data.players||[],requests=[...new Set([...(data.board?.rematchRequests||[]),me])];if(requests.length>=players.length){await client.from('room_games').update({phase:'turn',round:1,score:{},board:{restartToken:Date.now()},current_player:0,updated_at:new Date().toISOString()}).eq('room_code',window.qqeRoom.room)}else await client.from('room_games').update({board:{...(data.board||{}),rematchRequests:requests},updated_at:new Date().toISOString()}).eq('room_code',window.qqeRoom.room)};
  const $ = s => panel.querySelector(s);
  const chatMessages=$('#chatMessages'),roomChat=$('#roomChat');
  const appendChat=message=>{if(!message?.name||!message?.text)return;const line=document.createElement('p'),author=document.createElement('b'),body=document.createTextNode(`: ${String(message.text).slice(0,200)}`),time=document.createElement('time');author.textContent=String(message.name).slice(0,20);time.dateTime=new Date(message.sentAt||Date.now()).toISOString();time.textContent=new Date(message.sentAt||Date.now()).toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'});line.append(author,body,time);chatMessages.append(line);while(chatMessages.children.length>50)chatMessages.firstElementChild.remove();chatMessages.scrollTop=chatMessages.scrollHeight};
  $('#chatForm').onsubmit=event=>{event.preventDefault();const messageText=$('#chatInput').value.trim(),name=$('#roomName').value.trim();if(!currentRoom||!channel||!messageText||!name)return;const payload={id:globalThis.crypto?.randomUUID?.()||`${Date.now()}-${Math.random()}`,name,text:messageText.slice(0,200),sentAt:Date.now()};appendChat(payload);channel.send({type:'broadcast',event:'chat-message',payload});$('#chatInput').value=''};
  $('#roomRole').value='player';$('#roomRole').hidden=true;$('#createRoom').hidden=true;$('#roomPeople').textContent='Escolha uma das salas abertas ou entre com o código.';
  const code = () => Math.random().toString(36).slice(2,8).toUpperCase();
  const checkpointProgress=record=>{const board=record?.board||{},state=board.gameState,turn=String(board.turn||'').match(/(\d+)\s+de\s+5/),round=Number(state?.round)||Number(record?.round)||Number(turn?.[1])||1,score=Number(state?.score??board.score)||0;return (Number(record?.current_player)||0)*10000000+round*100000+score};
  const bestCheckpoint=(room,serverRecord)=>{try{const local=JSON.parse(localStorage.getItem(`qqeCheckpoint:${room}`)||'null'),serverToken=serverRecord?.board?.restartToken||serverRecord?.board?.matchId;if(local?.version!==2)return serverRecord;if(serverToken&&local.matchId!==serverToken)return serverRecord;return checkpointProgress(local)>checkpointProgress(serverRecord)?local:serverRecord}catch{return serverRecord}};
  let currentRoom='',currentRole=''; function requestChallenge(code,target){const name=$('#roomName').value.trim();client.from('game_rooms').select('challenge_queue').eq('code',code).single().then(({data})=>client.from('game_rooms').update({challenge_queue:[...(data.challenge_queue||[]),{from:name,to:target}],updated_at:new Date().toISOString()}).eq('code',code)).then(()=>$('#roomPeople').textContent=`Desafio enviado para ${target}.`)}async function showChallenges(){if(!currentRoom)return;const {data}=await client.from('game_rooms').select('challenge_queue').eq('code',currentRoom).single();const mine=(data?.challenge_queue||[]).filter(c=>c.to===$('#roomName').value.trim());$('#challengeActions').innerHTML=mine.map(c=>`<button data-accept="${c.from}">Aceitar desafio de ${c.from}</button>`).join('');[...panel.querySelectorAll('[data-accept]')].forEach(b=>b.onclick=()=>acceptChallenge(b.dataset.accept))}async function acceptChallenge(name){const {data}=await client.from('game_rooms').select('*').eq('code',currentRoom).single();const ordered=[...new Set([$('#roomName').value.trim(),...(data.active_players||[]).filter(n=>n!==$('#roomName').value.trim()),name])];await client.from('game_rooms').update({challenge_queue:(data.challenge_queue||[]).filter(c=>!(c.from===name&&c.to===$('#roomName').value.trim())),active_players:ordered,spectators:(data.spectators||[]).filter(n=>n!==name),updated_at:new Date().toISOString()}).eq('code',currentRoom);await client.from('room_games').upsert({room_code:currentRoom,players:ordered,current_player:0,phase:'turn',updated_at:new Date().toISOString()});$('#roomPeople').textContent=`Desafio de ${name} aceito: ele entra na próxima partida.`}  function renderPeople(){
    const knownPlayers=window.qqeRoom?.players||[],rawPeople=[...Object.values(channel.presenceState()).flat(),...knownPlayers.map(name=>({name,role:'player'}))],people=[...new Map(rawPeople.map(person=>[`${person.name}|${person.role}`,person])).values()];const players=people.filter(p=>p.role==='player'),viewers=people.filter(p=>p.role!=='player');const duel=document.querySelector('#mode option[value="duel"]');if(duel){duel.disabled=players.length<2;if(players.length<2&&document.querySelector('#mode').value==='duel'){document.querySelector('#mode').value='match';document.querySelector('#mode').dispatchEvent(new Event('change'))}}
    $('#roomPeople').textContent = `Sala ${channel.topic.replace('qqe:','')} · ${people.length} online: ${people.map(p=>`${p.name} (${p.role==='player'?'jogador':'assistindo'})`).join(', ')}`;
    if(currentRole==='viewer')window.qqeSetMatchState('👁 Você está assistindo','viewer');else if(players.length<2)window.qqeSetMatchState('⏳ Aguardando adversário…','waiting');else window.qqeSetMatchState('✅ Jogadores conectados · partida pronta','ready');
  }
  async function refreshRooms(){const {data,error}=await client.from('game_rooms').select('*').order('updated_at',{ascending:false});if(error){$('#roomGrid').textContent='Não foi possível listar salas: '+error.message;return}$('#roomGrid').innerHTML=data.length?data.map(r=>`<div class="roomCard"><b>Sala ${r.code}</b><br>🎮 ${(r.active_players||[]).length} jogando · 👁 ${(r.spectators||[]).length} assistindo<br><button data-room="${r.code}">Entrar</button> ${(r.active_players||[]).map(n=>`<button data-challenge="${r.code}|${n}">Desafiar ${n}</button>`).join('')}</div>`).join(''):'Nenhuma sala aberta no momento.';[...panel.querySelectorAll('[data-challenge]')].forEach(b=>b.onclick=()=>{const [code,target]=b.dataset.challenge.split('|');requestChallenge(code,target)});[...panel.querySelectorAll('[data-room]')].forEach(b=>b.onclick=()=>{$('#roomCode').value=b.dataset.room;connect(b.dataset.room)})}
  async function beat(){if(!currentRoom)return;const roomCode=currentRoom,name=$('#roomName').value.trim();const {data}=await client.from('game_rooms').select('*').eq('code',roomCode).single();if(!data||roomCode!==currentRoom)return;const now=Date.now(),live=Object.fromEntries(Object.entries(data.member_presence||{}).filter(([,t])=>now-new Date(t).getTime()<120000));live[name]=new Date().toISOString();const active=(data.active_players||[]).filter(n=>live[n]),viewers=(data.spectators||[]).filter(n=>live[n]);await client.from('game_rooms').update({member_presence:live,active_players:active,spectators:viewers,updated_at:new Date().toISOString()}).eq('code',roomCode);const {data:gameData}=await client.from('room_games').select('*').eq('room_code',roomCode).maybeSingle();const remaining=(gameData?.players||[]).filter(n=>active.some(a=>a.toLocaleLowerCase()===n.toLocaleLowerCase()));if(gameData&&remaining.length!==gameData.players.length){if((gameData.phase==='turn'||gameData.phase==='moving')&&remaining.length===1&&gameData.players.length>=2)await client.from('room_games').update({players:remaining,phase:'finished',board:{...(gameData.board||{}),status:`Vencedor! ${remaining[0]} — adversário desconectado.`},updated_at:new Date().toISOString()}).eq('room_code',roomCode);else await client.from('room_games').update({players:remaining,updated_at:new Date().toISOString()}).eq('room_code',roomCode)}refreshRooms()}
  async function registerRoom(room){const name=$('#roomName').value.trim(),role=$('#roomRole').value,same=(a,b)=>a.toLocaleLowerCase()===b.toLocaleLowerCase();const {data}=await client.from('game_rooms').select('*').eq('code',room).maybeSingle();let players=data?.active_players||[],viewers=data?.spectators||[],presence=data?.member_presence||{};presence[name]=new Date().toISOString();if(role==='player'){players=players.some(n=>same(n,name))?players:[...players,name];viewers=viewers.filter(n=>!same(n,name))}else{viewers=viewers.some(n=>same(n,name))?viewers:[...viewers,name];players=players.filter(n=>!same(n,name))}await client.from('game_rooms').upsert({code:room,host_name:data?.host_name||name,active_players:players,spectators:viewers,status:'waiting',member_presence:presence,updated_at:new Date().toISOString()});const {data:existingGame}=await client.from('room_games').select('*').eq('room_code',room).maybeSingle();if(!existingGame)await client.from('room_games').insert({room_code:room,players,phase:'waiting',updated_at:new Date().toISOString()});else if(role==='player'&&!existingGame.players?.some(n=>same(n,name)))await client.from('room_games').update({players:[...(existingGame.players||[]),name],updated_at:new Date().toISOString()}).eq('room_code',room);refreshRooms()}
  async function leaveRoom(){if(!currentRoom)return;const name=$('#roomName').value.trim();const {data}=await client.from('room_games').select('*').eq('room_code',currentRoom).single();const remaining=(data?.players||[]).filter(n=>n!==name);if((data?.phase==='turn'||data?.phase==='moving')&&remaining.length===1){await client.from('room_games').update({players:remaining,phase:'finished',board:{...(data.board||{}),status:`Vencedor! ${remaining[0]} — adversário saiu da sala.`},updated_at:new Date().toISOString()}).eq('room_code',currentRoom)}else if(data){await client.from('room_games').update({players:remaining,updated_at:new Date().toISOString()}).eq('room_code',currentRoom)}const {data:room}=await client.from('game_rooms').select('*').eq('code',currentRoom).single();if(room)await client.from('game_rooms').update({active_players:(room.active_players||[]).filter(n=>n!==name),spectators:(room.spectators||[]).filter(n=>n!==name),member_presence:Object.fromEntries(Object.entries(room.member_presence||{}).filter(([n])=>n!==name)),updated_at:new Date().toISOString()}).eq('code',currentRoom);channel?.unsubscribe();gameChannel?.unsubscribe();channel=null;gameChannel=null;clearInterval(heartbeat);currentRoom='';localStorage.removeItem('qqeRoomSession');window.qqeRoom=null;$('#createRoom').disabled=false;$('#joinRoom').disabled=false;$('#leaveRoom').hidden=true;$('#roomPeople').textContent='Você saiu da sala.';refreshRooms()}function connect(room){if(currentRoom)return;const enteredName=$('#roomName').value.trim();if(!enteredName)return $('#roomPeople').textContent='Informe seu nome para entrar.';currentRoom=room;
    channel?.unsubscribe();
    channel = client.channel(`qqe:${room}`, {config:{presence:{key:sessionId},broadcast:{self:false}}});
    channel.on('presence',{event:'sync'},renderPeople).on('broadcast',{event:'game-state'},({payload})=>window.dispatchEvent(new CustomEvent('qqe-remote-state',{detail:payload}))).on('broadcast',{event:'chat-message'},({payload})=>appendChat(payload)).subscribe(async status=>{
      if(status==='SUBSCRIBED'){
        await new Promise(resolve=>setTimeout(resolve,250));const name=$('#roomName').value.trim(),duplicate=Object.values(channel.presenceState()).flat().some(person=>person.name?.toLocaleLowerCase()===name.toLocaleLowerCase()&&person.sessionId!==sessionId);if(duplicate){$('#roomPeople').textContent=`O nome ${name} já está sendo usado nesta sala.`;channel.unsubscribe();channel=null;currentRoom='';return}
        await registerRoom(room);beat();$('#createRoom').disabled=true;$('#joinRoom').disabled=true;$('#leaveRoom').hidden=false;roomChat.hidden=false;chatMessages.replaceChildren();currentRole=$('#roomRole').value;clearInterval(heartbeat);heartbeat=setInterval(beat,30000);
        await channel.track({name:$('#roomName').value.trim(),role:$('#roomRole').value,sessionId});
        $('#roomPeople').textContent=`Sala ${room} conectada. Compartilhe este código.`;
        localStorage.setItem('qqeRoomSession',JSON.stringify({room,name:$('#roomName').value.trim(),role:$('#roomRole').value}));
        const roomSession=window.qqeRoom={sendState:data=>channel.send({type:'broadcast',event:'game-state',payload:data}),role:$('#roomRole').value,playerName:$('#roomName').value.trim(),room,client,hydrating:true,canPublish:false};
        gameChannel=client.channel(`game-db:${room}`).on('postgres_changes',{event:'*',schema:'public',table:'room_games',filter:`room_code=eq.${room}`},payload=>{window.qqePendingGameRecord=payload.new;window.dispatchEvent(new CustomEvent('qqe-game-record',{detail:payload.new}))}).subscribe();
        (async()=>{while(!window.qqeSyncReady&&window.qqeRoom===roomSession)await new Promise(resolve=>setTimeout(resolve,25));if(window.qqeRoom!==roomSession)return;for(let confirmation=0;confirmation<2;confirmation++){const {data}=await client.from('room_games').select('*').eq('room_code',room).maybeSingle();if(data){const restored=bestCheckpoint(room,data);window.qqePendingGameRecord=restored;window.dispatchEvent(new CustomEvent('qqe-game-record',{detail:restored}));if(restored!==data)await client.from('room_games').update({phase:restored.phase,current_player:restored.current_player,round:restored.round,score:restored.score,board:restored.board,updated_at:new Date().toISOString()}).eq('room_code',room)}if(!confirmation)await new Promise(resolve=>setTimeout(resolve,500))}if(window.qqeRoom===roomSession){roomSession.hydrating=false;roomSession.canPublish=true;window.qqePendingGameRecord=null}})();
      }
    });
  }
  setInterval(()=>{if(!channel)return;const online=Object.values(channel.presenceState()).flat(),duel=document.querySelector('#mode option[value="duel"]');if(duel)duel.disabled=online.filter(p=>p.role==='player').length<2},500);
  requestChallenge=async(roomCode,target)=>{const name=$('#roomName').value.trim();if(!name){$('#roomPeople').textContent='Informe seu nome antes de desafiar.';return}if(target===name){$('#roomPeople').textContent='Você não pode desafiar a si mesmo.';return}const {data,error}=await client.from('game_rooms').select('challenge_queue').eq('code',roomCode).single();if(error){$('#roomPeople').textContent='Não foi possível enviar o desafio.';return}const queue=(data?.challenge_queue||[]).filter(item=>item?.from&&item?.to&&item.from!==item.to),exists=queue.some(item=>item.from===name&&item.to===target);if(!exists)await client.from('game_rooms').update({challenge_queue:[...queue,{from:name,to:target}],updated_at:new Date().toISOString()}).eq('code',roomCode);$('#roomPeople').textContent=exists?`O desafio para ${target} já foi enviado.`:`Desafio enviado para ${target}.`};
  const acceptChallengeBase=acceptChallenge;acceptChallenge=async name=>{await acceptChallengeBase(name);await client.from('room_games').update({round:1,score:{},phase:'turn',current_player:0,board:{restartToken:Date.now()},updated_at:new Date().toISOString()}).eq('room_code',currentRoom)};
  client.channel('room-directory').on('postgres_changes',{event:'*',schema:'public',table:'game_rooms'},()=>{refreshRooms();showChallenges()}).subscribe();refreshRooms();
  $('#createRoom').onclick=()=>{const room=code();$('#roomCode').value=room;connect(room)};
  $('#leaveRoom').onclick=()=>{leaveRoom();roomChat.hidden=true;chatMessages.replaceChildren();rematchButton.hidden=true;duelScoreboard.hidden=true;panel.dataset.duelActive='false';window.qqeSetMatchState('Modo local · partida neste dispositivo','local')};
  const saved=JSON.parse(localStorage.getItem('qqeRoomSession')||'null');if(saved){$('#roomName').value=saved.name;$('#roomRole').value='player';connect(saved.room)}
  $('#joinRoom').onclick=()=>{const room=$('#roomCode').value.trim().toUpperCase();if(room)connect(room);else $('#roomPeople').textContent='Digite o código da sala.'};
  const removeDuplicateChallenges=()=>{const seen=new Set(),me=$('#roomName').value.trim();panel.querySelectorAll('#challengeActions [data-accept]').forEach(button=>{const challenger=button.dataset.accept;if(challenger===me||seen.has(challenger))button.remove();else seen.add(challenger)});panel.querySelectorAll('#roomGrid [data-challenge]').forEach(button=>{const target=button.dataset.challenge.split('|')[1];if(target===me)button.remove()})};
  new MutationObserver(removeDuplicateChallenges).observe($('#challengeActions'),{childList:true});
})();
