// Espelha o estado visual da partida para quem está na mesma sala.
(() => {
  let applying=false,previous='',lastScore='',lastRecorded='',rankBurns=0,rankMaxCombo=1,lastRankEvent='';
  const rank=document.createElement('section');rank.id='ranking';rank.innerHTML='<style>#ranking{margin-top:18px;padding:16px;background:#fff6d9;border:3px solid #c89143;border-radius:16px;color:#553a28;text-align:left}#ranking h2{margin:0 0 10px;font:700 1.25rem Georgia}#ranking table{width:100%;border-collapse:collapse;font-size:.82rem}#ranking th,#ranking td{padding:7px 5px;border-bottom:1px solid #dec38a;text-align:left}#ranking th{color:#8b432c}#ranking td:nth-child(3){font-weight:bold;color:#d83a2e}#ranking small{color:#79624b}</style><h2>🏆 Ranking geral deste dispositivo</h2><small>Os melhores resultados ficam salvos neste navegador.</small><div id="rankingList"></div>';document.querySelector('.game').after(rank);
  const renderRanking=()=>{const rows=JSON.parse(localStorage.getItem('qqeRanking')||'[]').sort((a,b)=>b.score-a.score).slice(0,10);document.querySelector('#rankingList').innerHTML=rows.length?`<div style="overflow-x:auto"><table><thead><tr><th>#</th><th>Jogador</th><th>Pontos</th><th>Vitórias</th><th>Queimas</th><th>Combo</th><th>Piso</th><th>Dificuldade</th><th>Modo</th><th>Sala</th><th>Data</th></tr></thead><tbody>${rows.map((r,i)=>`<tr><td>${i+1}</td><td>${r.name}</td><td>${r.score}</td><td>${r.wins||0}</td><td>${r.burns||0}</td><td>x${r.maxCombo||1}</td><td>${r.floor||'—'}</td><td>${r.difficulty||'—'}</td><td>${r.mode||'—'}</td><td>${r.room||'—'}</td><td>${r.date?new Date(r.date).toLocaleDateString('pt-BR'):'—'}</td></tr>`).join('')}</tbody></table></div>`:'Ainda não há resultados.'};
  const trackRankStats=()=>{const score=Number(document.querySelector('#score').textContent)||0,precisionText=document.querySelector('#precision').textContent,statusText=document.querySelector('#status').textContent;if(score===0&&/observe|recome/i.test(statusText)){rankBurns=0;rankMaxCombo=1;lastRankEvent='';return}const event=score+'|'+precisionText;if(event!==lastRankEvent){lastRankEvent=event;if(document.querySelector('#precision').classList.contains('precision-burn'))rankBurns++}const combo=statusText.match(/COMBO x(\d+)/i);if(combo)rankMaxCombo=Math.max(rankMaxCombo,Number(combo[1]))};
  const recordRanking=()=>{const raw=document.querySelector('#score').textContent.trim(),statusText=document.querySelector('#status').textContent;if(!raw||!/(Final:|Partida encerrada|Duelo final)/i.test(statusText)){if(Number(raw)===0)lastRecorded='';return}let score=Number(raw),name=(window.qqeRoom?.playerName||document.querySelector('#playerLabel').textContent||'Jogador').trim(),floor=document.querySelector('#floor').value,difficulty=document.querySelector('#difficulty').selectedOptions[0].textContent.split('—')[0].trim(),mode=document.querySelector('#mode').selectedOptions[0].textContent.split('—')[0].trim(),room=window.qqeRoom?.room||'Local',wins=0;if(mode==='Duelo local'&&/Duelo final:/i.test(statusText)){const entries=statusText.replace(/^.*Duelo final:\s*/i,'').split(' · ').map(v=>{const m=v.match(/^(.*)\s+(\d+)$/);return m?{name:m[1],score:Number(m[2])}:null}).filter(Boolean).sort((a,b)=>b.score-a.score);if(entries[0]){name=entries[0].name;score=entries[0].score;wins=1}}if(!score||!name)return;const eventKey=score+'|'+name+'|'+floor+'|'+mode;if(eventKey===lastRecorded)return;lastRecorded=eventKey;const rows=JSON.parse(localStorage.getItem('qqeRanking')||'[]'),identity=[name,floor,difficulty,mode,room].join('|'),index=rows.findIndex(r=>[r.name,r.floor,r.difficulty,r.mode,r.room].join('|')===identity),entry={name,score,floor,difficulty,mode,room,date:Date.now(),games:1,wins,burns:rankBurns,maxCombo:rankMaxCombo};if(index>=0){const old=rows[index];rows[index]={...old,...entry,score:Math.max(Number(old.score)||0,score),games:(old.games||1)+1,wins:(old.wins||0)+wins,burns:(old.burns||0)+rankBurns,maxCombo:Math.max(old.maxCombo||1,rankMaxCombo)}}else rows.push(entry);localStorage.setItem('qqeRanking',JSON.stringify(rows.sort((a,b)=>b.score-a.score).slice(0,50)));renderRanking()};renderRanking();
  let lastOnlineRank='';const recordOnlineWinner=detail=>{const scores=detail?.board?.finalScores||detail?.score,finishedAt=detail?.board?.finishedAt;if(detail?.phase!=='finished'||!finishedAt||!scores)return;const ordered=Object.entries(scores).sort((a,b)=>b[1]-a[1]);if(ordered.length<2||ordered[0][1]===ordered[1][1])return;const [name,score]=ordered[0],key=[window.qqeRoom?.room,finishedAt,name,score].join('|');if(key===lastOnlineRank)return;lastOnlineRank=key;const floor=detail.board?.config?.floor||detail.floor||document.querySelector('#floor').value,difficulty=document.querySelector('#difficulty').selectedOptions[0].textContent.split('—')[0].trim(),mode='Duelo online',room=window.qqeRoom?.room||detail.room_code||'Online',rows=JSON.parse(localStorage.getItem('qqeRanking')||'[]'),identity=[name,floor,difficulty,mode,room].join('|'),index=rows.findIndex(r=>[r.name,r.floor,r.difficulty,r.mode,r.room].join('|')===identity),entry={name,score:Number(score)||0,floor,difficulty,mode,room,date:Date.now(),games:1,wins:1,burns:name===window.qqeRoom?.playerName?rankBurns:0,maxCombo:name===window.qqeRoom?.playerName?rankMaxCombo:1};if(index>=0){const old=rows[index];rows[index]={...old,...entry,score:Math.max(Number(old.score)||0,entry.score),games:(old.games||1)+1,wins:(old.wins||0)+1,burns:(old.burns||0)+entry.burns,maxCombo:Math.max(old.maxCombo||1,entry.maxCombo)}}else rows.push(entry);localStorage.setItem('qqeRanking',JSON.stringify(rows.sort((a,b)=>b.score-a.score).slice(0,50)));renderRanking()};
  const boardEl=document.querySelector('#board');const playfield=document.createElement('div');playfield.id='playfield';const springBay=document.createElement('div');springBay.id='springBay';const spring=document.createElement('div');spring.id='spring';spring.innerHTML='<span>〰〰〰</span><i></i>';boardEl.parentNode.insertBefore(playfield,boardEl);playfield.append(springBay,boardEl);springBay.append(spring);
  const style=document.createElement('style');style.textContent='#playfield{display:grid;grid-template-columns:78px minmax(0,1fr);align-items:stretch}#springBay{position:relative;min-height:180px;overflow:hidden;border:10px solid #784d2f;border-right:0;border-radius:16px 0 0 16px;background:linear-gradient(#26333b,#111a20);box-shadow:inset 0 0 15px #000}#playfield>#board{border-left:0;border-radius:0 16px 16px 0}#springBay:after{content:"";position:absolute;z-index:6;right:-4px;top:calc(50% - 19px);width:9px;height:38px;border-radius:5px;background:#c89143;box-shadow:0 0 0 2px #f5dfab}#spring{position:absolute;z-index:5;left:5px;top:50%;width:68px;transform:translateY(-50%) scaleX(1);transform-origin:left;color:#d9e8ee;font:900 30px/1 monospace;letter-spacing:-7px;text-shadow:1px 2px #243746;transition:transform .08s}#spring i{display:block;position:absolute;right:-2px;top:9px;width:16px;height:28px;border-radius:5px;background:linear-gradient(90deg,#b4bec2,#f3f5ed,#7e898d);box-shadow:2px 2px 2px #000}#spring.launch{animation:springHit .22s ease-out}@keyframes springHit{0%{transform:translateY(-50%) scaleX(.25)}55%{transform:translate(8px,-50%) scaleX(1.15)}100%{transform:translateY(-50%) scaleX(1)}}';document.head.append(style);
  const floorStyle=document.createElement('style');floorStyle.textContent='#surfaceBadge{display:inline-flex;align-items:center;gap:7px;margin:2px auto 10px;padding:5px 10px;border:1px solid #c89143;border-radius:99px;background:#fff6d9;color:#553a28;font-size:.78rem;font-weight:bold}#board:before{content:"";position:absolute;inset:0;z-index:2;pointer-events:none;opacity:.22}#board.floor-wood{background-color:#c99350;background-image:linear-gradient(90deg,rgba(105,60,28,.12) 1px,transparent 1px),repeating-linear-gradient(2deg,transparent 0 16px,rgba(100,55,24,.1) 17px,transparent 19px),linear-gradient(90deg,#dcb16f,#bd8242 45%,#d7aa65)}#board.floor-wood:before{background:repeating-radial-gradient(ellipse at 20% 50%,transparent 0 22px,rgba(88,47,22,.22) 24px,transparent 27px 45px)}#board.floor-glass{background-color:#86c7df;background-image:linear-gradient(110deg,rgba(255,255,255,.7) 0 8%,transparent 9% 38%,rgba(255,255,255,.32) 39% 45%,transparent 46%),linear-gradient(#bcebf3,#70b7d2);box-shadow:inset 0 0 24px rgba(255,255,255,.75),inset 0 -12px 20px rgba(38,111,148,.25)}#board.floor-glass:before{opacity:.34;background:linear-gradient(115deg,transparent 0 28%,rgba(255,255,255,.9) 30%,transparent 33% 67%,rgba(255,255,255,.55) 69%,transparent 72%)}#board.floor-rubber{background-color:#30383d;background-image:radial-gradient(circle,rgba(255,255,255,.12) 1px,transparent 1.5px),linear-gradient(135deg,#465158,#252c31);background-size:11px 11px,100% 100%;box-shadow:inset 0 8px 18px rgba(0,0,0,.38),inset 0 -5px 12px rgba(255,255,255,.08)}#board.floor-rubber:before{opacity:.18;background:repeating-linear-gradient(135deg,transparent 0 10px,#000 11px 12px)}#board.floor-rubber .lane{background:#d7c5a2;opacity:.62}#board.floor-rubber .slot{color:#fff;text-shadow:0 1px 2px #000}';document.head.append(floorStyle);
  const springFloorStyle=document.createElement('style');springFloorStyle.textContent='#springBay{transition:background .25s,box-shadow .25s}#springBay[data-floor="wood"]{background:linear-gradient(#3e2c22,#17110e);box-shadow:inset 0 0 15px #000,inset 0 0 8px #9a673b}#springBay[data-floor="wood"] #spring{color:#e1b56d;text-shadow:1px 2px #5d351d}#springBay[data-floor="wood"] #spring i{background:linear-gradient(90deg,#8f5b25,#f0cb7a,#6f421d)}#springBay[data-floor="glass"]{background:linear-gradient(135deg,#24566b,#101f29 60%,#397d95);box-shadow:inset 0 0 18px #061117,inset 0 0 12px #80dcf4}#springBay[data-floor="glass"] #spring{color:#dffbff;text-shadow:0 0 7px #6de4ff}#springBay[data-floor="glass"] #spring i{background:linear-gradient(90deg,#78b9ca,#f4ffff,#5294a7);box-shadow:0 0 7px #8deaff}#springBay[data-floor="rubber"]{background:radial-gradient(circle,#4b555b 1px,transparent 2px),linear-gradient(#20272b,#0e1214);background-size:9px 9px,100% 100%;box-shadow:inset 0 0 20px #000}#springBay[data-floor="rubber"] #spring{color:#d8dde0;text-shadow:1px 2px #050708}#springBay[data-floor="rubber"] #spring i{background:linear-gradient(90deg,#991f1a,#ef654e,#6e1714)}';document.head.append(springFloorStyle);
  const surfaceBadge=document.createElement('div');surfaceBadge.id='surfaceBadge';document.querySelector('#floorControls').after(surfaceBadge);
  const floorInfo={wood:['🪵','Madeira clássica','equilíbrio'],glass:['💎','Vidro','alta sensibilidade'],rubber:['⬛','Borracha','maior resistência']};
  const updateFloorLook=value=>{const key=floorInfo[value]?value:'wood',[icon,name,trait]=floorInfo[key];if(surfaceBadge.dataset.floor!==key){surfaceBadge.dataset.floor=key;surfaceBadge.textContent=`${icon} ${name} · ${trait}`}springBay.dataset.floor=key};
  const floorFromBoard=()=>{const match=document.querySelector('#board').className.match(/floor-(wood|glass|rubber)/);updateFloorLook(match?.[1]||document.querySelector('#floor').value)};
  updateFloorLook(document.querySelector('#floor').value);new MutationObserver(floorFromBoard).observe(document.querySelector('#board'),{attributes:true,attributeFilter:['class']});document.querySelector('#floor').addEventListener('change',()=>setTimeout(floorFromBoard,0));document.querySelector('#difficulty').addEventListener('change',()=>setTimeout(floorFromBoard,0));window.addEventListener('qqe-remote-state',({detail})=>updateFloorLook(detail?.config?.floor||document.querySelector('#floor').value));
  const springTimer=setInterval(()=>{const fill=document.querySelector('#fill');const pct=parseFloat(fill?.style.width)||0;spring.style.transform=`translateY(-50%) scaleX(${Math.max(.18,1-pct/120)})`},40);
  document.querySelector('#flick').addEventListener('pointerup',()=>{spring.classList.add('launch');setTimeout(()=>spring.classList.remove('launch'),230)});
  const snap = () => ({
    board: document.querySelector('#board').className,matchId:window.qqeRoom?.matchId||null,
    slots: document.querySelector('#slots').innerHTML,
    puck: document.querySelector('#puck').style.left,
    score: document.querySelector('#score').textContent,
    turn: document.querySelector('#turn').textContent,
    status: document.querySelector('#status').textContent,
    precision: document.querySelector('#precision').textContent,
    metrics: document.querySelector('#metrics')?.textContent||'',gameState:window.qqeGameState?.export?.(),config:{difficulty:document.querySelector('#difficulty').value,floor:document.querySelector('#floor').value,mode:document.querySelector('#mode').value,players:document.querySelector('#playerCount').value}
  });
  const checkpointRecord=board=>{const room=window.qqeRoom;return {version:2,room_code:room.room,matchId:room.matchId||board.matchId||null,players:[...(room.players||[])],current_player:Number(room.currentPlayer)||0,round:Number(board.gameState?.round)||1,score:{...(room.matchScores||{})},phase:'turn',board}};
  const publish = () => {trackRankStats();if(document.querySelector('#mode').value!=='online')recordRanking();if(!window.qqeRoom){const currentStatus=document.querySelector('#status').textContent;if(/final|vencedor|saiu da sala|duelo final/i.test(currentStatus))window.qqeSetMatchState?.('🏁 Partida encerrada','finished');else window.qqeSetMatchState?.('Modo local · partida neste dispositivo','local')}
    if (applying || !window.qqeRoom || window.qqeRoom.hydrating || window.qqeRoom.canPublish!==true || window.qqeRoom.role !== 'player') return;
    if(window.qqeRoom.players?.length>=2&&window.qqeRoom.turnAllowed!==true)return;
    const state = JSON.stringify(snap());
    const board=JSON.parse(state),checkpoint=checkpointRecord(board);localStorage.setItem(`qqeCheckpoint:${window.qqeRoom.room}`,JSON.stringify(checkpoint));
    if(state!==previous){previous=state;lastScore=board.score;window.qqeRoom.sendState(board);window.qqeRoom.client.from('room_games').update({board,phase:'turn',current_player:checkpoint.current_player,round:checkpoint.round,score:checkpoint.score,updated_at:new Date().toISOString()}).eq('room_code',window.qqeRoom.room);if(/final|partida encerrada/i.test(board.status))completeOnlineMatch(board)}
  };
  setInterval(publish,1000);
  let lastOnlineCompletion='';async function completeOnlineMatch(board){if(!window.qqeRoom||window.qqeRoom.role!=='player')return;const room=window.qqeRoom.room,me=window.qqeRoom.playerName,key=[room,me,board.score,board.status].join('|');if(key===lastOnlineCompletion)return;lastOnlineCompletion=key;const {data}=await window.qqeRoom.client.from('room_games').select('*').eq('room_code',room).single();if(!data?.players?.length||data.players[data.current_player]!==me)return;const scores={...(data.score||{}),[me]:Number(board.score)||0},next=data.current_player+1;if(next<data.players.length){await window.qqeRoom.client.from('room_games').update({score:scores,current_player:next,round:1,phase:'turn',board:{restartToken:Date.now(),status:`Vez de ${data.players[next]}`},updated_at:new Date().toISOString()}).eq('room_code',room);return}const ordered=Object.entries(scores).sort((a,b)=>b[1]-a[1]),message=ordered.length>1&&ordered[0][1]===ordered[1][1]?`Empate! ${ordered.map(([name,score])=>`${name}: ${score}`).join(' · ')}`:`Vencedor! ${ordered[0]?.[0]||me} com ${ordered[0]?.[1]||0} pontos`;await window.qqeRoom.client.from('room_games').update({score:scores,phase:'finished',board:{...board,status:message,finalScores:scores,finishedAt:Date.now()},updated_at:new Date().toISOString()}).eq('room_code',room)}
  new MutationObserver(publish).observe(document.querySelector('.game'), {subtree:true,childList:true,characterData:true,attributes:true});
  setInterval(()=>{const roomText=document.querySelector('#roomPeople')?.textContent||'',onlineMatch=roomText.match(/(\d+) jogador/),players=window.qqeRoom?.players?.length||(onlineMatch?Number(onlineMatch[1]):0),duel=document.querySelector('#mode option[value="duel"]'),flick=document.querySelector('#flick'),reset=document.querySelector('#reset');if(duel&&window.qqeRoom){duel.disabled=players<2;if(players<2&&document.querySelector('#mode').value==='duel'){document.querySelector('#mode').value='match';document.querySelector('#mode').dispatchEvent(new Event('change'))}}if(!window.qqeRoom)return;if(window.qqeRoom.role==='viewer'){flick.disabled=true;reset.disabled=true;return}const moving=flick.textContent.includes('MOVIMENTO'),finished=/FINALIZAD|DUELO FINAL/.test(flick.textContent);if(players>=2){flick.disabled=!window.qqeRoom.turnAllowed||moving||finished;reset.disabled=true}else{reset.disabled=false;if(!moving&&!finished)flick.disabled=false}},300);
  window.addEventListener('qqe-game-record', ({detail})=>{if(detail?.players){window.qqeRoom.players=detail.players;window.qqeRoom.turnAllowed=window.qqeRoom.role==='player'&&detail.players[detail.current_player]===window.qqeRoom.playerName;const count=document.querySelector('#playerCount');const mode=document.querySelector('#mode');if(count&&detail.players.length>=2){mode.value='duel';count.value=Math.min(4,detail.players.length);count.dispatchEvent(new Event('change'));[...document.querySelectorAll('#playerInputs input')].forEach((input,i)=>input.value=detail.players[i]||'');document.querySelector('#playerLabel').textContent=detail.players[detail.current_player]||''}}if(detail?.board?.config){for(const [key,value] of Object.entries(detail.board.config)){const el=document.querySelector('#'+(key==='players'?'playerCount':key));if(el)el.value=value}}if(detail?.board)window.dispatchEvent(new CustomEvent('qqe-remote-state',{detail:detail.board}));if(window.qqeRoom?.hydrating){const hydratingRoom=window.qqeRoom;queueMicrotask(()=>{if(window.qqeRoom===hydratingRoom){hydratingRoom.hydrating=false;window.qqePendingGameRecord=null}})}});
  window.addEventListener('qqe-game-record',({detail})=>{if(!window.qqeRoom||!window.qqeSetMatchState)return;const players=detail?.players||[];if(detail?.phase==='finished'){const winner=players[0];window.qqeSetMatchState(winner?`🏆 Partida encerrada · vencedor: ${winner}`:'🏁 Partida encerrada','finished');return}if(window.qqeRoom.role==='viewer'){window.qqeSetMatchState('👁 Você está assistindo','viewer');return}if(players.length<2){window.qqeSetMatchState('⏳ Aguardando adversário…','waiting');return}const current=players[detail.current_player||0];window.qqeSetMatchState(current===window.qqeRoom.playerName?'🎯 Sua vez de jogar':`⏱ Vez de ${current}`,'ready')});
  window.addEventListener('qqe-game-record',({detail})=>{const mode=document.querySelector('#mode'),players=detail?.players||[];if(players.length>=2){let online=mode.querySelector('option[value="online"]');if(!online){online=document.createElement('option');online.value='online';online.textContent='Duelo online';mode.append(online)}mode.value='online'}else if(mode.value==='online'){mode.value='match';mode.dispatchEvent(new Event('change'))}});
  window.addEventListener('qqe-game-record',({detail})=>recordOnlineWinner(detail));
  window.addEventListener('qqe-game-record',({detail})=>{const room=window.qqeRoom;if(!room||detail?.room_code!==room.room)return;room.matchScores={...(detail.score||{})};room.phase=detail.phase;room.currentPlayer=Number(detail.current_player)||0;const matchId=detail.board?.restartToken||detail.board?.matchId||room.matchId||null;if(matchId)room.matchId=matchId;if(detail.board)try{localStorage.setItem(`qqeCheckpoint:${room.room}`,JSON.stringify({version:2,room_code:room.room,matchId,players:[...(detail.players||[])],current_player:room.currentPlayer,round:Number(detail.round)||Number(detail.board?.gameState?.round)||1,score:{...(detail.score||{})},phase:detail.phase,board:detail.board}))}catch{}});
  window.addEventListener('qqe-game-record',({detail})=>{if(detail?.board?.restartToken&&window.qqeRoom)window.qqeRoom.matchId=detail.board.restartToken});
  let lastRestartToken='',suppressResetPublish=false;window.addEventListener('qqe-game-record',({detail})=>{window.qqeUpdateRematch?.(detail);window.qqeUpdateDuelUI?.(detail);const room=window.qqeRoom,players=detail?.players||[],current=players[detail?.current_player||0];if(room&&players.length>=2){room.currentPlayer=detail.current_player||0;room.turnAllowed=room.role==='player'&&current===room.playerName;document.querySelector('#flick').disabled=detail.phase==='finished'||!room.turnAllowed;document.querySelector('#reset').disabled=detail.phase==='finished'||!room.turnAllowed}if(detail?.phase==='finished'&&detail.board?.status)window.qqeSetMatchState?.(`🏆 ${detail.board.status}`,'finished');const token=detail?.board?.restartToken;if(token&&token!==lastRestartToken){lastRestartToken=token;if(!room?.hydrating){suppressResetPublish=true;document.querySelector('#reset').onclick();suppressResetPublish=false}document.querySelector('#flick').disabled=!room?.turnAllowed;document.querySelector('#reset').disabled=!room?.turnAllowed;if(room?.turnAllowed)window.qqeSetMatchState?.('🎯 Sua vez de jogar','ready');else window.qqeSetMatchState?.(`⏱ Vez de ${current}`,'ready')}});
  window.addEventListener('qqe-game-record',({detail})=>{const room=window.qqeRoom,players=detail?.players||[],current=players[detail?.current_player||0],flick=document.querySelector('#flick');if(!room||players.length<2||detail.phase==='finished')return;if(room.turnAllowed){if(flick.textContent.startsWith('AGUARDE'))flick.textContent='SEGURE PARA CARREGAR'}else if(!flick.textContent.includes('MOVIMENTO'))flick.textContent=`AGUARDE — VEZ DE ${(current||'OUTRO JOGADOR').toLocaleUpperCase()}`});
  window.addEventListener('qqe-remote-state', ({detail:s}) => {
    applying = true;
    window.qqeGameState?.import?.(s.gameState);
    const remoteFloor=['wood','glass','rubber'].includes(s.config?.floor)?s.config.floor:'wood';
    document.querySelector('#board').className=(typeof s.board==='string'&&/^floor-(wood|glass|rubber)$/.test(s.board))?s.board:`floor-${remoteFloor}`;
    if(typeof s.slots==='string'&&s.slots.includes('slot'))document.querySelector('#slots').innerHTML=s.slots;
    if(typeof s.puck==='string'&&s.puck)document.querySelector('#puck').style.left=s.puck;
    if(s.score!=null)document.querySelector('#score').textContent=s.score;
    if(typeof s.turn==='string'&&s.turn!=='undefined')document.querySelector('#turn').textContent=s.turn;
    if(typeof s.status==='string')document.querySelector('#status').textContent=s.status;
    if(typeof s.status==='string'&&/final|vencedor|saiu da sala|duelo final/i.test(s.status))window.qqeSetMatchState?.('🏁 Partida encerrada','finished');
    if(typeof s.precision==='string')document.querySelector('#precision').textContent=s.precision;
    if(document.querySelector('#metrics')&&s.metrics&&(window.qqeRoom?.role==='viewer'||window.qqeRoom?.turnAllowed===false))document.querySelector('#metrics').textContent=s.metrics;
    setTimeout(()=>applying=false,0);
  });
  // Métricas e régua do tabuleiro (camada visual, sem alterar a física).
  const metrics=document.createElement('div');metrics.id='metrics';metrics.setAttribute('aria-live','polite');metrics.textContent='Velocidade: 0,00 m/s · Tempo: 0,00 s';document.querySelector('#precision').after(metrics);
  const ruler=document.createElement('div');ruler.id='ruler';ruler.style.gridColumn='2';ruler.setAttribute('aria-label','Medidas do tabuleiro');ruler.innerHTML='<span>0 cm</span><span>20 cm</span><span>40 cm</span><span>60 cm</span><span>80 cm</span><span>100 cm</span>';document.querySelector('#board').after(ruler);
  const metricStyle=document.createElement('style');metricStyle.textContent='#metrics{font-size:.82rem;color:#6c5140;margin:6px 0;text-align:center}#ruler{display:flex;justify-content:space-between;margin:-5px 8px 10px;color:#6c5140;font-size:.68rem;opacity:.7}#ruler span:before{content:"";display:block;height:5px;border-left:1px solid #9d6c36;margin:auto auto 2px}';document.head.append(metricStyle);
  const lockStyle=document.createElement('style');lockStyle.textContent='#flick:disabled{background:linear-gradient(#aeb5b8,#7d878c);box-shadow:0 5px #566066;color:#eef1f2;cursor:not-allowed;opacity:.72}#reset:disabled{opacity:.38;cursor:not-allowed;pointer-events:none}';document.head.append(lockStyle);
  let measuring=false,launched=false,startTime=0,maxSpeed=0,totalDistance=0,lastX=0,lastT=0,stillSince=0;
  const readX=()=>{const raw=document.querySelector('#puck').style.left||'4%';const n=parseFloat(raw)||4;return raw.includes('%')?n/100:n};
  const sample=()=>{if(!measuring)return;const now=performance.now(),x=readX(),dt=(now-lastT)/1000,dx=Math.abs(x-lastX);if(!launched&&dx>.00005){launched=true;startTime=now;lastT=now;lastX=x;stillSince=0}if(launched&&dt>0){maxSpeed=Math.max(maxSpeed,dx/dt);totalDistance+=dx;metrics.textContent=`Velocidade máxima: ${maxSpeed.toFixed(2).replace('.',',')} m/s · Tempo: ${((now-startTime)/1000).toFixed(2).replace('.',',')} s · Distância: ${(totalDistance*100).toFixed(1).replace('.',',')} cm`;if(dx<.00005){if(!stillSince)stillSince=now;else if(now-stillSince>350)finishMetrics()}else stillSince=0}lastX=x;lastT=now;requestAnimationFrame(sample)};
  document.querySelector('#flick').addEventListener('pointerdown',event=>{const room=window.qqeRoom;if(room&&room.players?.length>=2&&room.turnAllowed!==true){event.preventDefault();event.stopImmediatePropagation();document.querySelector('#flick').disabled=true;const current=room.players[room.currentPlayer||0]||'outro jogador';window.qqeSetMatchState?.(`⏱ Vez de ${current}`,'ready')}},true);
  document.querySelector('#flick').addEventListener('pointerdown',()=>{if(document.querySelector('#flick').disabled)return;measuring=true;launched=false;startTime=lastT=performance.now();lastX=readX();maxSpeed=0;totalDistance=0;stillSince=0;metrics.textContent='Velocidade: 0,00 m/s · Tempo: 0,00 s · Distância: 0,0 cm';requestAnimationFrame(sample)});
  document.querySelector('#flick').addEventListener('pointerup',()=>setTimeout(()=>{if(!measuring)return;const moving=document.querySelector('#flick').textContent.includes('MOVIMENTO');if(moving&&!launched){launched=true;startTime=lastT=performance.now();lastX=readX();stillSince=0}else if(!moving&&!launched)measuring=false},0));
  document.querySelector('#reset').addEventListener('click',()=>{previous='';lastScore='';if(!suppressResetPublish&&window.qqeRoom?.role==='player'&&(window.qqeRoom.players||[]).length<2){window.qqeSetMatchState?.('⏳ Aguardando adversário…','waiting');window.qqeRoom.client.from('room_games').update({phase:'turn',board:{},current_player:0,updated_at:new Date().toISOString()}).eq('room_code',window.qqeRoom.room)}});
  const finishMetrics=()=>{if(!measuring||!launched)return;measuring=false;const elapsed=(performance.now()-startTime)/1000;metrics.textContent=`Velocidade máxima: ${maxSpeed.toFixed(2).replace('.',',')} m/s · Tempo: ${elapsed.toFixed(2).replace('.',',')} s · Distância: ${(totalDistance*100).toFixed(1).replace('.',',')} cm`};
  new MutationObserver(()=>{if(measuring&&launched&&!document.querySelector('#flick').textContent.includes('MOVIMENTO'))finishMetrics()}).observe(document.querySelector('#flick'),{subtree:true,childList:true,characterData:true});
  window.qqeSyncReady=true;if(window.qqePendingGameRecord)window.dispatchEvent(new CustomEvent('qqe-game-record',{detail:window.qqePendingGameRecord}));
})();
